//
// This file was generated by the Eclipse Implementation of JAXB, v2.3.3 
// See https://eclipse-ee4j.github.io/jaxb-ri 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2021.08.30 at 11:05:22 AM BST 
//

package jalview.xml.binding.jalview;

import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlAttribute;
import javax.xml.bind.annotation.XmlRootElement;
import javax.xml.bind.annotation.XmlType;

/**
 * &lt;p&gt;Java class for anonymous complex type.
 * 
 * &lt;p&gt;The following schema fragment specifies the expected content
 * contained within this class.
 * 
 * &lt;pre&gt; &amp;lt;complexType&amp;gt; &amp;lt;complexContent&amp;gt;
 * &amp;lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType"&amp;gt;
 * &amp;lt;sequence&amp;gt; &amp;lt;element name="displayCharacter"
 * type="{http://www.w3.org/2001/XMLSchema}string" minOccurs="0"/&amp;gt;
 * &amp;lt;element name="description"
 * type="{http://www.w3.org/2001/XMLSchema}string" minOccurs="0"/&amp;gt;
 * &amp;lt;element name="secondaryStructure" minOccurs="0"&amp;gt;
 * &amp;lt;simpleType&amp;gt; &amp;lt;restriction
 * base="{http://www.w3.org/2001/XMLSchema}string"&amp;gt; &amp;lt;length
 * value="1"/&amp;gt; &amp;lt;/restriction&amp;gt; &amp;lt;/simpleType&amp;gt;
 * &amp;lt;/element&amp;gt; &amp;lt;element name="value"
 * type="{http://www.w3.org/2001/XMLSchema}float" minOccurs="0"/&amp;gt;
 * &amp;lt;/sequence&amp;gt; &amp;lt;attribute name="position" use="required"
 * type="{http://www.w3.org/2001/XMLSchema}int" /&amp;gt; &amp;lt;attribute
 * name="colour" type="{http://www.w3.org/2001/XMLSchema}int" /&amp;gt;
 * &amp;lt;/restriction&amp;gt; &amp;lt;/complexContent&amp;gt;
 * &amp;lt;/complexType&amp;gt; &lt;/pre&gt;
 * 
 * 
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(
  name = "",
  propOrder =
  { "displayCharacter", "description", "secondaryStructure", "value" })
@XmlRootElement(name = "annotationElement")
public class AnnotationElement
{

  protected String displayCharacter;

  protected String description;

  protected String secondaryStructure;

  protected Float value;

  @XmlAttribute(name = "position", required = true)
  protected int position;

  @XmlAttribute(name = "colour")
  protected Integer colour;

  /**
   * Gets the value of the displayCharacter property.
   * 
   * @return possible object is {@link String }
   * 
   */
  public String getDisplayCharacter()
  {
    return displayCharacter;
  }

  /**
   * Sets the value of the displayCharacter property.
   * 
   * @param value
   *          allowed object is {@link String }
   * 
   */
  public void setDisplayCharacter(String value)
  {
    this.displayCharacter = value;
  }

  /**
   * Gets the value of the description property.
   * 
   * @return possible object is {@link String }
   * 
   */
  public String getDescription()
  {
    return description;
  }

  /**
   * Sets the value of the description property.
   * 
   * @param value
   *          allowed object is {@link String }
   * 
   */
  public void setDescription(String value)
  {
    this.description = value;
  }

  /**
   * Gets the value of the secondaryStructure property.
   * 
   * @return possible object is {@link String }
   * 
   */
  public String getSecondaryStructure()
  {
    return secondaryStructure;
  }

  /**
   * Sets the value of the secondaryStructure property.
   * 
   * @param value
   *          allowed object is {@link String }
   * 
   */
  public void setSecondaryStructure(String value)
  {
    this.secondaryStructure = value;
  }

  /**
   * Gets the value of the value property.
   * 
   * @return possible object is {@link Float }
   * 
   */
  public Float getValue()
  {
    return value;
  }

  /**
   * Sets the value of the value property.
   * 
   * @param value
   *          allowed object is {@link Float }
   * 
   */
  public void setValue(Float value)
  {
    this.value = value;
  }

  /**
   * Gets the value of the position property.
   * 
   */
  public int getPosition()
  {
    return position;
  }

  /**
   * Sets the value of the position property.
   * 
   */
  public void setPosition(int value)
  {
    this.position = value;
  }

  /**
   * Gets the value of the colour property.
   * 
   * @return possible object is {@link Integer }
   * 
   */
  public Integer getColour()
  {
    return colour;
  }

  /**
   * Sets the value of the colour property.
   * 
   * @param value
   *          allowed object is {@link Integer }
   * 
   */
  public void setColour(Integer value)
  {
    this.colour = value;
  }

}
