//
// This file was generated by the Eclipse Implementation of JAXB, v2.3.3 
// See https://eclipse-ee4j.github.io/jaxb-ri 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2021.08.30 at 11:05:22 AM BST 
//

package jalview.xml.binding.jalview;

import java.util.ArrayList;
import java.util.List;
import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlAttribute;
import javax.xml.bind.annotation.XmlElement;
import javax.xml.bind.annotation.XmlType;

/**
 * &lt;p&gt;Java class for DoubleMatrix complex type.
 * 
 * &lt;p&gt;The following schema fragment specifies the expected content
 * contained within this class.
 * 
 * &lt;pre&gt; &amp;lt;complexType name="DoubleMatrix"&amp;gt;
 * &amp;lt;complexContent&amp;gt; &amp;lt;restriction
 * base="{http://www.w3.org/2001/XMLSchema}anyType"&amp;gt;
 * &amp;lt;sequence&amp;gt; &amp;lt;element name="row"
 * type="{www.jalview.org}DoubleVector" maxOccurs="unbounded"
 * minOccurs="0"/&amp;gt; &amp;lt;element name="D"
 * type="{www.jalview.org}DoubleVector" minOccurs="0"/&amp;gt; &amp;lt;element
 * name="E" type="{www.jalview.org}DoubleVector" minOccurs="0"/&amp;gt;
 * &amp;lt;/sequence&amp;gt; &amp;lt;attribute name="rows"
 * type="{http://www.w3.org/2001/XMLSchema}int" /&amp;gt; &amp;lt;attribute
 * name="columns" type="{http://www.w3.org/2001/XMLSchema}int" /&amp;gt;
 * &amp;lt;/restriction&amp;gt; &amp;lt;/complexContent&amp;gt;
 * &amp;lt;/complexType&amp;gt; &lt;/pre&gt;
 * 
 * 
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(
  name = "DoubleMatrix",
  namespace = "www.jalview.org",
  propOrder =
  { "row", "d", "e" })
public class DoubleMatrix
{

  protected List<DoubleVector> row;

  @XmlElement(name = "D")
  protected DoubleVector d;

  @XmlElement(name = "E")
  protected DoubleVector e;

  @XmlAttribute(name = "rows")
  protected Integer rows;

  @XmlAttribute(name = "columns")
  protected Integer columns;

  /**
   * Gets the value of the row property.
   * 
   * &lt;p&gt; This accessor method returns a reference to the live list, not a
   * snapshot. Therefore any modification you make to the returned list will be
   * present inside the JAXB object. This is why there is not a
   * &lt;CODE&gt;set&lt;/CODE&gt; method for the row property.
   * 
   * &lt;p&gt; For example, to add a new item, do as follows: &lt;pre&gt;
   * getRow().add(newItem); &lt;/pre&gt;
   * 
   * 
   * &lt;p&gt; Objects of the following type(s) are allowed in the list
   * {@link DoubleVector }
   * 
   * 
   */
  public List<DoubleVector> getRow()
  {
    if (row == null)
    {
      row = new ArrayList<DoubleVector>();
    }
    return this.row;
  }

  /**
   * Gets the value of the d property.
   * 
   * @return possible object is {@link DoubleVector }
   * 
   */
  public DoubleVector getD()
  {
    return d;
  }

  /**
   * Sets the value of the d property.
   * 
   * @param value
   *          allowed object is {@link DoubleVector }
   * 
   */
  public void setD(DoubleVector value)
  {
    this.d = value;
  }

  /**
   * Gets the value of the e property.
   * 
   * @return possible object is {@link DoubleVector }
   * 
   */
  public DoubleVector getE()
  {
    return e;
  }

  /**
   * Sets the value of the e property.
   * 
   * @param value
   *          allowed object is {@link DoubleVector }
   * 
   */
  public void setE(DoubleVector value)
  {
    this.e = value;
  }

  /**
   * Gets the value of the rows property.
   * 
   * @return possible object is {@link Integer }
   * 
   */
  public Integer getRows()
  {
    return rows;
  }

  /**
   * Sets the value of the rows property.
   * 
   * @param value
   *          allowed object is {@link Integer }
   * 
   */
  public void setRows(Integer value)
  {
    this.rows = value;
  }

  /**
   * Gets the value of the columns property.
   * 
   * @return possible object is {@link Integer }
   * 
   */
  public Integer getColumns()
  {
    return columns;
  }

  /**
   * Sets the value of the columns property.
   * 
   * @param value
   *          allowed object is {@link Integer }
   * 
   */
  public void setColumns(Integer value)
  {
    this.columns = value;
  }

}
