//
// This file was generated by the Eclipse Implementation of JAXB, v2.3.3 
// See https://eclipse-ee4j.github.io/jaxb-ri 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2021.08.30 at 11:05:22 AM BST 
//

package jalview.xml.binding.jalview;

import java.util.ArrayList;
import java.util.List;
import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlAttribute;
import javax.xml.bind.annotation.XmlType;

/**
 * &lt;p&gt;Java class for feature complex type.
 * 
 * &lt;p&gt;The following schema fragment specifies the expected content
 * contained within this class.
 * 
 * &lt;pre&gt; &amp;lt;complexType name="feature"&amp;gt;
 * &amp;lt;complexContent&amp;gt; &amp;lt;restriction
 * base="{http://www.w3.org/2001/XMLSchema}anyType"&amp;gt;
 * &amp;lt;sequence&amp;gt; &amp;lt;element name="otherData"
 * maxOccurs="unbounded" minOccurs="0"&amp;gt; &amp;lt;complexType&amp;gt;
 * &amp;lt;complexContent&amp;gt; &amp;lt;restriction
 * base="{http://www.w3.org/2001/XMLSchema}anyType"&amp;gt; &amp;lt;attribute
 * name="key" use="required" type="{http://www.w3.org/2001/XMLSchema}string"
 * /&amp;gt; &amp;lt;attribute name="key2"
 * type="{http://www.w3.org/2001/XMLSchema}string" /&amp;gt; &amp;lt;attribute
 * name="value" use="required" type="{http://www.w3.org/2001/XMLSchema}string"
 * /&amp;gt; &amp;lt;/restriction&amp;gt; &amp;lt;/complexContent&amp;gt;
 * &amp;lt;/complexType&amp;gt; &amp;lt;/element&amp;gt;
 * &amp;lt;/sequence&amp;gt; &amp;lt;attribute name="begin" use="required"
 * type="{http://www.w3.org/2001/XMLSchema}int" /&amp;gt; &amp;lt;attribute
 * name="end" use="required" type="{http://www.w3.org/2001/XMLSchema}int"
 * /&amp;gt; &amp;lt;attribute name="type" use="required"
 * type="{http://www.w3.org/2001/XMLSchema}string" /&amp;gt; &amp;lt;attribute
 * name="description" type="{http://www.w3.org/2001/XMLSchema}string" /&amp;gt;
 * &amp;lt;attribute name="status"
 * type="{http://www.w3.org/2001/XMLSchema}string" /&amp;gt; &amp;lt;attribute
 * name="featureGroup" type="{http://www.w3.org/2001/XMLSchema}string" /&amp;gt;
 * &amp;lt;attribute name="score" type="{http://www.w3.org/2001/XMLSchema}float"
 * /&amp;gt; &amp;lt;/restriction&amp;gt; &amp;lt;/complexContent&amp;gt;
 * &amp;lt;/complexType&amp;gt; &lt;/pre&gt;
 * 
 * 
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(
  name = "feature",
  namespace = "www.jalview.org",
  propOrder =
  { "otherData" })
public class Feature
{

  protected List<Feature.OtherData> otherData;

  @XmlAttribute(name = "begin", required = true)
  protected int begin;

  @XmlAttribute(name = "end", required = true)
  protected int end;

  @XmlAttribute(name = "type", required = true)
  protected String type;

  @XmlAttribute(name = "description")
  protected String description;

  @XmlAttribute(name = "status")
  protected String status;

  @XmlAttribute(name = "featureGroup")
  protected String featureGroup;

  @XmlAttribute(name = "score")
  protected Float score;

  /**
   * Gets the value of the otherData property.
   * 
   * &lt;p&gt; This accessor method returns a reference to the live list, not a
   * snapshot. Therefore any modification you make to the returned list will be
   * present inside the JAXB object. This is why there is not a
   * &lt;CODE&gt;set&lt;/CODE&gt; method for the otherData property.
   * 
   * &lt;p&gt; For example, to add a new item, do as follows: &lt;pre&gt;
   * getOtherData().add(newItem); &lt;/pre&gt;
   * 
   * 
   * &lt;p&gt; Objects of the following type(s) are allowed in the list
   * {@link Feature.OtherData }
   * 
   * 
   */
  public List<Feature.OtherData> getOtherData()
  {
    if (otherData == null)
    {
      otherData = new ArrayList<Feature.OtherData>();
    }
    return this.otherData;
  }

  /**
   * Gets the value of the begin property.
   * 
   */
  public int getBegin()
  {
    return begin;
  }

  /**
   * Sets the value of the begin property.
   * 
   */
  public void setBegin(int value)
  {
    this.begin = value;
  }

  /**
   * Gets the value of the end property.
   * 
   */
  public int getEnd()
  {
    return end;
  }

  /**
   * Sets the value of the end property.
   * 
   */
  public void setEnd(int value)
  {
    this.end = value;
  }

  /**
   * Gets the value of the type property.
   * 
   * @return possible object is {@link String }
   * 
   */
  public String getType()
  {
    return type;
  }

  /**
   * Sets the value of the type property.
   * 
   * @param value
   *          allowed object is {@link String }
   * 
   */
  public void setType(String value)
  {
    this.type = value;
  }

  /**
   * Gets the value of the description property.
   * 
   * @return possible object is {@link String }
   * 
   */
  public String getDescription()
  {
    return description;
  }

  /**
   * Sets the value of the description property.
   * 
   * @param value
   *          allowed object is {@link String }
   * 
   */
  public void setDescription(String value)
  {
    this.description = value;
  }

  /**
   * Gets the value of the status property.
   * 
   * @return possible object is {@link String }
   * 
   */
  public String getStatus()
  {
    return status;
  }

  /**
   * Sets the value of the status property.
   * 
   * @param value
   *          allowed object is {@link String }
   * 
   */
  public void setStatus(String value)
  {
    this.status = value;
  }

  /**
   * Gets the value of the featureGroup property.
   * 
   * @return possible object is {@link String }
   * 
   */
  public String getFeatureGroup()
  {
    return featureGroup;
  }

  /**
   * Sets the value of the featureGroup property.
   * 
   * @param value
   *          allowed object is {@link String }
   * 
   */
  public void setFeatureGroup(String value)
  {
    this.featureGroup = value;
  }

  /**
   * Gets the value of the score property.
   * 
   * @return possible object is {@link Float }
   * 
   */
  public Float getScore()
  {
    return score;
  }

  /**
   * Sets the value of the score property.
   * 
   * @param value
   *          allowed object is {@link Float }
   * 
   */
  public void setScore(Float value)
  {
    this.score = value;
  }

  /**
   * &lt;p&gt;Java class for anonymous complex type.
   * 
   * &lt;p&gt;The following schema fragment specifies the expected content
   * contained within this class.
   * 
   * &lt;pre&gt; &amp;lt;complexType&amp;gt; &amp;lt;complexContent&amp;gt;
   * &amp;lt;restriction
   * base="{http://www.w3.org/2001/XMLSchema}anyType"&amp;gt; &amp;lt;attribute
   * name="key" use="required" type="{http://www.w3.org/2001/XMLSchema}string"
   * /&amp;gt; &amp;lt;attribute name="key2"
   * type="{http://www.w3.org/2001/XMLSchema}string" /&amp;gt; &amp;lt;attribute
   * name="value" use="required" type="{http://www.w3.org/2001/XMLSchema}string"
   * /&amp;gt; &amp;lt;/restriction&amp;gt; &amp;lt;/complexContent&amp;gt;
   * &amp;lt;/complexType&amp;gt; &lt;/pre&gt;
   * 
   * 
   */
  @XmlAccessorType(XmlAccessType.FIELD)
  @XmlType(name = "")
  public static class OtherData
  {

    @XmlAttribute(name = "key", required = true)
    protected String key;

    @XmlAttribute(name = "key2")
    protected String key2;

    @XmlAttribute(name = "value", required = true)
    protected String value;

    /**
     * Gets the value of the key property.
     * 
     * @return possible object is {@link String }
     * 
     */
    public String getKey()
    {
      return key;
    }

    /**
     * Sets the value of the key property.
     * 
     * @param value
     *          allowed object is {@link String }
     * 
     */
    public void setKey(String value)
    {
      this.key = value;
    }

    /**
     * Gets the value of the key2 property.
     * 
     * @return possible object is {@link String }
     * 
     */
    public String getKey2()
    {
      return key2;
    }

    /**
     * Sets the value of the key2 property.
     * 
     * @param value
     *          allowed object is {@link String }
     * 
     */
    public void setKey2(String value)
    {
      this.key2 = value;
    }

    /**
     * Gets the value of the value property.
     * 
     * @return possible object is {@link String }
     * 
     */
    public String getValue()
    {
      return value;
    }

    /**
     * Sets the value of the value property.
     * 
     * @param value
     *          allowed object is {@link String }
     * 
     */
    public void setValue(String value)
    {
      this.value = value;
    }

  }

}
