//
// This file was generated by the Eclipse Implementation of JAXB, v2.3.3 
// See https://eclipse-ee4j.github.io/jaxb-ri 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2021.08.30 at 11:05:22 AM BST 
//

package jalview.xml.binding.jalview;

import java.util.ArrayList;
import java.util.List;
import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlAttribute;
import javax.xml.bind.annotation.XmlElement;
import javax.xml.bind.annotation.XmlType;

/**
 * &lt;p&gt;Java class for FeatureMatcher complex type.
 * 
 * &lt;p&gt;The following schema fragment specifies the expected content
 * contained within this class.
 * 
 * &lt;pre&gt; &amp;lt;complexType name="FeatureMatcher"&amp;gt;
 * &amp;lt;complexContent&amp;gt; &amp;lt;restriction
 * base="{http://www.w3.org/2001/XMLSchema}anyType"&amp;gt;
 * &amp;lt;sequence&amp;gt; &amp;lt;element name="attributeName"
 * type="{http://www.w3.org/2001/XMLSchema}string" maxOccurs="2"
 * minOccurs="0"/&amp;gt; &amp;lt;element name="condition"
 * type="{http://www.w3.org/2001/XMLSchema}string"/&amp;gt; &amp;lt;element
 * name="value" type="{http://www.w3.org/2001/XMLSchema}string"/&amp;gt;
 * &amp;lt;/sequence&amp;gt; &amp;lt;attribute name="by"
 * type="{www.jalview.org/colours}FilterBy" /&amp;gt;
 * &amp;lt;/restriction&amp;gt; &amp;lt;/complexContent&amp;gt;
 * &amp;lt;/complexType&amp;gt; &lt;/pre&gt;
 * 
 * 
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(
  name = "FeatureMatcher",
  namespace = "www.jalview.org/colours",
  propOrder =
  { "attributeName", "condition", "value" })
public class FeatureMatcher
{

  @XmlElement(namespace = "")
  protected List<String> attributeName;

  @XmlElement(namespace = "", required = true)
  protected String condition;

  @XmlElement(namespace = "", required = true)
  protected String value;

  @XmlAttribute(name = "by")
  protected FilterBy by;

  /**
   * Gets the value of the attributeName property.
   * 
   * &lt;p&gt; This accessor method returns a reference to the live list, not a
   * snapshot. Therefore any modification you make to the returned list will be
   * present inside the JAXB object. This is why there is not a
   * &lt;CODE&gt;set&lt;/CODE&gt; method for the attributeName property.
   * 
   * &lt;p&gt; For example, to add a new item, do as follows: &lt;pre&gt;
   * getAttributeName().add(newItem); &lt;/pre&gt;
   * 
   * 
   * &lt;p&gt; Objects of the following type(s) are allowed in the list
   * {@link String }
   * 
   * 
   */
  public List<String> getAttributeName()
  {
    if (attributeName == null)
    {
      attributeName = new ArrayList<String>();
    }
    return this.attributeName;
  }

  /**
   * Gets the value of the condition property.
   * 
   * @return possible object is {@link String }
   * 
   */
  public String getCondition()
  {
    return condition;
  }

  /**
   * Sets the value of the condition property.
   * 
   * @param value
   *          allowed object is {@link String }
   * 
   */
  public void setCondition(String value)
  {
    this.condition = value;
  }

  /**
   * Gets the value of the value property.
   * 
   * @return possible object is {@link String }
   * 
   */
  public String getValue()
  {
    return value;
  }

  /**
   * Sets the value of the value property.
   * 
   * @param value
   *          allowed object is {@link String }
   * 
   */
  public void setValue(String value)
  {
    this.value = value;
  }

  /**
   * Gets the value of the by property.
   * 
   * @return possible object is {@link FilterBy }
   * 
   */
  public FilterBy getBy()
  {
    return by;
  }

  /**
   * Sets the value of the by property.
   * 
   * @param value
   *          allowed object is {@link FilterBy }
   * 
   */
  public void setBy(FilterBy value)
  {
    this.by = value;
  }

}
