//
// This file was generated by the Eclipse Implementation of JAXB, v2.3.3 
// See https://eclipse-ee4j.github.io/jaxb-ri 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2021.08.30 at 11:05:22 AM BST 
//

package jalview.xml.binding.jalview;

import javax.xml.bind.annotation.XmlEnum;
import javax.xml.bind.annotation.XmlEnumValue;
import javax.xml.bind.annotation.XmlType;

/**
 * &lt;p&gt;Java class for FilterBy.
 * 
 * &lt;p&gt;The following schema fragment specifies the expected content
 * contained within this class. &lt;pre&gt; &amp;lt;simpleType
 * name="FilterBy"&amp;gt; &amp;lt;restriction
 * base="{http://www.w3.org/2001/XMLSchema}string"&amp;gt; &amp;lt;enumeration
 * value="byLabel"/&amp;gt; &amp;lt;enumeration value="byScore"/&amp;gt;
 * &amp;lt;enumeration value="byAttribute"/&amp;gt; &amp;lt;/restriction&amp;gt;
 * &amp;lt;/simpleType&amp;gt; &lt;/pre&gt;
 * 
 */
@XmlType(name = "FilterBy", namespace = "www.jalview.org/colours")
@XmlEnum
public enum FilterBy
{

  @XmlEnumValue("byLabel")
  BY_LABEL("byLabel"), @XmlEnumValue("byScore")
  BY_SCORE("byScore"), @XmlEnumValue("byAttribute")
  BY_ATTRIBUTE("byAttribute");

  private final String value;

  FilterBy(String v)
  {
    value = v;
  }

  public String value()
  {
    return value;
  }

  public static FilterBy fromValue(String v)
  {
    for (FilterBy c : FilterBy.values())
    {
      if (c.value.equals(v))
      {
        return c;
      }
    }
    throw new IllegalArgumentException(v);
  }

}
