//
// This file was generated by the Eclipse Implementation of JAXB, v2.3.3 
// See https://eclipse-ee4j.github.io/jaxb-ri 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2021.08.30 at 11:05:22 AM BST 
//

package jalview.xml.binding.jalview;

import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlAttribute;
import javax.xml.bind.annotation.XmlElement;
import javax.xml.bind.annotation.XmlRootElement;
import javax.xml.bind.annotation.XmlType;

/**
 * 
 * Represent the jalview.datamodel.Mapping object - it also provides a way of
 * storing sequences that are mapped 'to' without adding them to the sequence
 * set (which will mean they are then added to the alignment too).
 * 
 * 
 * &lt;p&gt;Java class for anonymous complex type.
 * 
 * &lt;p&gt;The following schema fragment specifies the expected content
 * contained within this class.
 * 
 * &lt;pre&gt; &amp;lt;complexType&amp;gt; &amp;lt;complexContent&amp;gt;
 * &amp;lt;extension
 * base="{www.vamsas.ac.uk/jalview/version2}mapListType"&amp;gt;
 * &amp;lt;sequence&amp;gt; &amp;lt;choice minOccurs="0"&amp;gt; &amp;lt;element
 * ref="{www.vamsas.ac.uk/jalview/version2}Sequence"/&amp;gt; &amp;lt;element
 * name="dseqFor"&amp;gt; &amp;lt;simpleType&amp;gt; &amp;lt;restriction
 * base="{http://www.w3.org/2001/XMLSchema}string"&amp;gt;
 * &amp;lt;/restriction&amp;gt; &amp;lt;/simpleType&amp;gt;
 * &amp;lt;/element&amp;gt; &amp;lt;/choice&amp;gt; &amp;lt;/sequence&amp;gt;
 * &amp;lt;attribute name="mappingType"
 * type="{http://www.w3.org/2001/XMLSchema}string" /&amp;gt;
 * &amp;lt;/extension&amp;gt; &amp;lt;/complexContent&amp;gt;
 * &amp;lt;/complexType&amp;gt; &lt;/pre&gt;
 * 
 * 
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "", propOrder = { "sequence", "dseqFor" })
@XmlRootElement(name = "Mapping")
public class Mapping extends MapListType
{

  @XmlElement(name = "Sequence")
  protected Sequence sequence;

  protected String dseqFor;

  @XmlAttribute(name = "mappingType")
  protected String mappingType;

  /**
   * Gets the value of the sequence property.
   * 
   * @return possible object is {@link Sequence }
   * 
   */
  public Sequence getSequence()
  {
    return sequence;
  }

  /**
   * Sets the value of the sequence property.
   * 
   * @param value
   *          allowed object is {@link Sequence }
   * 
   */
  public void setSequence(Sequence value)
  {
    this.sequence = value;
  }

  /**
   * Gets the value of the dseqFor property.
   * 
   * @return possible object is {@link String }
   * 
   */
  public String getDseqFor()
  {
    return dseqFor;
  }

  /**
   * Sets the value of the dseqFor property.
   * 
   * @param value
   *          allowed object is {@link String }
   * 
   */
  public void setDseqFor(String value)
  {
    this.dseqFor = value;
  }

  /**
   * Gets the value of the mappingType property.
   * 
   * @return possible object is {@link String }
   * 
   */
  public String getMappingType()
  {
    return mappingType;
  }

  /**
   * Sets the value of the mappingType property.
   * 
   * @param value
   *          allowed object is {@link String }
   * 
   */
  public void setMappingType(String value)
  {
    this.mappingType = value;
  }

}
