//
// This file was generated by the Eclipse Implementation of JAXB, v2.3.3 
// See https://eclipse-ee4j.github.io/jaxb-ri 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2021.08.30 at 11:05:22 AM BST 
//

package jalview.xml.binding.jalview;

import javax.xml.bind.annotation.XmlEnum;
import javax.xml.bind.annotation.XmlEnumValue;
import javax.xml.bind.annotation.XmlType;

/**
 * &lt;p&gt;Java class for NoValueColour.
 * 
 * &lt;p&gt;The following schema fragment specifies the expected content
 * contained within this class. &lt;pre&gt; &amp;lt;simpleType
 * name="NoValueColour"&amp;gt; &amp;lt;restriction
 * base="{http://www.w3.org/2001/XMLSchema}string"&amp;gt; &amp;lt;enumeration
 * value="None"/&amp;gt; &amp;lt;enumeration value="Min"/&amp;gt;
 * &amp;lt;enumeration value="Max"/&amp;gt; &amp;lt;/restriction&amp;gt;
 * &amp;lt;/simpleType&amp;gt; &lt;/pre&gt;
 * 
 */
@XmlType(name = "NoValueColour", namespace = "www.jalview.org/colours")
@XmlEnum
public enum NoValueColour
{

  @XmlEnumValue("None")
  NONE("None"), @XmlEnumValue("Min")
  MIN("Min"), @XmlEnumValue("Max")
  MAX("Max");

  private final String value;

  NoValueColour(String v)
  {
    value = v;
  }

  public String value()
  {
    return value;
  }

  public static NoValueColour fromValue(String v)
  {
    for (NoValueColour c : NoValueColour.values())
    {
      if (c.value.equals(v))
      {
        return c;
      }
    }
    throw new IllegalArgumentException(v);
  }

}
