//
// This file was generated by the Eclipse Implementation of JAXB, v2.3.3 
// See https://eclipse-ee4j.github.io/jaxb-ri 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2021.08.30 at 11:05:22 AM BST 
//

package jalview.xml.binding.jalview;

import javax.xml.bind.JAXBElement;
import javax.xml.bind.annotation.XmlElementDecl;
import javax.xml.bind.annotation.XmlRegistry;
import javax.xml.namespace.QName;

/**
 * This object contains factory methods for each Java content interface and Java
 * element interface generated in the jalview.xml.binding.jalview package.
 * &lt;p&gt;An ObjectFactory allows you to programatically construct new
 * instances of the Java representation for XML content. The Java representation
 * of XML content can consist of schema derived interfaces and classes
 * representing the binding of schema type definitions, element declarations and
 * model groups. Factory methods for each of these are provided in this class.
 * 
 */
@XmlRegistry
public class ObjectFactory
{

  private final static QName _JalviewModel_QNAME = new QName(
          "www.jalview.org", "JalviewModel");

  private final static QName _JalviewUserColours_QNAME = new QName(
          "www.jalview.org/colours", "JalviewUserColours");

  private final static QName _WebServiceParameterSet_QNAME = new QName(
          "www.jalview.org/xml/wsparamset", "WebServiceParameterSet");

  /**
   * Create a new ObjectFactory that can be used to create new instances of
   * schema derived classes for package: jalview.xml.binding.jalview
   * 
   */
  public ObjectFactory()
  {
  }

  /**
   * Create an instance of {@link MapListType }
   * 
   */
  public MapListType createMapListType()
  {
    return new MapListType();
  }

  /**
   * Create an instance of {@link Sequence }
   * 
   */
  public Sequence createSequence()
  {
    return new Sequence();
  }

  /**
   * Create an instance of {@link AlcodonFrame }
   * 
   */
  public AlcodonFrame createAlcodonFrame()
  {
    return new AlcodonFrame();
  }

  /**
   * Create an instance of {@link Annotation }
   * 
   */
  public Annotation createAnnotation()
  {
    return new Annotation();
  }

  /**
   * Create an instance of {@link SequenceSet }
   * 
   */
  public SequenceSet createSequenceSet()
  {
    return new SequenceSet();
  }

  /**
   * Create an instance of {@link FeatureMatcherSet }
   * 
   */
  public FeatureMatcherSet createFeatureMatcherSet()
  {
    return new FeatureMatcherSet();
  }

  /**
   * Create an instance of {@link JalviewUserColours }
   * 
   */
  public JalviewUserColours createJalviewUserColours()
  {
    return new JalviewUserColours();
  }

  /**
   * Create an instance of {@link Pdbentry }
   * 
   */
  public Pdbentry createPdbentry()
  {
    return new Pdbentry();
  }

  /**
   * Create an instance of {@link Feature }
   * 
   */
  public Feature createFeature()
  {
    return new Feature();
  }

  /**
   * Create an instance of {@link JalviewModel }
   * 
   */
  public JalviewModel createJalviewModel()
  {
    return new JalviewModel();
  }

  /**
   * Create an instance of {@link JalviewModel.FeatureSettings }
   * 
   */
  public JalviewModel.FeatureSettings createJalviewModelFeatureSettings()
  {
    return new JalviewModel.FeatureSettings();
  }

  /**
   * Create an instance of {@link JalviewModel.PcaViewer }
   * 
   */
  public JalviewModel.PcaViewer createJalviewModelPcaViewer()
  {
    return new JalviewModel.PcaViewer();
  }

  /**
   * Create an instance of {@link JalviewModel.Viewport }
   * 
   */
  public JalviewModel.Viewport createJalviewModelViewport()
  {
    return new JalviewModel.Viewport();
  }

  /**
   * Create an instance of {@link JalviewModel.JSeq }
   * 
   */
  public JalviewModel.JSeq createJalviewModelJSeq()
  {
    return new JalviewModel.JSeq();
  }

  /**
   * Create an instance of {@link JalviewModel.JSeq.RnaViewer }
   * 
   */
  public JalviewModel.JSeq.RnaViewer createJalviewModelJSeqRnaViewer()
  {
    return new JalviewModel.JSeq.RnaViewer();
  }

  /**
   * Create an instance of {@link JalviewModel.JSeq.Pdbids }
   * 
   */
  public JalviewModel.JSeq.Pdbids createJalviewModelJSeqPdbids()
  {
    return new JalviewModel.JSeq.Pdbids();
  }

  /**
   * Create an instance of {@link AnnotationColourScheme }
   * 
   */
  public AnnotationColourScheme createAnnotationColourScheme()
  {
    return new AnnotationColourScheme();
  }

  /**
   * Create an instance of {@link PcaDataType }
   * 
   */
  public PcaDataType createPcaDataType()
  {
    return new PcaDataType();
  }

  /**
   * Create an instance of {@link DoubleVector }
   * 
   */
  public DoubleVector createDoubleVector()
  {
    return new DoubleVector();
  }

  /**
   * Create an instance of {@link DoubleMatrix }
   * 
   */
  public DoubleMatrix createDoubleMatrix()
  {
    return new DoubleMatrix();
  }

  /**
   * Create an instance of {@link Mapping }
   * 
   */
  public Mapping createMapping()
  {
    return new Mapping();
  }

  /**
   * Create an instance of {@link MapListType.MapListFrom }
   * 
   */
  public MapListType.MapListFrom createMapListTypeMapListFrom()
  {
    return new MapListType.MapListFrom();
  }

  /**
   * Create an instance of {@link MapListType.MapListTo }
   * 
   */
  public MapListType.MapListTo createMapListTypeMapListTo()
  {
    return new MapListType.MapListTo();
  }

  /**
   * Create an instance of {@link SequenceType }
   * 
   */
  public SequenceType createSequenceType()
  {
    return new SequenceType();
  }

  /**
   * Create an instance of {@link Sequence.DBRef }
   * 
   */
  public Sequence.DBRef createSequenceDBRef()
  {
    return new Sequence.DBRef();
  }

  /**
   * Create an instance of {@link AlcodonFrame.Alcodon }
   * 
   */
  public AlcodonFrame.Alcodon createAlcodonFrameAlcodon()
  {
    return new AlcodonFrame.Alcodon();
  }

  /**
   * Create an instance of {@link AlcodonFrame.AlcodMap }
   * 
   */
  public AlcodonFrame.AlcodMap createAlcodonFrameAlcodMap()
  {
    return new AlcodonFrame.AlcodMap();
  }

  /**
   * Create an instance of {@link AnnotationElement }
   * 
   */
  public AnnotationElement createAnnotationElement()
  {
    return new AnnotationElement();
  }

  /**
   * Create an instance of {@link Annotation.ThresholdLine }
   * 
   */
  public Annotation.ThresholdLine createAnnotationThresholdLine()
  {
    return new Annotation.ThresholdLine();
  }

  /**
   * Create an instance of {@link Annotation.Property }
   * 
   */
  public Annotation.Property createAnnotationProperty()
  {
    return new Annotation.Property();
  }

  /**
   * Create an instance of {@link SequenceSet.SequenceSetProperties }
   * 
   */
  public SequenceSet.SequenceSetProperties createSequenceSetSequenceSetProperties()
  {
    return new SequenceSet.SequenceSetProperties();
  }

  /**
   * Create an instance of {@link VAMSAS }
   * 
   */
  public VAMSAS createVAMSAS()
  {
    return new VAMSAS();
  }

  /**
   * Create an instance of {@link FeatureMatcher }
   * 
   */
  public FeatureMatcher createFeatureMatcher()
  {
    return new FeatureMatcher();
  }

  /**
   * Create an instance of {@link WebServiceParameterSet }
   * 
   */
  public WebServiceParameterSet createWebServiceParameterSet()
  {
    return new WebServiceParameterSet();
  }

  /**
   * Create an instance of {@link FeatureMatcherSet.CompoundMatcher }
   * 
   */
  public FeatureMatcherSet.CompoundMatcher createFeatureMatcherSetCompoundMatcher()
  {
    return new FeatureMatcherSet.CompoundMatcher();
  }

  /**
   * Create an instance of {@link JalviewUserColours.Colour }
   * 
   */
  public JalviewUserColours.Colour createJalviewUserColoursColour()
  {
    return new JalviewUserColours.Colour();
  }

  /**
   * Create an instance of {@link JalviewUserColours.Filter }
   * 
   */
  public JalviewUserColours.Filter createJalviewUserColoursFilter()
  {
    return new JalviewUserColours.Filter();
  }

  /**
   * Create an instance of {@link Pdbentry.Property }
   * 
   */
  public Pdbentry.Property createPdbentryProperty()
  {
    return new Pdbentry.Property();
  }

  /**
   * Create an instance of {@link Feature.OtherData }
   * 
   */
  public Feature.OtherData createFeatureOtherData()
  {
    return new Feature.OtherData();
  }

  /**
   * Create an instance of {@link JalviewModel.JGroup }
   * 
   */
  public JalviewModel.JGroup createJalviewModelJGroup()
  {
    return new JalviewModel.JGroup();
  }

  /**
   * Create an instance of {@link JalviewModel.UserColours }
   * 
   */
  public JalviewModel.UserColours createJalviewModelUserColours()
  {
    return new JalviewModel.UserColours();
  }

  /**
   * Create an instance of {@link JalviewModel.Tree }
   * 
   */
  public JalviewModel.Tree createJalviewModelTree()
  {
    return new JalviewModel.Tree();
  }

  /**
   * Create an instance of {@link JalviewModel.FeatureSettings.Setting }
   * 
   */
  public JalviewModel.FeatureSettings.Setting createJalviewModelFeatureSettingsSetting()
  {
    return new JalviewModel.FeatureSettings.Setting();
  }

  /**
   * Create an instance of {@link JalviewModel.FeatureSettings.Group }
   * 
   */
  public JalviewModel.FeatureSettings.Group createJalviewModelFeatureSettingsGroup()
  {
    return new JalviewModel.FeatureSettings.Group();
  }

  /**
   * Create an instance of {@link JalviewModel.PcaViewer.SequencePoint }
   * 
   */
  public JalviewModel.PcaViewer.SequencePoint createJalviewModelPcaViewerSequencePoint()
  {
    return new JalviewModel.PcaViewer.SequencePoint();
  }

  /**
   * Create an instance of {@link JalviewModel.PcaViewer.Axis }
   * 
   */
  public JalviewModel.PcaViewer.Axis createJalviewModelPcaViewerAxis()
  {
    return new JalviewModel.PcaViewer.Axis();
  }

  /**
   * Create an instance of {@link JalviewModel.PcaViewer.SeqPointMin }
   * 
   */
  public JalviewModel.PcaViewer.SeqPointMin createJalviewModelPcaViewerSeqPointMin()
  {
    return new JalviewModel.PcaViewer.SeqPointMin();
  }

  /**
   * Create an instance of {@link JalviewModel.PcaViewer.SeqPointMax }
   * 
   */
  public JalviewModel.PcaViewer.SeqPointMax createJalviewModelPcaViewerSeqPointMax()
  {
    return new JalviewModel.PcaViewer.SeqPointMax();
  }

  /**
   * Create an instance of {@link JalviewModel.Viewport.HiddenColumns }
   * 
   */
  public JalviewModel.Viewport.HiddenColumns createJalviewModelViewportHiddenColumns()
  {
    return new JalviewModel.Viewport.HiddenColumns();
  }

  /**
   * Create an instance of {@link JalviewModel.Viewport.CalcIdParam }
   * 
   */
  public JalviewModel.Viewport.CalcIdParam createJalviewModelViewportCalcIdParam()
  {
    return new JalviewModel.Viewport.CalcIdParam();
  }

  /**
   * Create an instance of
   * {@link JalviewModel.JSeq.RnaViewer.SecondaryStructure }
   * 
   */
  public JalviewModel.JSeq.RnaViewer.SecondaryStructure createJalviewModelJSeqRnaViewerSecondaryStructure()
  {
    return new JalviewModel.JSeq.RnaViewer.SecondaryStructure();
  }

  /**
   * Create an instance of {@link JalviewModel.JSeq.Pdbids.StructureState }
   * 
   */
  public JalviewModel.JSeq.Pdbids.StructureState createJalviewModelJSeqPdbidsStructureState()
  {
    return new JalviewModel.JSeq.Pdbids.StructureState();
  }

  /**
   * Create an instance of {@link JAXBElement }{@code <}{@link JalviewModel
   * }{@code >}
   * 
   * @param value
   *          Java instance representing xml element's value.
   * @return the new instance of {@link JAXBElement
   *         }{@code <}{@link JalviewModel }{@code >}
   */
  @XmlElementDecl(namespace = "www.jalview.org", name = "JalviewModel")
  public JAXBElement<JalviewModel> createJalviewModel(JalviewModel value)
  {
    return new JAXBElement<JalviewModel>(_JalviewModel_QNAME,
            JalviewModel.class, null, value);
  }

  /**
   * Create an instance of {@link JAXBElement
   * }{@code <}{@link JalviewUserColours }{@code >}
   * 
   * @param value
   *          Java instance representing xml element's value.
   * @return the new instance of {@link JAXBElement
   *         }{@code <}{@link JalviewUserColours }{@code >}
   */
  @XmlElementDecl(
    namespace = "www.jalview.org/colours",
    name = "JalviewUserColours")
  public JAXBElement<JalviewUserColours> createJalviewUserColours(
          JalviewUserColours value)
  {
    return new JAXBElement<JalviewUserColours>(_JalviewUserColours_QNAME,
            JalviewUserColours.class, null, value);
  }

  /**
   * Create an instance of {@link JAXBElement
   * }{@code <}{@link WebServiceParameterSet }{@code >}
   * 
   * @param value
   *          Java instance representing xml element's value.
   * @return the new instance of {@link JAXBElement
   *         }{@code <}{@link WebServiceParameterSet }{@code >}
   */
  @XmlElementDecl(
    namespace = "www.jalview.org/xml/wsparamset",
    name = "WebServiceParameterSet")
  public JAXBElement<WebServiceParameterSet> createWebServiceParameterSet(
          WebServiceParameterSet value)
  {
    return new JAXBElement<WebServiceParameterSet>(
            _WebServiceParameterSet_QNAME, WebServiceParameterSet.class,
            null, value);
  }

}
