//
// This file was generated by the Eclipse Implementation of JAXB, v2.3.3 
// See https://eclipse-ee4j.github.io/jaxb-ri 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2021.08.30 at 11:05:22 AM BST 
//

@javax.xml.bind.annotation.XmlSchema(
  namespace = "www.vamsas.ac.uk/jalview/version2",
  elementFormDefault = javax.xml.bind.annotation.XmlNsForm.QUALIFIED)
package jalview.xml.binding.jalview;
