//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.2.8-b130911.1802 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2015.10.09 at 03:18:33 PM BST 
//

package jalview.xml.binding.sifts;

import javax.xml.bind.annotation.XmlEnum;
import javax.xml.bind.annotation.XmlEnumValue;
import javax.xml.bind.annotation.XmlType;

/**
 * <p>
 * Java class for entityType.
 * 
 * <p>
 * The following schema fragment specifies the expected content contained within
 * this class.
 * <p>
 * 
 * <pre>
 * &lt;simpleType name="entityType">
 *   &lt;restriction base="{http://www.w3.org/2001/XMLSchema}string">
 *     &lt;enumeration value="protein"/>
 *     &lt;enumeration value="RNA"/>
 *     &lt;enumeration value="DNA"/>
 *     &lt;enumeration value="domain"/>
 *   &lt;/restriction>
 * &lt;/simpleType>
 * </pre>
 * 
 */
@XmlType(
  name = "entityType",
  namespace = "http://www.ebi.ac.uk/pdbe/docs/sifts/dataTypes.xsd")
@XmlEnum
public enum EntityType
{

  @XmlEnumValue("protein")
  PROTEIN("protein"), RNA("RNA"), DNA("DNA"), @XmlEnumValue("domain")
  DOMAIN("domain");

  private final String value;

  EntityType(String v)
  {
    value = v;
  }

  public String value()
  {
    return value;
  }

  public static EntityType fromValue(String v)
  {
    for (EntityType c : EntityType.values())
    {
      if (c.value.equals(v))
      {
        return c;
      }
    }
    throw new IllegalArgumentException(v);
  }

}
