//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.2.8-b130911.1802 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2015.10.09 at 03:18:33 PM BST 
//

package jalview.xml.binding.sifts;

import java.util.ArrayList;
import java.util.List;
import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlAttribute;
import javax.xml.bind.annotation.XmlElement;
import javax.xml.bind.annotation.XmlRootElement;
import javax.xml.bind.annotation.XmlSchemaType;
import javax.xml.bind.annotation.XmlType;
import javax.xml.bind.annotation.XmlValue;
import javax.xml.datatype.XMLGregorianCalendar;

/**
 * <p>
 * Java class for anonymous complex type.
 * 
 * <p>
 * The following schema fragment specifies the expected content contained within
 * this class.
 * 
 * <pre>
 * &lt;complexType>
 *   &lt;complexContent>
 *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *       &lt;sequence>
 *         &lt;element name="listDB">
 *           &lt;complexType>
 *             &lt;complexContent>
 *               &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *                 &lt;sequence maxOccurs="unbounded">
 *                   &lt;element name="db">
 *                     &lt;complexType>
 *                       &lt;complexContent>
 *                         &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *                           &lt;attGroup ref="{http://www.ebi.ac.uk/pdbe/docs/sifts/dataTypes.xsd}listdbRef"/>
 *                         &lt;/restriction>
 *                       &lt;/complexContent>
 *                     &lt;/complexType>
 *                   &lt;/element>
 *                 &lt;/sequence>
 *               &lt;/restriction>
 *             &lt;/complexContent>
 *           &lt;/complexType>
 *         &lt;/element>
 *         &lt;element name="entryDetail" maxOccurs="unbounded" minOccurs="0">
 *           &lt;complexType>
 *             &lt;complexContent>
 *               &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *                 &lt;attGroup ref="{http://www.ebi.ac.uk/pdbe/docs/sifts/dataTypes.xsd}detail"/>
 *               &lt;/restriction>
 *             &lt;/complexContent>
 *           &lt;/complexType>
 *         &lt;/element>
 *         &lt;element name="entity" maxOccurs="unbounded">
 *           &lt;complexType>
 *             &lt;complexContent>
 *               &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *                 &lt;sequence>
 *                   &lt;element name="entityDetail" maxOccurs="unbounded" minOccurs="0">
 *                     &lt;complexType>
 *                       &lt;complexContent>
 *                         &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *                           &lt;attGroup ref="{http://www.ebi.ac.uk/pdbe/docs/sifts/dataTypes.xsd}detail"/>
 *                         &lt;/restriction>
 *                       &lt;/complexContent>
 *                     &lt;/complexType>
 *                   &lt;/element>
 *                   &lt;element name="segment" maxOccurs="unbounded">
 *                     &lt;complexType>
 *                       &lt;complexContent>
 *                         &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *                           &lt;sequence>
 *                             &lt;element name="listResidue" minOccurs="0">
 *                               &lt;complexType>
 *                                 &lt;complexContent>
 *                                   &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *                                     &lt;sequence>
 *                                       &lt;element name="residue" maxOccurs="unbounded">
 *                                         &lt;complexType>
 *                                           &lt;complexContent>
 *                                             &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *                                               &lt;sequence>
 *                                                 &lt;element name="crossRefDb" maxOccurs="unbounded" minOccurs="0">
 *                                                   &lt;complexType>
 *                                                     &lt;complexContent>
 *                                                       &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *                                                         &lt;attGroup ref="{http://www.ebi.ac.uk/pdbe/docs/sifts/dataTypes.xsd}dbRef"/>
 *                                                         &lt;attGroup ref="{http://www.ebi.ac.uk/pdbe/docs/sifts/dataTypes.xsd}resRef"/>
 *                                                         &lt;attribute name="dbChainId" type="{http://www.ebi.ac.uk/pdbe/docs/sifts/dataTypes.xsd}chainId" />
 *                                                       &lt;/restriction>
 *                                                     &lt;/complexContent>
 *                                                   &lt;/complexType>
 *                                                 &lt;/element>
 *                                                 &lt;element name="residueDetail" maxOccurs="unbounded" minOccurs="0">
 *                                                   &lt;complexType>
 *                                                     &lt;complexContent>
 *                                                       &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *                                                         &lt;attGroup ref="{http://www.ebi.ac.uk/pdbe/docs/sifts/dataTypes.xsd}detail"/>
 *                                                       &lt;/restriction>
 *                                                     &lt;/complexContent>
 *                                                   &lt;/complexType>
 *                                                 &lt;/element>
 *                                               &lt;/sequence>
 *                                               &lt;attGroup ref="{http://www.ebi.ac.uk/pdbe/docs/sifts/dataTypes.xsd}resRef"/>
 *                                               &lt;attGroup ref="{http://www.ebi.ac.uk/pdbe/docs/sifts/dataTypes.xsd}listdbRef"/>
 *                                             &lt;/restriction>
 *                                           &lt;/complexContent>
 *                                         &lt;/complexType>
 *                                       &lt;/element>
 *                                     &lt;/sequence>
 *                                   &lt;/restriction>
 *                                 &lt;/complexContent>
 *                               &lt;/complexType>
 *                             &lt;/element>
 *                             &lt;element name="listMapRegion" minOccurs="0">
 *                               &lt;complexType>
 *                                 &lt;complexContent>
 *                                   &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *                                     &lt;sequence>
 *                                       &lt;element name="mapRegion" maxOccurs="unbounded">
 *                                         &lt;complexType>
 *                                           &lt;complexContent>
 *                                             &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *                                               &lt;sequence>
 *                                                 &lt;element name="db">
 *                                                   &lt;complexType>
 *                                                     &lt;complexContent>
 *                                                       &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *                                                         &lt;sequence>
 *                                                           &lt;element name="dbDetail" maxOccurs="unbounded" minOccurs="0">
 *                                                             &lt;complexType>
 *                                                               &lt;complexContent>
 *                                                                 &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *                                                                   &lt;attGroup ref="{http://www.ebi.ac.uk/pdbe/docs/sifts/dataTypes.xsd}detail"/>
 *                                                                 &lt;/restriction>
 *                                                               &lt;/complexContent>
 *                                                             &lt;/complexType>
 *                                                           &lt;/element>
 *                                                         &lt;/sequence>
 *                                                         &lt;attGroup ref="{http://www.ebi.ac.uk/pdbe/docs/sifts/dataTypes.xsd}dbRef"/>
 *                                                         &lt;attGroup ref="{http://www.ebi.ac.uk/pdbe/docs/sifts/dataTypes.xsd}region"/>
 *                                                         &lt;attribute name="dbChainId" type="{http://www.ebi.ac.uk/pdbe/docs/sifts/dataTypes.xsd}dbChainId" />
 *                                                       &lt;/restriction>
 *                                                     &lt;/complexContent>
 *                                                   &lt;/complexType>
 *                                                 &lt;/element>
 *                                               &lt;/sequence>
 *                                               &lt;attGroup ref="{http://www.ebi.ac.uk/pdbe/docs/sifts/dataTypes.xsd}region"/>
 *                                             &lt;/restriction>
 *                                           &lt;/complexContent>
 *                                         &lt;/complexType>
 *                                       &lt;/element>
 *                                     &lt;/sequence>
 *                                   &lt;/restriction>
 *                                 &lt;/complexContent>
 *                               &lt;/complexType>
 *                             &lt;/element>
 *                             &lt;element name="segmentDetail" maxOccurs="unbounded" minOccurs="0">
 *                               &lt;complexType>
 *                                 &lt;complexContent>
 *                                   &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *                                     &lt;attGroup ref="{http://www.ebi.ac.uk/pdbe/docs/sifts/dataTypes.xsd}detail"/>
 *                                   &lt;/restriction>
 *                                 &lt;/complexContent>
 *                               &lt;/complexType>
 *                             &lt;/element>
 *                           &lt;/sequence>
 *                           &lt;attGroup ref="{http://www.ebi.ac.uk/pdbe/docs/sifts/dataTypes.xsd}region"/>
 *                           &lt;attribute name="segId" use="required" type="{http://www.w3.org/2001/XMLSchema}string" />
 *                         &lt;/restriction>
 *                       &lt;/complexContent>
 *                     &lt;/complexType>
 *                   &lt;/element>
 *                 &lt;/sequence>
 *                 &lt;attribute name="type" use="required" type="{http://www.ebi.ac.uk/pdbe/docs/sifts/dataTypes.xsd}entityType" />
 *                 &lt;attribute name="entityId" use="required" type="{http://www.w3.org/2001/XMLSchema}string" />
 *               &lt;/restriction>
 *             &lt;/complexContent>
 *           &lt;/complexType>
 *         &lt;/element>
 *         &lt;element ref="{http://www.ebi.ac.uk/pdbe/docs/sifts/eFamily.xsd}alignment" maxOccurs="unbounded" minOccurs="0"/>
 *       &lt;/sequence>
 *       &lt;attGroup ref="{http://www.ebi.ac.uk/pdbe/docs/sifts/dataTypes.xsd}dbRef"/>
 *       &lt;attribute name="date" use="required" type="{http://www.w3.org/2001/XMLSchema}date" />
 *       &lt;attribute name="dbEntryVersion" use="required" type="{http://www.w3.org/2001/XMLSchema}date" />
 *     &lt;/restriction>
 *   &lt;/complexContent>
 * &lt;/complexType>
 * </pre>
 * 
 * 
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(
  name = "",
  propOrder =
  { "listDB", "entryDetail", "entity", "alignment" })
@XmlRootElement(name = "entry")
public class Entry
{

  @XmlElement(required = true)
  protected Entry.ListDB listDB;

  protected List<Entry.EntryDetail> entryDetail;

  @XmlElement(required = true)
  protected List<Entry.Entity> entity;

  protected List<Alignment> alignment;

  @XmlAttribute(name = "date", required = true)
  @XmlSchemaType(name = "date")
  protected XMLGregorianCalendar date;

  @XmlAttribute(name = "dbEntryVersion", required = true)
  @XmlSchemaType(name = "date")
  protected XMLGregorianCalendar dbEntryVersion;

  @XmlAttribute(name = "dbSource", required = true)
  protected String dbSource;

  @XmlAttribute(name = "dbCoordSys", required = true)
  protected String dbCoordSys;

  @XmlAttribute(name = "dbAccessionId", required = true)
  protected String dbAccessionId;

  @XmlAttribute(name = "dbEvidence")
  protected String dbEvidence;

  @XmlAttribute(name = "dbVersion")
  protected String dbVersion;

  /**
   * Gets the value of the listDB property.
   * 
   * @return possible object is {@link Entry.ListDB }
   * 
   */
  public Entry.ListDB getListDB()
  {
    return listDB;
  }

  /**
   * Sets the value of the listDB property.
   * 
   * @param value
   *          allowed object is {@link Entry.ListDB }
   * 
   */
  public void setListDB(Entry.ListDB value)
  {
    this.listDB = value;
  }

  /**
   * Gets the value of the entryDetail property.
   * 
   * <p>
   * This accessor method returns a reference to the live list, not a snapshot.
   * Therefore any modification you make to the returned list will be present
   * inside the JAXB object. This is why there is not a <CODE>set</CODE> method
   * for the entryDetail property.
   * 
   * <p>
   * For example, to add a new item, do as follows:
   * 
   * <pre>
   * getEntryDetail().add(newItem);
   * </pre>
   * 
   * 
   * <p>
   * Objects of the following type(s) are allowed in the list
   * {@link Entry.EntryDetail }
   * 
   * 
   */
  public List<Entry.EntryDetail> getEntryDetail()
  {
    if (entryDetail == null)
    {
      entryDetail = new ArrayList<Entry.EntryDetail>();
    }
    return this.entryDetail;
  }

  /**
   * Gets the value of the entity property.
   * 
   * <p>
   * This accessor method returns a reference to the live list, not a snapshot.
   * Therefore any modification you make to the returned list will be present
   * inside the JAXB object. This is why there is not a <CODE>set</CODE> method
   * for the entity property.
   * 
   * <p>
   * For example, to add a new item, do as follows:
   * 
   * <pre>
   * getEntity().add(newItem);
   * </pre>
   * 
   * 
   * <p>
   * Objects of the following type(s) are allowed in the list
   * {@link Entry.Entity }
   * 
   * 
   */
  public List<Entry.Entity> getEntity()
  {
    if (entity == null)
    {
      entity = new ArrayList<Entry.Entity>();
    }
    return this.entity;
  }

  /**
   * Gets the value of the alignment property.
   * 
   * <p>
   * This accessor method returns a reference to the live list, not a snapshot.
   * Therefore any modification you make to the returned list will be present
   * inside the JAXB object. This is why there is not a <CODE>set</CODE> method
   * for the alignment property.
   * 
   * <p>
   * For example, to add a new item, do as follows:
   * 
   * <pre>
   * getAlignment().add(newItem);
   * </pre>
   * 
   * 
   * <p>
   * Objects of the following type(s) are allowed in the list {@link Alignment }
   * 
   * 
   */
  public List<Alignment> getAlignment()
  {
    if (alignment == null)
    {
      alignment = new ArrayList<Alignment>();
    }
    return this.alignment;
  }

  /**
   * Gets the value of the date property.
   * 
   * @return possible object is {@link XMLGregorianCalendar }
   * 
   */
  public XMLGregorianCalendar getDate()
  {
    return date;
  }

  /**
   * Sets the value of the date property.
   * 
   * @param value
   *          allowed object is {@link XMLGregorianCalendar }
   * 
   */
  public void setDate(XMLGregorianCalendar value)
  {
    this.date = value;
  }

  /**
   * Gets the value of the dbEntryVersion property.
   * 
   * @return possible object is {@link XMLGregorianCalendar }
   * 
   */
  public XMLGregorianCalendar getDbEntryVersion()
  {
    return dbEntryVersion;
  }

  /**
   * Sets the value of the dbEntryVersion property.
   * 
   * @param value
   *          allowed object is {@link XMLGregorianCalendar }
   * 
   */
  public void setDbEntryVersion(XMLGregorianCalendar value)
  {
    this.dbEntryVersion = value;
  }

  /**
   * Gets the value of the dbSource property.
   * 
   * @return possible object is {@link String }
   * 
   */
  public String getDbSource()
  {
    return dbSource;
  }

  /**
   * Sets the value of the dbSource property.
   * 
   * @param value
   *          allowed object is {@link String }
   * 
   */
  public void setDbSource(String value)
  {
    this.dbSource = value;
  }

  /**
   * Gets the value of the dbCoordSys property.
   * 
   * @return possible object is {@link String }
   * 
   */
  public String getDbCoordSys()
  {
    return dbCoordSys;
  }

  /**
   * Sets the value of the dbCoordSys property.
   * 
   * @param value
   *          allowed object is {@link String }
   * 
   */
  public void setDbCoordSys(String value)
  {
    this.dbCoordSys = value;
  }

  /**
   * Gets the value of the dbAccessionId property.
   * 
   * @return possible object is {@link String }
   * 
   */
  public String getDbAccessionId()
  {
    return dbAccessionId;
  }

  /**
   * Sets the value of the dbAccessionId property.
   * 
   * @param value
   *          allowed object is {@link String }
   * 
   */
  public void setDbAccessionId(String value)
  {
    this.dbAccessionId = value;
  }

  /**
   * Gets the value of the dbEvidence property.
   * 
   * @return possible object is {@link String }
   * 
   */
  public String getDbEvidence()
  {
    return dbEvidence;
  }

  /**
   * Sets the value of the dbEvidence property.
   * 
   * @param value
   *          allowed object is {@link String }
   * 
   */
  public void setDbEvidence(String value)
  {
    this.dbEvidence = value;
  }

  /**
   * Gets the value of the dbVersion property.
   * 
   * @return possible object is {@link String }
   * 
   */
  public String getDbVersion()
  {
    return dbVersion;
  }

  /**
   * Sets the value of the dbVersion property.
   * 
   * @param value
   *          allowed object is {@link String }
   * 
   */
  public void setDbVersion(String value)
  {
    this.dbVersion = value;
  }

  /**
   * <p>
   * Java class for anonymous complex type.
   * 
   * <p>
   * The following schema fragment specifies the expected content contained
   * within this class.
   * 
   * <pre>
   * &lt;complexType>
   *   &lt;complexContent>
   *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
   *       &lt;sequence>
   *         &lt;element name="entityDetail" maxOccurs="unbounded" minOccurs="0">
   *           &lt;complexType>
   *             &lt;complexContent>
   *               &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
   *                 &lt;attGroup ref="{http://www.ebi.ac.uk/pdbe/docs/sifts/dataTypes.xsd}detail"/>
   *               &lt;/restriction>
   *             &lt;/complexContent>
   *           &lt;/complexType>
   *         &lt;/element>
   *         &lt;element name="segment" maxOccurs="unbounded">
   *           &lt;complexType>
   *             &lt;complexContent>
   *               &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
   *                 &lt;sequence>
   *                   &lt;element name="listResidue" minOccurs="0">
   *                     &lt;complexType>
   *                       &lt;complexContent>
   *                         &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
   *                           &lt;sequence>
   *                             &lt;element name="residue" maxOccurs="unbounded">
   *                               &lt;complexType>
   *                                 &lt;complexContent>
   *                                   &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
   *                                     &lt;sequence>
   *                                       &lt;element name="crossRefDb" maxOccurs="unbounded" minOccurs="0">
   *                                         &lt;complexType>
   *                                           &lt;complexContent>
   *                                             &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
   *                                               &lt;attGroup ref="{http://www.ebi.ac.uk/pdbe/docs/sifts/dataTypes.xsd}dbRef"/>
   *                                               &lt;attGroup ref="{http://www.ebi.ac.uk/pdbe/docs/sifts/dataTypes.xsd}resRef"/>
   *                                               &lt;attribute name="dbChainId" type="{http://www.ebi.ac.uk/pdbe/docs/sifts/dataTypes.xsd}chainId" />
   *                                             &lt;/restriction>
   *                                           &lt;/complexContent>
   *                                         &lt;/complexType>
   *                                       &lt;/element>
   *                                       &lt;element name="residueDetail" maxOccurs="unbounded" minOccurs="0">
   *                                         &lt;complexType>
   *                                           &lt;complexContent>
   *                                             &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
   *                                               &lt;attGroup ref="{http://www.ebi.ac.uk/pdbe/docs/sifts/dataTypes.xsd}detail"/>
   *                                             &lt;/restriction>
   *                                           &lt;/complexContent>
   *                                         &lt;/complexType>
   *                                       &lt;/element>
   *                                     &lt;/sequence>
   *                                     &lt;attGroup ref="{http://www.ebi.ac.uk/pdbe/docs/sifts/dataTypes.xsd}resRef"/>
   *                                     &lt;attGroup ref="{http://www.ebi.ac.uk/pdbe/docs/sifts/dataTypes.xsd}listdbRef"/>
   *                                   &lt;/restriction>
   *                                 &lt;/complexContent>
   *                               &lt;/complexType>
   *                             &lt;/element>
   *                           &lt;/sequence>
   *                         &lt;/restriction>
   *                       &lt;/complexContent>
   *                     &lt;/complexType>
   *                   &lt;/element>
   *                   &lt;element name="listMapRegion" minOccurs="0">
   *                     &lt;complexType>
   *                       &lt;complexContent>
   *                         &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
   *                           &lt;sequence>
   *                             &lt;element name="mapRegion" maxOccurs="unbounded">
   *                               &lt;complexType>
   *                                 &lt;complexContent>
   *                                   &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
   *                                     &lt;sequence>
   *                                       &lt;element name="db">
   *                                         &lt;complexType>
   *                                           &lt;complexContent>
   *                                             &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
   *                                               &lt;sequence>
   *                                                 &lt;element name="dbDetail" maxOccurs="unbounded" minOccurs="0">
   *                                                   &lt;complexType>
   *                                                     &lt;complexContent>
   *                                                       &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
   *                                                         &lt;attGroup ref="{http://www.ebi.ac.uk/pdbe/docs/sifts/dataTypes.xsd}detail"/>
   *                                                       &lt;/restriction>
   *                                                     &lt;/complexContent>
   *                                                   &lt;/complexType>
   *                                                 &lt;/element>
   *                                               &lt;/sequence>
   *                                               &lt;attGroup ref="{http://www.ebi.ac.uk/pdbe/docs/sifts/dataTypes.xsd}dbRef"/>
   *                                               &lt;attGroup ref="{http://www.ebi.ac.uk/pdbe/docs/sifts/dataTypes.xsd}region"/>
   *                                               &lt;attribute name="dbChainId" type="{http://www.ebi.ac.uk/pdbe/docs/sifts/dataTypes.xsd}dbChainId" />
   *                                             &lt;/restriction>
   *                                           &lt;/complexContent>
   *                                         &lt;/complexType>
   *                                       &lt;/element>
   *                                     &lt;/sequence>
   *                                     &lt;attGroup ref="{http://www.ebi.ac.uk/pdbe/docs/sifts/dataTypes.xsd}region"/>
   *                                   &lt;/restriction>
   *                                 &lt;/complexContent>
   *                               &lt;/complexType>
   *                             &lt;/element>
   *                           &lt;/sequence>
   *                         &lt;/restriction>
   *                       &lt;/complexContent>
   *                     &lt;/complexType>
   *                   &lt;/element>
   *                   &lt;element name="segmentDetail" maxOccurs="unbounded" minOccurs="0">
   *                     &lt;complexType>
   *                       &lt;complexContent>
   *                         &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
   *                           &lt;attGroup ref="{http://www.ebi.ac.uk/pdbe/docs/sifts/dataTypes.xsd}detail"/>
   *                         &lt;/restriction>
   *                       &lt;/complexContent>
   *                     &lt;/complexType>
   *                   &lt;/element>
   *                 &lt;/sequence>
   *                 &lt;attGroup ref="{http://www.ebi.ac.uk/pdbe/docs/sifts/dataTypes.xsd}region"/>
   *                 &lt;attribute name="segId" use="required" type="{http://www.w3.org/2001/XMLSchema}string" />
   *               &lt;/restriction>
   *             &lt;/complexContent>
   *           &lt;/complexType>
   *         &lt;/element>
   *       &lt;/sequence>
   *       &lt;attribute name="type" use="required" type="{http://www.ebi.ac.uk/pdbe/docs/sifts/dataTypes.xsd}entityType" />
   *       &lt;attribute name="entityId" use="required" type="{http://www.w3.org/2001/XMLSchema}string" />
   *     &lt;/restriction>
   *   &lt;/complexContent>
   * &lt;/complexType>
   * </pre>
   * 
   * 
   */
  @XmlAccessorType(XmlAccessType.FIELD)
  @XmlType(name = "", propOrder = { "entityDetail", "segment" })
  public static class Entity
  {

    protected List<Entry.Entity.EntityDetail> entityDetail;

    @XmlElement(required = true)
    protected List<Entry.Entity.Segment> segment;

    @XmlAttribute(name = "type", required = true)
    protected EntityType type;

    @XmlAttribute(name = "entityId", required = true)
    protected String entityId;

    /**
     * Gets the value of the entityDetail property.
     * 
     * <p>
     * This accessor method returns a reference to the live list, not a
     * snapshot. Therefore any modification you make to the returned list will
     * be present inside the JAXB object. This is why there is not a
     * <CODE>set</CODE> method for the entityDetail property.
     * 
     * <p>
     * For example, to add a new item, do as follows:
     * 
     * <pre>
     * getEntityDetail().add(newItem);
     * </pre>
     * 
     * 
     * <p>
     * Objects of the following type(s) are allowed in the list
     * {@link Entry.Entity.EntityDetail }
     * 
     * 
     */
    public List<Entry.Entity.EntityDetail> getEntityDetail()
    {
      if (entityDetail == null)
      {
        entityDetail = new ArrayList<Entry.Entity.EntityDetail>();
      }
      return this.entityDetail;
    }

    /**
     * Gets the value of the segment property.
     * 
     * <p>
     * This accessor method returns a reference to the live list, not a
     * snapshot. Therefore any modification you make to the returned list will
     * be present inside the JAXB object. This is why there is not a
     * <CODE>set</CODE> method for the segment property.
     * 
     * <p>
     * For example, to add a new item, do as follows:
     * 
     * <pre>
     * getSegment().add(newItem);
     * </pre>
     * 
     * 
     * <p>
     * Objects of the following type(s) are allowed in the list
     * {@link Entry.Entity.Segment }
     * 
     * 
     */
    public List<Entry.Entity.Segment> getSegment()
    {
      if (segment == null)
      {
        segment = new ArrayList<Entry.Entity.Segment>();
      }
      return this.segment;
    }

    /**
     * Gets the value of the type property.
     * 
     * @return possible object is {@link EntityType }
     * 
     */
    public EntityType getType()
    {
      return type;
    }

    /**
     * Sets the value of the type property.
     * 
     * @param value
     *          allowed object is {@link EntityType }
     * 
     */
    public void setType(EntityType value)
    {
      this.type = value;
    }

    /**
     * Gets the value of the entityId property.
     * 
     * @return possible object is {@link String }
     * 
     */
    public String getEntityId()
    {
      return entityId;
    }

    /**
     * Sets the value of the entityId property.
     * 
     * @param value
     *          allowed object is {@link String }
     * 
     */
    public void setEntityId(String value)
    {
      this.entityId = value;
    }

    /**
     * <p>
     * Java class for anonymous complex type.
     * 
     * <p>
     * The following schema fragment specifies the expected content contained
     * within this class.
     * 
     * <pre>
     * &lt;complexType>
     *   &lt;complexContent>
     *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
     *       &lt;attGroup ref="{http://www.ebi.ac.uk/pdbe/docs/sifts/dataTypes.xsd}detail"/>
     *     &lt;/restriction>
     *   &lt;/complexContent>
     * &lt;/complexType>
     * </pre>
     * 
     * 
     */
    @XmlAccessorType(XmlAccessType.FIELD)
    @XmlType(name = "", propOrder = { "content" })
    public static class EntityDetail
    {

      @XmlValue
      protected String content;

      @XmlAttribute(name = "dbSource")
      protected String dbSource;

      @XmlAttribute(name = "property", required = true)
      protected String property;

      /**
       * Gets the value of the content property.
       * 
       * @return possible object is {@link String }
       * 
       */
      public String getContent()
      {
        return content;
      }

      /**
       * Sets the value of the content property.
       * 
       * @param value
       *          allowed object is {@link String }
       * 
       */
      public void setContent(String value)
      {
        this.content = value;
      }

      /**
       * Gets the value of the dbSource property.
       * 
       * @return possible object is {@link String }
       * 
       */
      public String getDbSource()
      {
        return dbSource;
      }

      /**
       * Sets the value of the dbSource property.
       * 
       * @param value
       *          allowed object is {@link String }
       * 
       */
      public void setDbSource(String value)
      {
        this.dbSource = value;
      }

      /**
       * Gets the value of the property property.
       * 
       * @return possible object is {@link String }
       * 
       */
      public String getProperty()
      {
        return property;
      }

      /**
       * Sets the value of the property property.
       * 
       * @param value
       *          allowed object is {@link String }
       * 
       */
      public void setProperty(String value)
      {
        this.property = value;
      }

    }

    /**
     * <p>
     * Java class for anonymous complex type.
     * 
     * <p>
     * The following schema fragment specifies the expected content contained
     * within this class.
     * 
     * <pre>
     * &lt;complexType>
     *   &lt;complexContent>
     *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
     *       &lt;sequence>
     *         &lt;element name="listResidue" minOccurs="0">
     *           &lt;complexType>
     *             &lt;complexContent>
     *               &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
     *                 &lt;sequence>
     *                   &lt;element name="residue" maxOccurs="unbounded">
     *                     &lt;complexType>
     *                       &lt;complexContent>
     *                         &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
     *                           &lt;sequence>
     *                             &lt;element name="crossRefDb" maxOccurs="unbounded" minOccurs="0">
     *                               &lt;complexType>
     *                                 &lt;complexContent>
     *                                   &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
     *                                     &lt;attGroup ref="{http://www.ebi.ac.uk/pdbe/docs/sifts/dataTypes.xsd}dbRef"/>
     *                                     &lt;attGroup ref="{http://www.ebi.ac.uk/pdbe/docs/sifts/dataTypes.xsd}resRef"/>
     *                                     &lt;attribute name="dbChainId" type="{http://www.ebi.ac.uk/pdbe/docs/sifts/dataTypes.xsd}chainId" />
     *                                   &lt;/restriction>
     *                                 &lt;/complexContent>
     *                               &lt;/complexType>
     *                             &lt;/element>
     *                             &lt;element name="residueDetail" maxOccurs="unbounded" minOccurs="0">
     *                               &lt;complexType>
     *                                 &lt;complexContent>
     *                                   &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
     *                                     &lt;attGroup ref="{http://www.ebi.ac.uk/pdbe/docs/sifts/dataTypes.xsd}detail"/>
     *                                   &lt;/restriction>
     *                                 &lt;/complexContent>
     *                               &lt;/complexType>
     *                             &lt;/element>
     *                           &lt;/sequence>
     *                           &lt;attGroup ref="{http://www.ebi.ac.uk/pdbe/docs/sifts/dataTypes.xsd}resRef"/>
     *                           &lt;attGroup ref="{http://www.ebi.ac.uk/pdbe/docs/sifts/dataTypes.xsd}listdbRef"/>
     *                         &lt;/restriction>
     *                       &lt;/complexContent>
     *                     &lt;/complexType>
     *                   &lt;/element>
     *                 &lt;/sequence>
     *               &lt;/restriction>
     *             &lt;/complexContent>
     *           &lt;/complexType>
     *         &lt;/element>
     *         &lt;element name="listMapRegion" minOccurs="0">
     *           &lt;complexType>
     *             &lt;complexContent>
     *               &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
     *                 &lt;sequence>
     *                   &lt;element name="mapRegion" maxOccurs="unbounded">
     *                     &lt;complexType>
     *                       &lt;complexContent>
     *                         &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
     *                           &lt;sequence>
     *                             &lt;element name="db">
     *                               &lt;complexType>
     *                                 &lt;complexContent>
     *                                   &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
     *                                     &lt;sequence>
     *                                       &lt;element name="dbDetail" maxOccurs="unbounded" minOccurs="0">
     *                                         &lt;complexType>
     *                                           &lt;complexContent>
     *                                             &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
     *                                               &lt;attGroup ref="{http://www.ebi.ac.uk/pdbe/docs/sifts/dataTypes.xsd}detail"/>
     *                                             &lt;/restriction>
     *                                           &lt;/complexContent>
     *                                         &lt;/complexType>
     *                                       &lt;/element>
     *                                     &lt;/sequence>
     *                                     &lt;attGroup ref="{http://www.ebi.ac.uk/pdbe/docs/sifts/dataTypes.xsd}dbRef"/>
     *                                     &lt;attGroup ref="{http://www.ebi.ac.uk/pdbe/docs/sifts/dataTypes.xsd}region"/>
     *                                     &lt;attribute name="dbChainId" type="{http://www.ebi.ac.uk/pdbe/docs/sifts/dataTypes.xsd}dbChainId" />
     *                                   &lt;/restriction>
     *                                 &lt;/complexContent>
     *                               &lt;/complexType>
     *                             &lt;/element>
     *                           &lt;/sequence>
     *                           &lt;attGroup ref="{http://www.ebi.ac.uk/pdbe/docs/sifts/dataTypes.xsd}region"/>
     *                         &lt;/restriction>
     *                       &lt;/complexContent>
     *                     &lt;/complexType>
     *                   &lt;/element>
     *                 &lt;/sequence>
     *               &lt;/restriction>
     *             &lt;/complexContent>
     *           &lt;/complexType>
     *         &lt;/element>
     *         &lt;element name="segmentDetail" maxOccurs="unbounded" minOccurs="0">
     *           &lt;complexType>
     *             &lt;complexContent>
     *               &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
     *                 &lt;attGroup ref="{http://www.ebi.ac.uk/pdbe/docs/sifts/dataTypes.xsd}detail"/>
     *               &lt;/restriction>
     *             &lt;/complexContent>
     *           &lt;/complexType>
     *         &lt;/element>
     *       &lt;/sequence>
     *       &lt;attGroup ref="{http://www.ebi.ac.uk/pdbe/docs/sifts/dataTypes.xsd}region"/>
     *       &lt;attribute name="segId" use="required" type="{http://www.w3.org/2001/XMLSchema}string" />
     *     &lt;/restriction>
     *   &lt;/complexContent>
     * &lt;/complexType>
     * </pre>
     * 
     * 
     */
    @XmlAccessorType(XmlAccessType.FIELD)
    @XmlType(
      name = "",
      propOrder =
      { "listResidue", "listMapRegion", "segmentDetail" })
    public static class Segment
    {

      protected Entry.Entity.Segment.ListResidue listResidue;

      protected Entry.Entity.Segment.ListMapRegion listMapRegion;

      protected List<Entry.Entity.Segment.SegmentDetail> segmentDetail;

      @XmlAttribute(name = "segId", required = true)
      protected String segId;

      @XmlAttribute(name = "start")
      protected String start;

      @XmlAttribute(name = "end")
      protected String end;

      /**
       * Gets the value of the listResidue property.
       * 
       * @return possible object is {@link Entry.Entity.Segment.ListResidue }
       * 
       */
      public Entry.Entity.Segment.ListResidue getListResidue()
      {
        return listResidue;
      }

      /**
       * Sets the value of the listResidue property.
       * 
       * @param value
       *          allowed object is {@link Entry.Entity.Segment.ListResidue }
       * 
       */
      public void setListResidue(Entry.Entity.Segment.ListResidue value)
      {
        this.listResidue = value;
      }

      /**
       * Gets the value of the listMapRegion property.
       * 
       * @return possible object is {@link Entry.Entity.Segment.ListMapRegion }
       * 
       */
      public Entry.Entity.Segment.ListMapRegion getListMapRegion()
      {
        return listMapRegion;
      }

      /**
       * Sets the value of the listMapRegion property.
       * 
       * @param value
       *          allowed object is {@link Entry.Entity.Segment.ListMapRegion }
       * 
       */
      public void setListMapRegion(Entry.Entity.Segment.ListMapRegion value)
      {
        this.listMapRegion = value;
      }

      /**
       * Gets the value of the segmentDetail property.
       * 
       * <p>
       * This accessor method returns a reference to the live list, not a
       * snapshot. Therefore any modification you make to the returned list will
       * be present inside the JAXB object. This is why there is not a
       * <CODE>set</CODE> method for the segmentDetail property.
       * 
       * <p>
       * For example, to add a new item, do as follows:
       * 
       * <pre>
       * getSegmentDetail().add(newItem);
       * </pre>
       * 
       * 
       * <p>
       * Objects of the following type(s) are allowed in the list
       * {@link Entry.Entity.Segment.SegmentDetail }
       * 
       * 
       */
      public List<Entry.Entity.Segment.SegmentDetail> getSegmentDetail()
      {
        if (segmentDetail == null)
        {
          segmentDetail = new ArrayList<Entry.Entity.Segment.SegmentDetail>();
        }
        return this.segmentDetail;
      }

      /**
       * Gets the value of the segId property.
       * 
       * @return possible object is {@link String }
       * 
       */
      public String getSegId()
      {
        return segId;
      }

      /**
       * Sets the value of the segId property.
       * 
       * @param value
       *          allowed object is {@link String }
       * 
       */
      public void setSegId(String value)
      {
        this.segId = value;
      }

      /**
       * Gets the value of the start property.
       * 
       * @return possible object is {@link String }
       * 
       */
      public String getStart()
      {
        return start;
      }

      /**
       * Sets the value of the start property.
       * 
       * @param value
       *          allowed object is {@link String }
       * 
       */
      public void setStart(String value)
      {
        this.start = value;
      }

      /**
       * Gets the value of the end property.
       * 
       * @return possible object is {@link String }
       * 
       */
      public String getEnd()
      {
        return end;
      }

      /**
       * Sets the value of the end property.
       * 
       * @param value
       *          allowed object is {@link String }
       * 
       */
      public void setEnd(String value)
      {
        this.end = value;
      }

      /**
       * <p>
       * Java class for anonymous complex type.
       * 
       * <p>
       * The following schema fragment specifies the expected content contained
       * within this class.
       * 
       * <pre>
       * &lt;complexType>
       *   &lt;complexContent>
       *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
       *       &lt;sequence>
       *         &lt;element name="mapRegion" maxOccurs="unbounded">
       *           &lt;complexType>
       *             &lt;complexContent>
       *               &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
       *                 &lt;sequence>
       *                   &lt;element name="db">
       *                     &lt;complexType>
       *                       &lt;complexContent>
       *                         &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
       *                           &lt;sequence>
       *                             &lt;element name="dbDetail" maxOccurs="unbounded" minOccurs="0">
       *                               &lt;complexType>
       *                                 &lt;complexContent>
       *                                   &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
       *                                     &lt;attGroup ref="{http://www.ebi.ac.uk/pdbe/docs/sifts/dataTypes.xsd}detail"/>
       *                                   &lt;/restriction>
       *                                 &lt;/complexContent>
       *                               &lt;/complexType>
       *                             &lt;/element>
       *                           &lt;/sequence>
       *                           &lt;attGroup ref="{http://www.ebi.ac.uk/pdbe/docs/sifts/dataTypes.xsd}dbRef"/>
       *                           &lt;attGroup ref="{http://www.ebi.ac.uk/pdbe/docs/sifts/dataTypes.xsd}region"/>
       *                           &lt;attribute name="dbChainId" type="{http://www.ebi.ac.uk/pdbe/docs/sifts/dataTypes.xsd}dbChainId" />
       *                         &lt;/restriction>
       *                       &lt;/complexContent>
       *                     &lt;/complexType>
       *                   &lt;/element>
       *                 &lt;/sequence>
       *                 &lt;attGroup ref="{http://www.ebi.ac.uk/pdbe/docs/sifts/dataTypes.xsd}region"/>
       *               &lt;/restriction>
       *             &lt;/complexContent>
       *           &lt;/complexType>
       *         &lt;/element>
       *       &lt;/sequence>
       *     &lt;/restriction>
       *   &lt;/complexContent>
       * &lt;/complexType>
       * </pre>
       * 
       * 
       */
      @XmlAccessorType(XmlAccessType.FIELD)
      @XmlType(name = "", propOrder = { "mapRegion" })
      public static class ListMapRegion
      {

        @XmlElement(required = true)
        protected List<Entry.Entity.Segment.ListMapRegion.MapRegion> mapRegion;

        /**
         * Gets the value of the mapRegion property.
         * 
         * <p>
         * This accessor method returns a reference to the live list, not a
         * snapshot. Therefore any modification you make to the returned list
         * will be present inside the JAXB object. This is why there is not a
         * <CODE>set</CODE> method for the mapRegion property.
         * 
         * <p>
         * For example, to add a new item, do as follows:
         * 
         * <pre>
         * getMapRegion().add(newItem);
         * </pre>
         * 
         * 
         * <p>
         * Objects of the following type(s) are allowed in the list
         * {@link Entry.Entity.Segment.ListMapRegion.MapRegion }
         * 
         * 
         */
        public List<Entry.Entity.Segment.ListMapRegion.MapRegion> getMapRegion()
        {
          if (mapRegion == null)
          {
            mapRegion = new ArrayList<Entry.Entity.Segment.ListMapRegion.MapRegion>();
          }
          return this.mapRegion;
        }

        /**
         * <p>
         * Java class for anonymous complex type.
         * 
         * <p>
         * The following schema fragment specifies the expected content
         * contained within this class.
         * 
         * <pre>
         * &lt;complexType>
         *   &lt;complexContent>
         *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
         *       &lt;sequence>
         *         &lt;element name="db">
         *           &lt;complexType>
         *             &lt;complexContent>
         *               &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
         *                 &lt;sequence>
         *                   &lt;element name="dbDetail" maxOccurs="unbounded" minOccurs="0">
         *                     &lt;complexType>
         *                       &lt;complexContent>
         *                         &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
         *                           &lt;attGroup ref="{http://www.ebi.ac.uk/pdbe/docs/sifts/dataTypes.xsd}detail"/>
         *                         &lt;/restriction>
         *                       &lt;/complexContent>
         *                     &lt;/complexType>
         *                   &lt;/element>
         *                 &lt;/sequence>
         *                 &lt;attGroup ref="{http://www.ebi.ac.uk/pdbe/docs/sifts/dataTypes.xsd}dbRef"/>
         *                 &lt;attGroup ref="{http://www.ebi.ac.uk/pdbe/docs/sifts/dataTypes.xsd}region"/>
         *                 &lt;attribute name="dbChainId" type="{http://www.ebi.ac.uk/pdbe/docs/sifts/dataTypes.xsd}dbChainId" />
         *               &lt;/restriction>
         *             &lt;/complexContent>
         *           &lt;/complexType>
         *         &lt;/element>
         *       &lt;/sequence>
         *       &lt;attGroup ref="{http://www.ebi.ac.uk/pdbe/docs/sifts/dataTypes.xsd}region"/>
         *     &lt;/restriction>
         *   &lt;/complexContent>
         * &lt;/complexType>
         * </pre>
         * 
         * 
         */
        @XmlAccessorType(XmlAccessType.FIELD)
        @XmlType(name = "", propOrder = { "db" })
        public static class MapRegion
        {

          @XmlElement(required = true)
          protected Entry.Entity.Segment.ListMapRegion.MapRegion.Db db;

          @XmlAttribute(name = "start")
          protected String start;

          @XmlAttribute(name = "end")
          protected String end;

          /**
           * Gets the value of the db property.
           * 
           * @return possible object is
           *         {@link Entry.Entity.Segment.ListMapRegion.MapRegion.Db }
           * 
           */
          public Entry.Entity.Segment.ListMapRegion.MapRegion.Db getDb()
          {
            return db;
          }

          /**
           * Sets the value of the db property.
           * 
           * @param value
           *          allowed object is
           *          {@link Entry.Entity.Segment.ListMapRegion.MapRegion.Db }
           * 
           */
          public void setDb(
                  Entry.Entity.Segment.ListMapRegion.MapRegion.Db value)
          {
            this.db = value;
          }

          /**
           * Gets the value of the start property.
           * 
           * @return possible object is {@link String }
           * 
           */
          public String getStart()
          {
            return start;
          }

          /**
           * Sets the value of the start property.
           * 
           * @param value
           *          allowed object is {@link String }
           * 
           */
          public void setStart(String value)
          {
            this.start = value;
          }

          /**
           * Gets the value of the end property.
           * 
           * @return possible object is {@link String }
           * 
           */
          public String getEnd()
          {
            return end;
          }

          /**
           * Sets the value of the end property.
           * 
           * @param value
           *          allowed object is {@link String }
           * 
           */
          public void setEnd(String value)
          {
            this.end = value;
          }

          /**
           * <p>
           * Java class for anonymous complex type.
           * 
           * <p>
           * The following schema fragment specifies the expected content
           * contained within this class.
           * 
           * <pre>
           * &lt;complexType>
           *   &lt;complexContent>
           *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
           *       &lt;sequence>
           *         &lt;element name="dbDetail" maxOccurs="unbounded" minOccurs="0">
           *           &lt;complexType>
           *             &lt;complexContent>
           *               &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
           *                 &lt;attGroup ref="{http://www.ebi.ac.uk/pdbe/docs/sifts/dataTypes.xsd}detail"/>
           *               &lt;/restriction>
           *             &lt;/complexContent>
           *           &lt;/complexType>
           *         &lt;/element>
           *       &lt;/sequence>
           *       &lt;attGroup ref="{http://www.ebi.ac.uk/pdbe/docs/sifts/dataTypes.xsd}dbRef"/>
           *       &lt;attGroup ref="{http://www.ebi.ac.uk/pdbe/docs/sifts/dataTypes.xsd}region"/>
           *       &lt;attribute name="dbChainId" type="{http://www.ebi.ac.uk/pdbe/docs/sifts/dataTypes.xsd}dbChainId" />
           *     &lt;/restriction>
           *   &lt;/complexContent>
           * &lt;/complexType>
           * </pre>
           * 
           * 
           */
          @XmlAccessorType(XmlAccessType.FIELD)
          @XmlType(name = "", propOrder = { "dbDetail" })
          public static class Db
          {

            protected List<Entry.Entity.Segment.ListMapRegion.MapRegion.Db.DbDetail> dbDetail;

            @XmlAttribute(name = "dbChainId")
            protected String dbChainId;

            @XmlAttribute(name = "dbSource", required = true)
            protected String dbSource;

            @XmlAttribute(name = "dbCoordSys", required = true)
            protected String dbCoordSys;

            @XmlAttribute(name = "dbAccessionId", required = true)
            protected String dbAccessionId;

            @XmlAttribute(name = "dbEvidence")
            protected String dbEvidence;

            @XmlAttribute(name = "dbVersion")
            protected String dbVersion;

            @XmlAttribute(name = "start")
            protected String start;

            @XmlAttribute(name = "end")
            protected String end;

            /**
             * Gets the value of the dbDetail property.
             * 
             * <p>
             * This accessor method returns a reference to the live list, not a
             * snapshot. Therefore any modification you make to the returned
             * list will be present inside the JAXB object. This is why there is
             * not a <CODE>set</CODE> method for the dbDetail property.
             * 
             * <p>
             * For example, to add a new item, do as follows:
             * 
             * <pre>
             * getDbDetail().add(newItem);
             * </pre>
             * 
             * 
             * <p>
             * Objects of the following type(s) are allowed in the list
             * {@link Entry.Entity.Segment.ListMapRegion.MapRegion.Db.DbDetail }
             * 
             * 
             */
            public List<Entry.Entity.Segment.ListMapRegion.MapRegion.Db.DbDetail> getDbDetail()
            {
              if (dbDetail == null)
              {
                dbDetail = new ArrayList<Entry.Entity.Segment.ListMapRegion.MapRegion.Db.DbDetail>();
              }
              return this.dbDetail;
            }

            /**
             * Gets the value of the dbChainId property.
             * 
             * @return possible object is {@link String }
             * 
             */
            public String getDbChainId()
            {
              return dbChainId;
            }

            /**
             * Sets the value of the dbChainId property.
             * 
             * @param value
             *          allowed object is {@link String }
             * 
             */
            public void setDbChainId(String value)
            {
              this.dbChainId = value;
            }

            /**
             * Gets the value of the dbSource property.
             * 
             * @return possible object is {@link String }
             * 
             */
            public String getDbSource()
            {
              return dbSource;
            }

            /**
             * Sets the value of the dbSource property.
             * 
             * @param value
             *          allowed object is {@link String }
             * 
             */
            public void setDbSource(String value)
            {
              this.dbSource = value;
            }

            /**
             * Gets the value of the dbCoordSys property.
             * 
             * @return possible object is {@link String }
             * 
             */
            public String getDbCoordSys()
            {
              return dbCoordSys;
            }

            /**
             * Sets the value of the dbCoordSys property.
             * 
             * @param value
             *          allowed object is {@link String }
             * 
             */
            public void setDbCoordSys(String value)
            {
              this.dbCoordSys = value;
            }

            /**
             * Gets the value of the dbAccessionId property.
             * 
             * @return possible object is {@link String }
             * 
             */
            public String getDbAccessionId()
            {
              return dbAccessionId;
            }

            /**
             * Sets the value of the dbAccessionId property.
             * 
             * @param value
             *          allowed object is {@link String }
             * 
             */
            public void setDbAccessionId(String value)
            {
              this.dbAccessionId = value;
            }

            /**
             * Gets the value of the dbEvidence property.
             * 
             * @return possible object is {@link String }
             * 
             */
            public String getDbEvidence()
            {
              return dbEvidence;
            }

            /**
             * Sets the value of the dbEvidence property.
             * 
             * @param value
             *          allowed object is {@link String }
             * 
             */
            public void setDbEvidence(String value)
            {
              this.dbEvidence = value;
            }

            /**
             * Gets the value of the dbVersion property.
             * 
             * @return possible object is {@link String }
             * 
             */
            public String getDbVersion()
            {
              return dbVersion;
            }

            /**
             * Sets the value of the dbVersion property.
             * 
             * @param value
             *          allowed object is {@link String }
             * 
             */
            public void setDbVersion(String value)
            {
              this.dbVersion = value;
            }

            /**
             * Gets the value of the start property.
             * 
             * @return possible object is {@link String }
             * 
             */
            public String getStart()
            {
              return start;
            }

            /**
             * Sets the value of the start property.
             * 
             * @param value
             *          allowed object is {@link String }
             * 
             */
            public void setStart(String value)
            {
              this.start = value;
            }

            /**
             * Gets the value of the end property.
             * 
             * @return possible object is {@link String }
             * 
             */
            public String getEnd()
            {
              return end;
            }

            /**
             * Sets the value of the end property.
             * 
             * @param value
             *          allowed object is {@link String }
             * 
             */
            public void setEnd(String value)
            {
              this.end = value;
            }

            /**
             * <p>
             * Java class for anonymous complex type.
             * 
             * <p>
             * The following schema fragment specifies the expected content
             * contained within this class.
             * 
             * <pre>
             * &lt;complexType>
             *   &lt;complexContent>
             *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
             *       &lt;attGroup ref="{http://www.ebi.ac.uk/pdbe/docs/sifts/dataTypes.xsd}detail"/>
             *     &lt;/restriction>
             *   &lt;/complexContent>
             * &lt;/complexType>
             * </pre>
             * 
             * 
             */
            @XmlAccessorType(XmlAccessType.FIELD)
            @XmlType(name = "", propOrder = { "content" })
            public static class DbDetail
            {

              @XmlValue
              protected String content;

              @XmlAttribute(name = "dbSource")
              protected String dbSource;

              @XmlAttribute(name = "property", required = true)
              protected String property;

              /**
               * Gets the value of the content property.
               * 
               * @return possible object is {@link String }
               * 
               */
              public String getContent()
              {
                return content;
              }

              /**
               * Sets the value of the content property.
               * 
               * @param value
               *          allowed object is {@link String }
               * 
               */
              public void setContent(String value)
              {
                this.content = value;
              }

              /**
               * Gets the value of the dbSource property.
               * 
               * @return possible object is {@link String }
               * 
               */
              public String getDbSource()
              {
                return dbSource;
              }

              /**
               * Sets the value of the dbSource property.
               * 
               * @param value
               *          allowed object is {@link String }
               * 
               */
              public void setDbSource(String value)
              {
                this.dbSource = value;
              }

              /**
               * Gets the value of the property property.
               * 
               * @return possible object is {@link String }
               * 
               */
              public String getProperty()
              {
                return property;
              }

              /**
               * Sets the value of the property property.
               * 
               * @param value
               *          allowed object is {@link String }
               * 
               */
              public void setProperty(String value)
              {
                this.property = value;
              }

            }

          }

        }

      }

      /**
       * <p>
       * Java class for anonymous complex type.
       * 
       * <p>
       * The following schema fragment specifies the expected content contained
       * within this class.
       * 
       * <pre>
       * &lt;complexType>
       *   &lt;complexContent>
       *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
       *       &lt;sequence>
       *         &lt;element name="residue" maxOccurs="unbounded">
       *           &lt;complexType>
       *             &lt;complexContent>
       *               &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
       *                 &lt;sequence>
       *                   &lt;element name="crossRefDb" maxOccurs="unbounded" minOccurs="0">
       *                     &lt;complexType>
       *                       &lt;complexContent>
       *                         &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
       *                           &lt;attGroup ref="{http://www.ebi.ac.uk/pdbe/docs/sifts/dataTypes.xsd}dbRef"/>
       *                           &lt;attGroup ref="{http://www.ebi.ac.uk/pdbe/docs/sifts/dataTypes.xsd}resRef"/>
       *                           &lt;attribute name="dbChainId" type="{http://www.ebi.ac.uk/pdbe/docs/sifts/dataTypes.xsd}chainId" />
       *                         &lt;/restriction>
       *                       &lt;/complexContent>
       *                     &lt;/complexType>
       *                   &lt;/element>
       *                   &lt;element name="residueDetail" maxOccurs="unbounded" minOccurs="0">
       *                     &lt;complexType>
       *                       &lt;complexContent>
       *                         &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
       *                           &lt;attGroup ref="{http://www.ebi.ac.uk/pdbe/docs/sifts/dataTypes.xsd}detail"/>
       *                         &lt;/restriction>
       *                       &lt;/complexContent>
       *                     &lt;/complexType>
       *                   &lt;/element>
       *                 &lt;/sequence>
       *                 &lt;attGroup ref="{http://www.ebi.ac.uk/pdbe/docs/sifts/dataTypes.xsd}resRef"/>
       *                 &lt;attGroup ref="{http://www.ebi.ac.uk/pdbe/docs/sifts/dataTypes.xsd}listdbRef"/>
       *               &lt;/restriction>
       *             &lt;/complexContent>
       *           &lt;/complexType>
       *         &lt;/element>
       *       &lt;/sequence>
       *     &lt;/restriction>
       *   &lt;/complexContent>
       * &lt;/complexType>
       * </pre>
       * 
       * 
       */
      @XmlAccessorType(XmlAccessType.FIELD)
      @XmlType(name = "", propOrder = { "residue" })
      public static class ListResidue
      {

        @XmlElement(required = true)
        protected List<Entry.Entity.Segment.ListResidue.Residue> residue;

        /**
         * Gets the value of the residue property.
         * 
         * <p>
         * This accessor method returns a reference to the live list, not a
         * snapshot. Therefore any modification you make to the returned list
         * will be present inside the JAXB object. This is why there is not a
         * <CODE>set</CODE> method for the residue property.
         * 
         * <p>
         * For example, to add a new item, do as follows:
         * 
         * <pre>
         * getResidue().add(newItem);
         * </pre>
         * 
         * 
         * <p>
         * Objects of the following type(s) are allowed in the list
         * {@link Entry.Entity.Segment.ListResidue.Residue }
         * 
         * 
         */
        public List<Entry.Entity.Segment.ListResidue.Residue> getResidue()
        {
          if (residue == null)
          {
            residue = new ArrayList<Entry.Entity.Segment.ListResidue.Residue>();
          }
          return this.residue;
        }

        /**
         * <p>
         * Java class for anonymous complex type.
         * 
         * <p>
         * The following schema fragment specifies the expected content
         * contained within this class.
         * 
         * <pre>
         * &lt;complexType>
         *   &lt;complexContent>
         *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
         *       &lt;sequence>
         *         &lt;element name="crossRefDb" maxOccurs="unbounded" minOccurs="0">
         *           &lt;complexType>
         *             &lt;complexContent>
         *               &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
         *                 &lt;attGroup ref="{http://www.ebi.ac.uk/pdbe/docs/sifts/dataTypes.xsd}dbRef"/>
         *                 &lt;attGroup ref="{http://www.ebi.ac.uk/pdbe/docs/sifts/dataTypes.xsd}resRef"/>
         *                 &lt;attribute name="dbChainId" type="{http://www.ebi.ac.uk/pdbe/docs/sifts/dataTypes.xsd}chainId" />
         *               &lt;/restriction>
         *             &lt;/complexContent>
         *           &lt;/complexType>
         *         &lt;/element>
         *         &lt;element name="residueDetail" maxOccurs="unbounded" minOccurs="0">
         *           &lt;complexType>
         *             &lt;complexContent>
         *               &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
         *                 &lt;attGroup ref="{http://www.ebi.ac.uk/pdbe/docs/sifts/dataTypes.xsd}detail"/>
         *               &lt;/restriction>
         *             &lt;/complexContent>
         *           &lt;/complexType>
         *         &lt;/element>
         *       &lt;/sequence>
         *       &lt;attGroup ref="{http://www.ebi.ac.uk/pdbe/docs/sifts/dataTypes.xsd}resRef"/>
         *       &lt;attGroup ref="{http://www.ebi.ac.uk/pdbe/docs/sifts/dataTypes.xsd}listdbRef"/>
         *     &lt;/restriction>
         *   &lt;/complexContent>
         * &lt;/complexType>
         * </pre>
         * 
         * 
         */
        @XmlAccessorType(XmlAccessType.FIELD)
        @XmlType(name = "", propOrder = { "crossRefDb", "residueDetail" })
        public static class Residue
        {

          protected List<Entry.Entity.Segment.ListResidue.Residue.CrossRefDb> crossRefDb;

          protected List<Entry.Entity.Segment.ListResidue.Residue.ResidueDetail> residueDetail;

          @XmlAttribute(name = "dbResNum", required = true)
          protected String dbResNum;

          @XmlAttribute(name = "dbResName", required = true)
          protected String dbResName;

          @XmlAttribute(name = "dbVersion")
          protected String dbVersion;

          @XmlAttribute(name = "dbSource", required = true)
          protected String dbSource;

          @XmlAttribute(name = "dbCoordSys", required = true)
          protected String dbCoordSys;

          /**
           * Gets the value of the crossRefDb property.
           * 
           * <p>
           * This accessor method returns a reference to the live list, not a
           * snapshot. Therefore any modification you make to the returned list
           * will be present inside the JAXB object. This is why there is not a
           * <CODE>set</CODE> method for the crossRefDb property.
           * 
           * <p>
           * For example, to add a new item, do as follows:
           * 
           * <pre>
           * getCrossRefDb().add(newItem);
           * </pre>
           * 
           * 
           * <p>
           * Objects of the following type(s) are allowed in the list
           * {@link Entry.Entity.Segment.ListResidue.Residue.CrossRefDb }
           * 
           * 
           */
          public List<Entry.Entity.Segment.ListResidue.Residue.CrossRefDb> getCrossRefDb()
          {
            if (crossRefDb == null)
            {
              crossRefDb = new ArrayList<Entry.Entity.Segment.ListResidue.Residue.CrossRefDb>();
            }
            return this.crossRefDb;
          }

          /**
           * Gets the value of the residueDetail property.
           * 
           * <p>
           * This accessor method returns a reference to the live list, not a
           * snapshot. Therefore any modification you make to the returned list
           * will be present inside the JAXB object. This is why there is not a
           * <CODE>set</CODE> method for the residueDetail property.
           * 
           * <p>
           * For example, to add a new item, do as follows:
           * 
           * <pre>
           * getResidueDetail().add(newItem);
           * </pre>
           * 
           * 
           * <p>
           * Objects of the following type(s) are allowed in the list
           * {@link Entry.Entity.Segment.ListResidue.Residue.ResidueDetail }
           * 
           * 
           */
          public List<Entry.Entity.Segment.ListResidue.Residue.ResidueDetail> getResidueDetail()
          {
            if (residueDetail == null)
            {
              residueDetail = new ArrayList<Entry.Entity.Segment.ListResidue.Residue.ResidueDetail>();
            }
            return this.residueDetail;
          }

          /**
           * Gets the value of the dbResNum property.
           * 
           * @return possible object is {@link String }
           * 
           */
          public String getDbResNum()
          {
            return dbResNum;
          }

          /**
           * Sets the value of the dbResNum property.
           * 
           * @param value
           *          allowed object is {@link String }
           * 
           */
          public void setDbResNum(String value)
          {
            this.dbResNum = value;
          }

          /**
           * Gets the value of the dbResName property.
           * 
           * @return possible object is {@link String }
           * 
           */
          public String getDbResName()
          {
            return dbResName;
          }

          /**
           * Sets the value of the dbResName property.
           * 
           * @param value
           *          allowed object is {@link String }
           * 
           */
          public void setDbResName(String value)
          {
            this.dbResName = value;
          }

          /**
           * Gets the value of the dbVersion property.
           * 
           * @return possible object is {@link String }
           * 
           */
          public String getDbVersion()
          {
            return dbVersion;
          }

          /**
           * Sets the value of the dbVersion property.
           * 
           * @param value
           *          allowed object is {@link String }
           * 
           */
          public void setDbVersion(String value)
          {
            this.dbVersion = value;
          }

          /**
           * Gets the value of the dbSource property.
           * 
           * @return possible object is {@link String }
           * 
           */
          public String getDbSource()
          {
            return dbSource;
          }

          /**
           * Sets the value of the dbSource property.
           * 
           * @param value
           *          allowed object is {@link String }
           * 
           */
          public void setDbSource(String value)
          {
            this.dbSource = value;
          }

          /**
           * Gets the value of the dbCoordSys property.
           * 
           * @return possible object is {@link String }
           * 
           */
          public String getDbCoordSys()
          {
            return dbCoordSys;
          }

          /**
           * Sets the value of the dbCoordSys property.
           * 
           * @param value
           *          allowed object is {@link String }
           * 
           */
          public void setDbCoordSys(String value)
          {
            this.dbCoordSys = value;
          }

          /**
           * <p>
           * Java class for anonymous complex type.
           * 
           * <p>
           * The following schema fragment specifies the expected content
           * contained within this class.
           * 
           * <pre>
           * &lt;complexType>
           *   &lt;complexContent>
           *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
           *       &lt;attGroup ref="{http://www.ebi.ac.uk/pdbe/docs/sifts/dataTypes.xsd}dbRef"/>
           *       &lt;attGroup ref="{http://www.ebi.ac.uk/pdbe/docs/sifts/dataTypes.xsd}resRef"/>
           *       &lt;attribute name="dbChainId" type="{http://www.ebi.ac.uk/pdbe/docs/sifts/dataTypes.xsd}chainId" />
           *     &lt;/restriction>
           *   &lt;/complexContent>
           * &lt;/complexType>
           * </pre>
           * 
           * 
           */
          @XmlAccessorType(XmlAccessType.FIELD)
          @XmlType(name = "")
          public static class CrossRefDb
          {

            @XmlAttribute(name = "dbChainId")
            protected String dbChainId;

            @XmlAttribute(name = "dbSource", required = true)
            protected String dbSource;

            @XmlAttribute(name = "dbCoordSys", required = true)
            protected String dbCoordSys;

            @XmlAttribute(name = "dbAccessionId", required = true)
            protected String dbAccessionId;

            @XmlAttribute(name = "dbEvidence")
            protected String dbEvidence;

            @XmlAttribute(name = "dbVersion")
            protected String dbVersion;

            @XmlAttribute(name = "dbResNum", required = true)
            protected String dbResNum;

            @XmlAttribute(name = "dbResName", required = true)
            protected String dbResName;

            /**
             * Gets the value of the dbChainId property.
             * 
             * @return possible object is {@link String }
             * 
             */
            public String getDbChainId()
            {
              return dbChainId;
            }

            /**
             * Sets the value of the dbChainId property.
             * 
             * @param value
             *          allowed object is {@link String }
             * 
             */
            public void setDbChainId(String value)
            {
              this.dbChainId = value;
            }

            /**
             * Gets the value of the dbSource property.
             * 
             * @return possible object is {@link String }
             * 
             */
            public String getDbSource()
            {
              return dbSource;
            }

            /**
             * Sets the value of the dbSource property.
             * 
             * @param value
             *          allowed object is {@link String }
             * 
             */
            public void setDbSource(String value)
            {
              this.dbSource = value;
            }

            /**
             * Gets the value of the dbCoordSys property.
             * 
             * @return possible object is {@link String }
             * 
             */
            public String getDbCoordSys()
            {
              return dbCoordSys;
            }

            /**
             * Sets the value of the dbCoordSys property.
             * 
             * @param value
             *          allowed object is {@link String }
             * 
             */
            public void setDbCoordSys(String value)
            {
              this.dbCoordSys = value;
            }

            /**
             * Gets the value of the dbAccessionId property.
             * 
             * @return possible object is {@link String }
             * 
             */
            public String getDbAccessionId()
            {
              return dbAccessionId;
            }

            /**
             * Sets the value of the dbAccessionId property.
             * 
             * @param value
             *          allowed object is {@link String }
             * 
             */
            public void setDbAccessionId(String value)
            {
              this.dbAccessionId = value;
            }

            /**
             * Gets the value of the dbEvidence property.
             * 
             * @return possible object is {@link String }
             * 
             */
            public String getDbEvidence()
            {
              return dbEvidence;
            }

            /**
             * Sets the value of the dbEvidence property.
             * 
             * @param value
             *          allowed object is {@link String }
             * 
             */
            public void setDbEvidence(String value)
            {
              this.dbEvidence = value;
            }

            /**
             * Gets the value of the dbVersion property.
             * 
             * @return possible object is {@link String }
             * 
             */
            public String getDbVersion()
            {
              return dbVersion;
            }

            /**
             * Sets the value of the dbVersion property.
             * 
             * @param value
             *          allowed object is {@link String }
             * 
             */
            public void setDbVersion(String value)
            {
              this.dbVersion = value;
            }

            /**
             * Gets the value of the dbResNum property.
             * 
             * @return possible object is {@link String }
             * 
             */
            public String getDbResNum()
            {
              return dbResNum;
            }

            /**
             * Sets the value of the dbResNum property.
             * 
             * @param value
             *          allowed object is {@link String }
             * 
             */
            public void setDbResNum(String value)
            {
              this.dbResNum = value;
            }

            /**
             * Gets the value of the dbResName property.
             * 
             * @return possible object is {@link String }
             * 
             */
            public String getDbResName()
            {
              return dbResName;
            }

            /**
             * Sets the value of the dbResName property.
             * 
             * @param value
             *          allowed object is {@link String }
             * 
             */
            public void setDbResName(String value)
            {
              this.dbResName = value;
            }

          }

          /**
           * <p>
           * Java class for anonymous complex type.
           * 
           * <p>
           * The following schema fragment specifies the expected content
           * contained within this class.
           * 
           * <pre>
           * &lt;complexType>
           *   &lt;complexContent>
           *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
           *       &lt;attGroup ref="{http://www.ebi.ac.uk/pdbe/docs/sifts/dataTypes.xsd}detail"/>
           *     &lt;/restriction>
           *   &lt;/complexContent>
           * &lt;/complexType>
           * </pre>
           * 
           * 
           */
          @XmlAccessorType(XmlAccessType.FIELD)
          @XmlType(name = "", propOrder = { "content" })
          public static class ResidueDetail
          {

            @XmlValue
            protected String content;

            @XmlAttribute(name = "dbSource")
            protected String dbSource;

            @XmlAttribute(name = "property", required = true)
            protected String property;

            /**
             * Gets the value of the content property.
             * 
             * @return possible object is {@link String }
             * 
             */
            public String getContent()
            {
              return content;
            }

            /**
             * Sets the value of the content property.
             * 
             * @param value
             *          allowed object is {@link String }
             * 
             */
            public void setContent(String value)
            {
              this.content = value;
            }

            /**
             * Gets the value of the dbSource property.
             * 
             * @return possible object is {@link String }
             * 
             */
            public String getDbSource()
            {
              return dbSource;
            }

            /**
             * Sets the value of the dbSource property.
             * 
             * @param value
             *          allowed object is {@link String }
             * 
             */
            public void setDbSource(String value)
            {
              this.dbSource = value;
            }

            /**
             * Gets the value of the property property.
             * 
             * @return possible object is {@link String }
             * 
             */
            public String getProperty()
            {
              return property;
            }

            /**
             * Sets the value of the property property.
             * 
             * @param value
             *          allowed object is {@link String }
             * 
             */
            public void setProperty(String value)
            {
              this.property = value;
            }

          }

        }

      }

      /**
       * <p>
       * Java class for anonymous complex type.
       * 
       * <p>
       * The following schema fragment specifies the expected content contained
       * within this class.
       * 
       * <pre>
       * &lt;complexType>
       *   &lt;complexContent>
       *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
       *       &lt;attGroup ref="{http://www.ebi.ac.uk/pdbe/docs/sifts/dataTypes.xsd}detail"/>
       *     &lt;/restriction>
       *   &lt;/complexContent>
       * &lt;/complexType>
       * </pre>
       * 
       * 
       */
      @XmlAccessorType(XmlAccessType.FIELD)
      @XmlType(name = "", propOrder = { "content" })
      public static class SegmentDetail
      {

        @XmlValue
        protected String content;

        @XmlAttribute(name = "dbSource")
        protected String dbSource;

        @XmlAttribute(name = "property", required = true)
        protected String property;

        /**
         * Gets the value of the content property.
         * 
         * @return possible object is {@link String }
         * 
         */
        public String getContent()
        {
          return content;
        }

        /**
         * Sets the value of the content property.
         * 
         * @param value
         *          allowed object is {@link String }
         * 
         */
        public void setContent(String value)
        {
          this.content = value;
        }

        /**
         * Gets the value of the dbSource property.
         * 
         * @return possible object is {@link String }
         * 
         */
        public String getDbSource()
        {
          return dbSource;
        }

        /**
         * Sets the value of the dbSource property.
         * 
         * @param value
         *          allowed object is {@link String }
         * 
         */
        public void setDbSource(String value)
        {
          this.dbSource = value;
        }

        /**
         * Gets the value of the property property.
         * 
         * @return possible object is {@link String }
         * 
         */
        public String getProperty()
        {
          return property;
        }

        /**
         * Sets the value of the property property.
         * 
         * @param value
         *          allowed object is {@link String }
         * 
         */
        public void setProperty(String value)
        {
          this.property = value;
        }

      }

    }

  }

  /**
   * <p>
   * Java class for anonymous complex type.
   * 
   * <p>
   * The following schema fragment specifies the expected content contained
   * within this class.
   * 
   * <pre>
   * &lt;complexType>
   *   &lt;complexContent>
   *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
   *       &lt;attGroup ref="{http://www.ebi.ac.uk/pdbe/docs/sifts/dataTypes.xsd}detail"/>
   *     &lt;/restriction>
   *   &lt;/complexContent>
   * &lt;/complexType>
   * </pre>
   * 
   * 
   */
  @XmlAccessorType(XmlAccessType.FIELD)
  @XmlType(name = "", propOrder = { "content" })
  public static class EntryDetail
  {

    @XmlValue
    protected String content;

    @XmlAttribute(name = "dbSource")
    protected String dbSource;

    @XmlAttribute(name = "property", required = true)
    protected String property;

    /**
     * Gets the value of the content property.
     * 
     * @return possible object is {@link String }
     * 
     */
    public String getContent()
    {
      return content;
    }

    /**
     * Sets the value of the content property.
     * 
     * @param value
     *          allowed object is {@link String }
     * 
     */
    public void setContent(String value)
    {
      this.content = value;
    }

    /**
     * Gets the value of the dbSource property.
     * 
     * @return possible object is {@link String }
     * 
     */
    public String getDbSource()
    {
      return dbSource;
    }

    /**
     * Sets the value of the dbSource property.
     * 
     * @param value
     *          allowed object is {@link String }
     * 
     */
    public void setDbSource(String value)
    {
      this.dbSource = value;
    }

    /**
     * Gets the value of the property property.
     * 
     * @return possible object is {@link String }
     * 
     */
    public String getProperty()
    {
      return property;
    }

    /**
     * Sets the value of the property property.
     * 
     * @param value
     *          allowed object is {@link String }
     * 
     */
    public void setProperty(String value)
    {
      this.property = value;
    }

  }

  /**
   * <p>
   * Java class for anonymous complex type.
   * 
   * <p>
   * The following schema fragment specifies the expected content contained
   * within this class.
   * 
   * <pre>
   * &lt;complexType>
   *   &lt;complexContent>
   *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
   *       &lt;sequence maxOccurs="unbounded">
   *         &lt;element name="db">
   *           &lt;complexType>
   *             &lt;complexContent>
   *               &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
   *                 &lt;attGroup ref="{http://www.ebi.ac.uk/pdbe/docs/sifts/dataTypes.xsd}listdbRef"/>
   *               &lt;/restriction>
   *             &lt;/complexContent>
   *           &lt;/complexType>
   *         &lt;/element>
   *       &lt;/sequence>
   *     &lt;/restriction>
   *   &lt;/complexContent>
   * &lt;/complexType>
   * </pre>
   * 
   * 
   */
  @XmlAccessorType(XmlAccessType.FIELD)
  @XmlType(name = "", propOrder = { "db" })
  public static class ListDB
  {

    @XmlElement(required = true)
    protected List<Entry.ListDB.Db> db;

    /**
     * Gets the value of the db property.
     * 
     * <p>
     * This accessor method returns a reference to the live list, not a
     * snapshot. Therefore any modification you make to the returned list will
     * be present inside the JAXB object. This is why there is not a
     * <CODE>set</CODE> method for the db property.
     * 
     * <p>
     * For example, to add a new item, do as follows:
     * 
     * <pre>
     * getDb().add(newItem);
     * </pre>
     * 
     * 
     * <p>
     * Objects of the following type(s) are allowed in the list
     * {@link Entry.ListDB.Db }
     * 
     * 
     */
    public List<Entry.ListDB.Db> getDb()
    {
      if (db == null)
      {
        db = new ArrayList<Entry.ListDB.Db>();
      }
      return this.db;
    }

    /**
     * <p>
     * Java class for anonymous complex type.
     * 
     * <p>
     * The following schema fragment specifies the expected content contained
     * within this class.
     * 
     * <pre>
     * &lt;complexType>
     *   &lt;complexContent>
     *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
     *       &lt;attGroup ref="{http://www.ebi.ac.uk/pdbe/docs/sifts/dataTypes.xsd}listdbRef"/>
     *     &lt;/restriction>
     *   &lt;/complexContent>
     * &lt;/complexType>
     * </pre>
     * 
     * 
     */
    @XmlAccessorType(XmlAccessType.FIELD)
    @XmlType(name = "")
    public static class Db
    {

      @XmlAttribute(name = "dbVersion")
      protected String dbVersion;

      @XmlAttribute(name = "dbSource", required = true)
      protected String dbSource;

      @XmlAttribute(name = "dbCoordSys", required = true)
      protected String dbCoordSys;

      /**
       * Gets the value of the dbVersion property.
       * 
       * @return possible object is {@link String }
       * 
       */
      public String getDbVersion()
      {
        return dbVersion;
      }

      /**
       * Sets the value of the dbVersion property.
       * 
       * @param value
       *          allowed object is {@link String }
       * 
       */
      public void setDbVersion(String value)
      {
        this.dbVersion = value;
      }

      /**
       * Gets the value of the dbSource property.
       * 
       * @return possible object is {@link String }
       * 
       */
      public String getDbSource()
      {
        return dbSource;
      }

      /**
       * Sets the value of the dbSource property.
       * 
       * @param value
       *          allowed object is {@link String }
       * 
       */
      public void setDbSource(String value)
      {
        this.dbSource = value;
      }

      /**
       * Gets the value of the dbCoordSys property.
       * 
       * @return possible object is {@link String }
       * 
       */
      public String getDbCoordSys()
      {
        return dbCoordSys;
      }

      /**
       * Sets the value of the dbCoordSys property.
       * 
       * @param value
       *          allowed object is {@link String }
       * 
       */
      public void setDbCoordSys(String value)
      {
        this.dbCoordSys = value;
      }

    }

  }

}
