//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.2.8-b130911.1802 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2015.10.09 at 03:18:33 PM BST 
//

package jalview.xml.binding.sifts;

import javax.xml.bind.annotation.XmlRegistry;

/**
 * This object contains factory methods for each Java content interface and Java
 * element interface generated in the jalview.xml.binding.sifts package.
 * <p>
 * An ObjectFactory allows you to programatically construct new instances of the
 * Java representation for XML content. The Java representation of XML content
 * can consist of schema derived interfaces and classes representing the binding
 * of schema type definitions, element declarations and model groups. Factory
 * methods for each of these are provided in this class.
 * 
 */
@XmlRegistry
public class ObjectFactory
{

  /**
   * Create a new ObjectFactory that can be used to create new instances of
   * schema derived classes for package: jalview.xml.binding.sifts
   * 
   */
  public ObjectFactory()
  {
  }

  /**
   * Create an instance of {@link Entry }
   * 
   */
  public Entry createEntry()
  {
    return new Entry();
  }

  /**
   * Create an instance of {@link Alignment }
   * 
   */
  public Alignment createAlignment()
  {
    return new Alignment();
  }

  /**
   * Create an instance of {@link Alignment.Geo3D }
   * 
   */
  public Alignment.Geo3D createAlignmentGeo3D()
  {
    return new Alignment.Geo3D();
  }

  /**
   * Create an instance of {@link Alignment.Geo3D.Matrix }
   * 
   */
  public Alignment.Geo3D.Matrix createAlignmentGeo3DMatrix()
  {
    return new Alignment.Geo3D.Matrix();
  }

  /**
   * Create an instance of {@link Alignment.Block }
   * 
   */
  public Alignment.Block createAlignmentBlock()
  {
    return new Alignment.Block();
  }

  /**
   * Create an instance of {@link Alignment.AlignObject }
   * 
   */
  public Alignment.AlignObject createAlignmentAlignObject()
  {
    return new Alignment.AlignObject();
  }

  /**
   * Create an instance of {@link Entry.Entity }
   * 
   */
  public Entry.Entity createEntryEntity()
  {
    return new Entry.Entity();
  }

  /**
   * Create an instance of {@link Entry.Entity.Segment }
   * 
   */
  public Entry.Entity.Segment createEntryEntitySegment()
  {
    return new Entry.Entity.Segment();
  }

  /**
   * Create an instance of {@link Entry.Entity.Segment.ListMapRegion }
   * 
   */
  public Entry.Entity.Segment.ListMapRegion createEntryEntitySegmentListMapRegion()
  {
    return new Entry.Entity.Segment.ListMapRegion();
  }

  /**
   * Create an instance of {@link Entry.Entity.Segment.ListMapRegion.MapRegion }
   * 
   */
  public Entry.Entity.Segment.ListMapRegion.MapRegion createEntryEntitySegmentListMapRegionMapRegion()
  {
    return new Entry.Entity.Segment.ListMapRegion.MapRegion();
  }

  /**
   * Create an instance of
   * {@link Entry.Entity.Segment.ListMapRegion.MapRegion.Db }
   * 
   */
  public Entry.Entity.Segment.ListMapRegion.MapRegion.Db createEntryEntitySegmentListMapRegionMapRegionDb()
  {
    return new Entry.Entity.Segment.ListMapRegion.MapRegion.Db();
  }

  /**
   * Create an instance of {@link Entry.Entity.Segment.ListResidue }
   * 
   */
  public Entry.Entity.Segment.ListResidue createEntryEntitySegmentListResidue()
  {
    return new Entry.Entity.Segment.ListResidue();
  }

  /**
   * Create an instance of {@link Entry.Entity.Segment.ListResidue.Residue }
   * 
   */
  public Entry.Entity.Segment.ListResidue.Residue createEntryEntitySegmentListResidueResidue()
  {
    return new Entry.Entity.Segment.ListResidue.Residue();
  }

  /**
   * Create an instance of {@link Entry.ListDB }
   * 
   */
  public Entry.ListDB createEntryListDB()
  {
    return new Entry.ListDB();
  }

  /**
   * Create an instance of {@link Entry.EntryDetail }
   * 
   */
  public Entry.EntryDetail createEntryEntryDetail()
  {
    return new Entry.EntryDetail();
  }

  /**
   * Create an instance of {@link Alignment.Score }
   * 
   */
  public Alignment.Score createAlignmentScore()
  {
    return new Alignment.Score();
  }

  /**
   * Create an instance of {@link Alignment.Geo3D.Vector }
   * 
   */
  public Alignment.Geo3D.Vector createAlignmentGeo3DVector()
  {
    return new Alignment.Geo3D.Vector();
  }

  /**
   * Create an instance of {@link Alignment.Geo3D.Matrix.Max11 }
   * 
   */
  public Alignment.Geo3D.Matrix.Max11 createAlignmentGeo3DMatrixMax11()
  {
    return new Alignment.Geo3D.Matrix.Max11();
  }

  /**
   * Create an instance of {@link Alignment.Geo3D.Matrix.Max12 }
   * 
   */
  public Alignment.Geo3D.Matrix.Max12 createAlignmentGeo3DMatrixMax12()
  {
    return new Alignment.Geo3D.Matrix.Max12();
  }

  /**
   * Create an instance of {@link Alignment.Geo3D.Matrix.Max13 }
   * 
   */
  public Alignment.Geo3D.Matrix.Max13 createAlignmentGeo3DMatrixMax13()
  {
    return new Alignment.Geo3D.Matrix.Max13();
  }

  /**
   * Create an instance of {@link Alignment.Geo3D.Matrix.Max21 }
   * 
   */
  public Alignment.Geo3D.Matrix.Max21 createAlignmentGeo3DMatrixMax21()
  {
    return new Alignment.Geo3D.Matrix.Max21();
  }

  /**
   * Create an instance of {@link Alignment.Geo3D.Matrix.Max22 }
   * 
   */
  public Alignment.Geo3D.Matrix.Max22 createAlignmentGeo3DMatrixMax22()
  {
    return new Alignment.Geo3D.Matrix.Max22();
  }

  /**
   * Create an instance of {@link Alignment.Geo3D.Matrix.Max23 }
   * 
   */
  public Alignment.Geo3D.Matrix.Max23 createAlignmentGeo3DMatrixMax23()
  {
    return new Alignment.Geo3D.Matrix.Max23();
  }

  /**
   * Create an instance of {@link Alignment.Geo3D.Matrix.Max31 }
   * 
   */
  public Alignment.Geo3D.Matrix.Max31 createAlignmentGeo3DMatrixMax31()
  {
    return new Alignment.Geo3D.Matrix.Max31();
  }

  /**
   * Create an instance of {@link Alignment.Geo3D.Matrix.Max32 }
   * 
   */
  public Alignment.Geo3D.Matrix.Max32 createAlignmentGeo3DMatrixMax32()
  {
    return new Alignment.Geo3D.Matrix.Max32();
  }

  /**
   * Create an instance of {@link Alignment.Geo3D.Matrix.Max33 }
   * 
   */
  public Alignment.Geo3D.Matrix.Max33 createAlignmentGeo3DMatrixMax33()
  {
    return new Alignment.Geo3D.Matrix.Max33();
  }

  /**
   * Create an instance of {@link Alignment.Block.Segment }
   * 
   */
  public Alignment.Block.Segment createAlignmentBlockSegment()
  {
    return new Alignment.Block.Segment();
  }

  /**
   * Create an instance of {@link Alignment.AlignObject.AlignObjectDetail }
   * 
   */
  public Alignment.AlignObject.AlignObjectDetail createAlignmentAlignObjectAlignObjectDetail()
  {
    return new Alignment.AlignObject.AlignObjectDetail();
  }

  /**
   * Create an instance of {@link Alignment.AlignObject.Sequence }
   * 
   */
  public Alignment.AlignObject.Sequence createAlignmentAlignObjectSequence()
  {
    return new Alignment.AlignObject.Sequence();
  }

  /**
   * Create an instance of {@link Entry.Entity.EntityDetail }
   * 
   */
  public Entry.Entity.EntityDetail createEntryEntityEntityDetail()
  {
    return new Entry.Entity.EntityDetail();
  }

  /**
   * Create an instance of {@link Entry.Entity.Segment.SegmentDetail }
   * 
   */
  public Entry.Entity.Segment.SegmentDetail createEntryEntitySegmentSegmentDetail()
  {
    return new Entry.Entity.Segment.SegmentDetail();
  }

  /**
   * Create an instance of
   * {@link Entry.Entity.Segment.ListMapRegion.MapRegion.Db.DbDetail }
   * 
   */
  public Entry.Entity.Segment.ListMapRegion.MapRegion.Db.DbDetail createEntryEntitySegmentListMapRegionMapRegionDbDbDetail()
  {
    return new Entry.Entity.Segment.ListMapRegion.MapRegion.Db.DbDetail();
  }

  /**
   * Create an instance of
   * {@link Entry.Entity.Segment.ListResidue.Residue.CrossRefDb }
   * 
   */
  public Entry.Entity.Segment.ListResidue.Residue.CrossRefDb createEntryEntitySegmentListResidueResidueCrossRefDb()
  {
    return new Entry.Entity.Segment.ListResidue.Residue.CrossRefDb();
  }

  /**
   * Create an instance of
   * {@link Entry.Entity.Segment.ListResidue.Residue.ResidueDetail }
   * 
   */
  public Entry.Entity.Segment.ListResidue.Residue.ResidueDetail createEntryEntitySegmentListResidueResidueResidueDetail()
  {
    return new Entry.Entity.Segment.ListResidue.Residue.ResidueDetail();
  }

  /**
   * Create an instance of {@link Entry.ListDB.Db }
   * 
   */
  public Entry.ListDB.Db createEntryListDBDb()
  {
    return new Entry.ListDB.Db();
  }

}
