//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.2.8-b130911.1802 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2018.09.14 at 02:46:00 PM BST 
//

package jalview.xml.binding.embl;

import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlRootElement;
import javax.xml.bind.annotation.XmlType;

/**
 * <p>
 * Java class for anonymous complex type.
 * 
 * <p>
 * The following schema fragment specifies the expected content contained within
 * this class.
 * 
 * <pre>
 * &lt;complexType>
 *   &lt;complexContent>
 *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *       &lt;choice>
 *         &lt;element name="entrySet" type="{}EntrySetType"/>
 *         &lt;element name="entry" type="{}EntryType"/>
 *       &lt;/choice>
 *     &lt;/restriction>
 *   &lt;/complexContent>
 * &lt;/complexType>
 * </pre>
 * 
 * 
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "", propOrder = { "entrySet", "entry" })
@XmlRootElement(name = "ROOT")
public class ROOT
{

  protected EntrySetType entrySet;

  protected EntryType entry;

  /**
   * Gets the value of the entrySet property.
   * 
   * @return possible object is {@link EntrySetType }
   * 
   */
  public EntrySetType getEntrySet()
  {
    return entrySet;
  }

  /**
   * Sets the value of the entrySet property.
   * 
   * @param value
   *          allowed object is {@link EntrySetType }
   * 
   */
  public void setEntrySet(EntrySetType value)
  {
    this.entrySet = value;
  }

  /**
   * Gets the value of the entry property.
   * 
   * @return possible object is {@link EntryType }
   * 
   */
  public EntryType getEntry()
  {
    return entry;
  }

  /**
   * Sets the value of the entry property.
   * 
   * @param value
   *          allowed object is {@link EntryType }
   * 
   */
  public void setEntry(EntryType value)
  {
    this.entry = value;
  }

}
