//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.2.8-b130911.1802 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2018.09.14 at 02:46:00 PM BST 
//

package jalview.xml.binding.embl;

import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlAttribute;
import javax.xml.bind.annotation.XmlType;

/**
 * Database cross-reference.
 * 
 * <p>
 * Java class for XrefType complex type.
 * 
 * <p>
 * The following schema fragment specifies the expected content contained within
 * this class.
 * 
 * <pre>
 * &lt;complexType name="XrefType">
 *   &lt;complexContent>
 *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *       &lt;attribute name="db" use="required" type="{http://www.w3.org/2001/XMLSchema}string" />
 *       &lt;attribute name="id" use="required" type="{http://www.w3.org/2001/XMLSchema}string" />
 *       &lt;attribute name="secondaryId" type="{http://www.w3.org/2001/XMLSchema}string" />
 *     &lt;/restriction>
 *   &lt;/complexContent>
 * &lt;/complexType>
 * </pre>
 * 
 * 
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "XrefType")
public class XrefType
{

  @XmlAttribute(name = "db", required = true)
  protected String db;

  @XmlAttribute(name = "id", required = true)
  protected String id;

  @XmlAttribute(name = "secondaryId")
  protected String secondaryId;

  /**
   * Gets the value of the db property.
   * 
   * @return possible object is {@link String }
   * 
   */
  public String getDb()
  {
    return db;
  }

  /**
   * Sets the value of the db property.
   * 
   * @param value
   *          allowed object is {@link String }
   * 
   */
  public void setDb(String value)
  {
    this.db = value;
  }

  /**
   * Gets the value of the id property.
   * 
   * @return possible object is {@link String }
   * 
   */
  public String getId()
  {
    return id;
  }

  /**
   * Sets the value of the id property.
   * 
   * @param value
   *          allowed object is {@link String }
   * 
   */
  public void setId(String value)
  {
    this.id = value;
  }

  /**
   * Gets the value of the secondaryId property.
   * 
   * @return possible object is {@link String }
   * 
   */
  public String getSecondaryId()
  {
    return secondaryId;
  }

  /**
   * Sets the value of the secondaryId property.
   * 
   * @param value
   *          allowed object is {@link String }
   * 
   */
  public void setSecondaryId(String value)
  {
    this.secondaryId = value;
  }

}
