(function(){var P$=Clazz.newPackage("jalview.schemes"),I$=[[0,'java.util.HashMap','java.awt.Color','java.util.Arrays','java.util.Hashtable','jalview.analysis.GeneticCodes','java.util.ArrayList']],$I$=function(i){return I$[i]||(I$[i]=Clazz.load(I$[0][i]))};
var C$=Clazz.newClass(P$, "ResidueProperties");
C$.aaIndex=null;
C$.nucleotideIndex=null;
C$.purinepyrimidineIndex=null;
C$.aa3Hash=null;
C$.aa2Triplet=null;
C$.nucleotideName=null;
C$.modifications=null;
C$.ONE=null;
C$.ZERO=null;
C$.aa=null;
C$.midBlue=null;
C$.taylor=null;
C$.nucleotide=null;
C$.purinepyrimidine=null;
C$.zappo=null;
C$.hyd2=null;
C$.helix=null;
C$.strand=null;
C$.turn=null;
C$.buried=null;
C$.hyd=null;
C$.STOP=null;
C$.STOP_CODONS=null;
C$.START=null;
C$.propHash=null;
C$.hydrophobic=null;
C$.polar=null;
C$.small=null;
C$.positive=null;
C$.negative=null;
C$.charged=null;
C$.aromatic=null;
C$.aliphatic=null;
C$.tiny=null;
C$.proline=null;
C$.toDssp3State=null;

C$.$clinit$ = function() {Clazz.load(C$, 1);
C$.aa3Hash=Clazz.new_($I$(1));
C$.aa2Triplet=Clazz.new_($I$(1));
C$.nucleotideName=Clazz.new_($I$(1));
C$.modifications=Clazz.new_($I$(1));
{
C$.aaIndex=Clazz.array(Integer.TYPE, [255]);
for (var i=0; i < 255; i++) {
C$.aaIndex[i]=23;
}
C$.aaIndex[65]=0;
C$.aaIndex[82]=1;
C$.aaIndex[78]=2;
C$.aaIndex[68]=3;
C$.aaIndex[67]=4;
C$.aaIndex[81]=5;
C$.aaIndex[69]=6;
C$.aaIndex[71]=7;
C$.aaIndex[72]=8;
C$.aaIndex[73]=9;
C$.aaIndex[76]=10;
C$.aaIndex[75]=11;
C$.aaIndex[77]=12;
C$.aaIndex[70]=13;
C$.aaIndex[80]=14;
C$.aaIndex[83]=15;
C$.aaIndex[84]=16;
C$.aaIndex[87]=17;
C$.aaIndex[89]=18;
C$.aaIndex[86]=19;
C$.aaIndex[66]=20;
C$.aaIndex[90]=21;
C$.aaIndex[88]=22;
C$.aaIndex[85]=22;
C$.aaIndex[97]=0;
C$.aaIndex[114]=1;
C$.aaIndex[110]=2;
C$.aaIndex[100]=3;
C$.aaIndex[99]=4;
C$.aaIndex[113]=5;
C$.aaIndex[101]=6;
C$.aaIndex[103]=7;
C$.aaIndex[104]=8;
C$.aaIndex[105]=9;
C$.aaIndex[108]=10;
C$.aaIndex[107]=11;
C$.aaIndex[109]=12;
C$.aaIndex[102]=13;
C$.aaIndex[112]=14;
C$.aaIndex[115]=15;
C$.aaIndex[116]=16;
C$.aaIndex[119]=17;
C$.aaIndex[121]=18;
C$.aaIndex[118]=19;
C$.aaIndex[98]=20;
C$.aaIndex[122]=21;
C$.aaIndex[120]=22;
C$.aaIndex[117]=22;
};
{
C$.nucleotideIndex=Clazz.array(Integer.TYPE, [255]);
for (var i=0; i < 255; i++) {
C$.nucleotideIndex[i]=10;
}
C$.nucleotideIndex[65]=0;
C$.nucleotideIndex[97]=0;
C$.nucleotideIndex[67]=1;
C$.nucleotideIndex[99]=1;
C$.nucleotideIndex[71]=2;
C$.nucleotideIndex[103]=2;
C$.nucleotideIndex[84]=3;
C$.nucleotideIndex[116]=3;
C$.nucleotideIndex[85]=4;
C$.nucleotideIndex[117]=4;
C$.nucleotideIndex[73]=5;
C$.nucleotideIndex[105]=5;
C$.nucleotideIndex[88]=6;
C$.nucleotideIndex[120]=6;
C$.nucleotideIndex[82]=7;
C$.nucleotideIndex[114]=7;
C$.nucleotideIndex[89]=8;
C$.nucleotideIndex[121]=8;
C$.nucleotideIndex[78]=9;
C$.nucleotideIndex[110]=9;
C$.nucleotideName.put$TK$TV("A", "Adenine");
C$.nucleotideName.put$TK$TV("a", "Adenine");
C$.nucleotideName.put$TK$TV("G", "Guanine");
C$.nucleotideName.put$TK$TV("g", "Guanine");
C$.nucleotideName.put$TK$TV("C", "Cytosine");
C$.nucleotideName.put$TK$TV("c", "Cytosine");
C$.nucleotideName.put$TK$TV("T", "Thymine");
C$.nucleotideName.put$TK$TV("t", "Thymine");
C$.nucleotideName.put$TK$TV("U", "Uracil");
C$.nucleotideName.put$TK$TV("u", "Uracil");
C$.nucleotideName.put$TK$TV("I", "Inosine");
C$.nucleotideName.put$TK$TV("i", "Inosine");
C$.nucleotideName.put$TK$TV("X", "Xanthine");
C$.nucleotideName.put$TK$TV("x", "Xanthine");
C$.nucleotideName.put$TK$TV("R", "Unknown Purine");
C$.nucleotideName.put$TK$TV("r", "Unknown Purine");
C$.nucleotideName.put$TK$TV("Y", "Unknown Pyrimidine");
C$.nucleotideName.put$TK$TV("y", "Unknown Pyrimidine");
C$.nucleotideName.put$TK$TV("N", "Unknown");
C$.nucleotideName.put$TK$TV("n", "Unknown");
C$.nucleotideName.put$TK$TV("W", "Weak nucleotide (A or T)");
C$.nucleotideName.put$TK$TV("w", "Weak nucleotide (A or T)");
C$.nucleotideName.put$TK$TV("S", "Strong nucleotide (G or C)");
C$.nucleotideName.put$TK$TV("s", "Strong nucleotide (G or C)");
C$.nucleotideName.put$TK$TV("M", "Amino (A or C)");
C$.nucleotideName.put$TK$TV("m", "Amino (A or C)");
C$.nucleotideName.put$TK$TV("K", "Keto (G or T)");
C$.nucleotideName.put$TK$TV("k", "Keto (G or T)");
C$.nucleotideName.put$TK$TV("B", "Not A (G or C or T)");
C$.nucleotideName.put$TK$TV("b", "Not A (G or C or T)");
C$.nucleotideName.put$TK$TV("H", "Not G (A or C or T)");
C$.nucleotideName.put$TK$TV("h", "Not G (A or C or T)");
C$.nucleotideName.put$TK$TV("D", "Not C (A or G or T)");
C$.nucleotideName.put$TK$TV("d", "Not C (A or G or T)");
C$.nucleotideName.put$TK$TV("V", "Not T (A or G or C");
C$.nucleotideName.put$TK$TV("v", "Not T (A or G or C");
};
{
C$.purinepyrimidineIndex=Clazz.array(Integer.TYPE, [255]);
for (var i=0; i < 255; i++) {
C$.purinepyrimidineIndex[i]=3;
}
C$.purinepyrimidineIndex[65]=0;
C$.purinepyrimidineIndex[97]=0;
C$.purinepyrimidineIndex[67]=1;
C$.purinepyrimidineIndex[99]=1;
C$.purinepyrimidineIndex[71]=0;
C$.purinepyrimidineIndex[103]=0;
C$.purinepyrimidineIndex[84]=1;
C$.purinepyrimidineIndex[116]=1;
C$.purinepyrimidineIndex[85]=1;
C$.purinepyrimidineIndex[117]=1;
C$.purinepyrimidineIndex[73]=2;
C$.purinepyrimidineIndex[105]=2;
C$.purinepyrimidineIndex[88]=2;
C$.purinepyrimidineIndex[120]=2;
C$.purinepyrimidineIndex[82]=0;
C$.purinepyrimidineIndex[114]=0;
C$.purinepyrimidineIndex[89]=1;
C$.purinepyrimidineIndex[121]=1;
C$.purinepyrimidineIndex[78]=2;
C$.purinepyrimidineIndex[110]=2;
};
C$.ONE=Integer.valueOf$I(1);
C$.ZERO=Integer.valueOf$I(0);
{
C$.aa3Hash.put$TK$TV("ALA", C$.ZERO);
C$.aa3Hash.put$TK$TV("ARG", C$.ONE);
C$.aa3Hash.put$TK$TV("ASN", Integer.valueOf$I(2));
C$.aa3Hash.put$TK$TV("ASP", Integer.valueOf$I(3));
C$.aa3Hash.put$TK$TV("CYS", Integer.valueOf$I(4));
C$.aa3Hash.put$TK$TV("GLN", Integer.valueOf$I(5));
C$.aa3Hash.put$TK$TV("GLU", Integer.valueOf$I(6));
C$.aa3Hash.put$TK$TV("GLY", Integer.valueOf$I(7));
C$.aa3Hash.put$TK$TV("HIS", Integer.valueOf$I(8));
C$.aa3Hash.put$TK$TV("ILE", Integer.valueOf$I(9));
C$.aa3Hash.put$TK$TV("LEU", Integer.valueOf$I(10));
C$.aa3Hash.put$TK$TV("LYS", Integer.valueOf$I(11));
C$.aa3Hash.put$TK$TV("MET", Integer.valueOf$I(12));
C$.aa3Hash.put$TK$TV("PHE", Integer.valueOf$I(13));
C$.aa3Hash.put$TK$TV("PRO", Integer.valueOf$I(14));
C$.aa3Hash.put$TK$TV("SER", Integer.valueOf$I(15));
C$.aa3Hash.put$TK$TV("THR", Integer.valueOf$I(16));
C$.aa3Hash.put$TK$TV("TRP", Integer.valueOf$I(17));
C$.aa3Hash.put$TK$TV("TYR", Integer.valueOf$I(18));
C$.aa3Hash.put$TK$TV("VAL", Integer.valueOf$I(19));
C$.aa3Hash.put$TK$TV("ASX", Integer.valueOf$I(20));
C$.aa3Hash.put$TK$TV("GLX", Integer.valueOf$I(21));
C$.aa3Hash.put$TK$TV("XAA", Integer.valueOf$I(22));
C$.aa3Hash.put$TK$TV("-", Integer.valueOf$I(23));
C$.aa3Hash.put$TK$TV("*", Integer.valueOf$I(23));
C$.aa3Hash.put$TK$TV(".", Integer.valueOf$I(23));
C$.aa3Hash.put$TK$TV(" ", Integer.valueOf$I(23));
C$.aa3Hash.put$TK$TV("Gap", Integer.valueOf$I(23));
C$.aa3Hash.put$TK$TV("UR3", Integer.valueOf$I(24));
};
{
C$.aa2Triplet.put$TK$TV("A", "ALA");
C$.aa2Triplet.put$TK$TV("a", "ALA");
C$.aa2Triplet.put$TK$TV("R", "ARG");
C$.aa2Triplet.put$TK$TV("r", "ARG");
C$.aa2Triplet.put$TK$TV("N", "ASN");
C$.aa2Triplet.put$TK$TV("n", "ASN");
C$.aa2Triplet.put$TK$TV("D", "ASP");
C$.aa2Triplet.put$TK$TV("d", "ASP");
C$.aa2Triplet.put$TK$TV("C", "CYS");
C$.aa2Triplet.put$TK$TV("c", "CYS");
C$.aa2Triplet.put$TK$TV("Q", "GLN");
C$.aa2Triplet.put$TK$TV("q", "GLN");
C$.aa2Triplet.put$TK$TV("E", "GLU");
C$.aa2Triplet.put$TK$TV("e", "GLU");
C$.aa2Triplet.put$TK$TV("G", "GLY");
C$.aa2Triplet.put$TK$TV("g", "GLY");
C$.aa2Triplet.put$TK$TV("H", "HIS");
C$.aa2Triplet.put$TK$TV("h", "HIS");
C$.aa2Triplet.put$TK$TV("I", "ILE");
C$.aa2Triplet.put$TK$TV("i", "ILE");
C$.aa2Triplet.put$TK$TV("L", "LEU");
C$.aa2Triplet.put$TK$TV("l", "LEU");
C$.aa2Triplet.put$TK$TV("K", "LYS");
C$.aa2Triplet.put$TK$TV("k", "LYS");
C$.aa2Triplet.put$TK$TV("M", "MET");
C$.aa2Triplet.put$TK$TV("m", "MET");
C$.aa2Triplet.put$TK$TV("F", "PHE");
C$.aa2Triplet.put$TK$TV("f", "PHE");
C$.aa2Triplet.put$TK$TV("P", "PRO");
C$.aa2Triplet.put$TK$TV("p", "PRO");
C$.aa2Triplet.put$TK$TV("S", "SER");
C$.aa2Triplet.put$TK$TV("s", "SER");
C$.aa2Triplet.put$TK$TV("T", "THR");
C$.aa2Triplet.put$TK$TV("t", "THR");
C$.aa2Triplet.put$TK$TV("W", "TRP");
C$.aa2Triplet.put$TK$TV("w", "TRP");
C$.aa2Triplet.put$TK$TV("Y", "TYR");
C$.aa2Triplet.put$TK$TV("y", "TYR");
C$.aa2Triplet.put$TK$TV("V", "VAL");
C$.aa2Triplet.put$TK$TV("v", "VAL");
};
C$.aa=Clazz.array(String, -1, ["A", "R", "N", "D", "C", "Q", "E", "G", "H", "I", "L", "K", "M", "F", "P", "S", "T", "W", "Y", "V", "B", "Z", "X", "_", "*", ".", " ", "U"]);
C$.midBlue=Clazz.new_($I$(2).c$$I$I$I,[100, 100, 255]);
C$.taylor=Clazz.array($I$(2), -1, [Clazz.new_($I$(2).c$$I$I$I,[204, 255, 0]), Clazz.new_($I$(2).c$$I$I$I,[0, 0, 255]), Clazz.new_($I$(2).c$$I$I$I,[204, 0, 255]), Clazz.new_($I$(2).c$$I$I$I,[255, 0, 0]), Clazz.new_($I$(2).c$$I$I$I,[255, 255, 0]), Clazz.new_($I$(2).c$$I$I$I,[255, 0, 204]), Clazz.new_($I$(2).c$$I$I$I,[255, 0, 102]), Clazz.new_($I$(2).c$$I$I$I,[255, 153, 0]), Clazz.new_($I$(2).c$$I$I$I,[0, 102, 255]), Clazz.new_($I$(2).c$$I$I$I,[102, 255, 0]), Clazz.new_($I$(2).c$$I$I$I,[51, 255, 0]), Clazz.new_($I$(2).c$$I$I$I,[102, 0, 255]), Clazz.new_($I$(2).c$$I$I$I,[0, 255, 0]), Clazz.new_($I$(2).c$$I$I$I,[0, 255, 102]), Clazz.new_($I$(2).c$$I$I$I,[255, 204, 0]), Clazz.new_($I$(2).c$$I$I$I,[255, 51, 0]), Clazz.new_($I$(2).c$$I$I$I,[255, 102, 0]), Clazz.new_($I$(2).c$$I$I$I,[0, 204, 255]), Clazz.new_($I$(2).c$$I$I$I,[0, 255, 204]), Clazz.new_($I$(2).c$$I$I$I,[153, 255, 0]), $I$(2).white, $I$(2).white, $I$(2).white, $I$(2).white, $I$(2).white, $I$(2).white]);
C$.nucleotide=Clazz.array($I$(2), -1, [Clazz.new_($I$(2).c$$I$I$I,[100, 247, 63]), Clazz.new_($I$(2).c$$I$I$I,[255, 179, 64]), Clazz.new_($I$(2).c$$I$I$I,[235, 65, 60]), Clazz.new_($I$(2).c$$I$I$I,[60, 136, 238]), Clazz.new_($I$(2).c$$I$I$I,[60, 136, 238]), $I$(2).white, $I$(2).white, $I$(2).white, $I$(2).white, $I$(2).white, $I$(2).white]);
C$.purinepyrimidine=Clazz.array($I$(2), -1, [Clazz.new_($I$(2).c$$I$I$I,[255, 131, 250]), Clazz.new_($I$(2).c$$I$I$I,[64, 224, 208]), $I$(2).white, $I$(2).white]);
C$.zappo=Clazz.array($I$(2), -1, [$I$(2).pink, C$.midBlue, $I$(2).green, $I$(2).red, $I$(2).yellow, $I$(2).green, $I$(2).red, $I$(2).magenta, C$.midBlue, $I$(2).pink, $I$(2).pink, C$.midBlue, $I$(2).pink, $I$(2).orange, $I$(2).magenta, $I$(2).green, $I$(2).green, $I$(2).orange, $I$(2).orange, $I$(2).pink, $I$(2).white, $I$(2).white, $I$(2).white, $I$(2).white, $I$(2).white, $I$(2).white, $I$(2).white]);
C$.hyd2=Clazz.array(Double.TYPE, -1, [0.62, 0.29, -0.9, -0.74, 1.19, 0.48, -0.4, 1.38, -1.5, 1.06, 0.64, -0.78, 0.12, -0.85, -2.53, -0.18, -0.05, 1.08, 0.81, 0.0, 0.26, 0.0, 0.0]);
C$.helix=Clazz.array(Double.TYPE, -1, [1.42, 0.98, 0.67, 1.01, 0.7, 1.11, 1.51, 0.57, 1.0, 1.08, 1.21, 1.16, 1.45, 1.13, 0.57, 0.77, 0.83, 1.08, 0.69, 1.06, 0.84, 1.31, 1.0, 0.0]);
C$.strand=Clazz.array(Double.TYPE, -1, [0.83, 0.93, 0.89, 0.54, 1.19, 1.1, 0.37, 0.75, 0.87, 1.6, 1.3, 0.74, 1.05, 1.38, 0.55, 0.75, 1.19, 1.37, 1.47, 1.7, 0.72, 0.74, 1.0, 0.0]);
C$.turn=Clazz.array(Double.TYPE, -1, [0.66, 0.95, 1.56, 1.46, 1.19, 0.98, 0.74, 1.56, 0.95, 0.47, 0.59, 1.01, 0.6, 0.6, 1.52, 1.43, 0.96, 0.96, 1.14, 0.5, 1.51, 0.86, 1.0, 0, 0]);
C$.buried=Clazz.array(Double.TYPE, -1, [1.7, 0.1, 0.4, 0.4, 4.6, 0.3, 0.3, 1.8, 0.8, 3.1, 2.4, 0.05, 1.9, 2.2, 0.6, 0.8, 0.7, 1.6, 0.5, 2.9, 0.4, 0.3, 1.358, 0.0]);
C$.hyd=Clazz.array(Double.TYPE, -1, [1.8, -4.5, -3.5, -3.5, 2.5, -3.5, -3.5, -0.4, -3.2, 4.5, 3.8, -3.9, 1.9, 2.8, -1.6, -0.8, -0.7, -0.9, -1.3, 4.2, -3.5, -3.5, -0.49, 0.0]);
C$.STOP="STOP";
C$.STOP_CODONS=$I$(3).asList$TTA(["TGA", "TAA", "TAG"]);
C$.START="ATG";
C$.propHash=Clazz.new_($I$(4));
C$.hydrophobic=Clazz.new_($I$(4));
C$.polar=Clazz.new_($I$(4));
C$.small=Clazz.new_($I$(4));
C$.positive=Clazz.new_($I$(4));
C$.negative=Clazz.new_($I$(4));
C$.charged=Clazz.new_($I$(4));
C$.aromatic=Clazz.new_($I$(4));
C$.aliphatic=Clazz.new_($I$(4));
C$.tiny=Clazz.new_($I$(4));
C$.proline=Clazz.new_($I$(4));
{
C$.hydrophobic.put$TK$TV("I", C$.ONE);
C$.hydrophobic.put$TK$TV("L", C$.ONE);
C$.hydrophobic.put$TK$TV("V", C$.ONE);
C$.hydrophobic.put$TK$TV("C", C$.ONE);
C$.hydrophobic.put$TK$TV("A", C$.ONE);
C$.hydrophobic.put$TK$TV("G", C$.ONE);
C$.hydrophobic.put$TK$TV("M", C$.ONE);
C$.hydrophobic.put$TK$TV("F", C$.ONE);
C$.hydrophobic.put$TK$TV("Y", C$.ONE);
C$.hydrophobic.put$TK$TV("W", C$.ONE);
C$.hydrophobic.put$TK$TV("H", C$.ONE);
C$.hydrophobic.put$TK$TV("K", C$.ONE);
C$.hydrophobic.put$TK$TV("X", C$.ONE);
C$.hydrophobic.put$TK$TV("-", C$.ONE);
C$.hydrophobic.put$TK$TV("*", C$.ONE);
C$.hydrophobic.put$TK$TV("R", C$.ZERO);
C$.hydrophobic.put$TK$TV("E", C$.ZERO);
C$.hydrophobic.put$TK$TV("Q", C$.ZERO);
C$.hydrophobic.put$TK$TV("D", C$.ZERO);
C$.hydrophobic.put$TK$TV("N", C$.ZERO);
C$.hydrophobic.put$TK$TV("S", C$.ZERO);
C$.hydrophobic.put$TK$TV("T", C$.ONE);
C$.hydrophobic.put$TK$TV("P", C$.ZERO);
};
{
C$.polar.put$TK$TV("Y", C$.ONE);
C$.polar.put$TK$TV("W", C$.ONE);
C$.polar.put$TK$TV("H", C$.ONE);
C$.polar.put$TK$TV("K", C$.ONE);
C$.polar.put$TK$TV("R", C$.ONE);
C$.polar.put$TK$TV("E", C$.ONE);
C$.polar.put$TK$TV("Q", C$.ONE);
C$.polar.put$TK$TV("D", C$.ONE);
C$.polar.put$TK$TV("N", C$.ONE);
C$.polar.put$TK$TV("S", C$.ONE);
C$.polar.put$TK$TV("T", C$.ONE);
C$.polar.put$TK$TV("X", C$.ONE);
C$.polar.put$TK$TV("-", C$.ONE);
C$.polar.put$TK$TV("*", C$.ONE);
C$.polar.put$TK$TV("I", C$.ZERO);
C$.polar.put$TK$TV("L", C$.ZERO);
C$.polar.put$TK$TV("V", C$.ZERO);
C$.polar.put$TK$TV("C", C$.ZERO);
C$.polar.put$TK$TV("A", C$.ZERO);
C$.polar.put$TK$TV("G", C$.ZERO);
C$.polar.put$TK$TV("M", C$.ZERO);
C$.polar.put$TK$TV("F", C$.ZERO);
C$.polar.put$TK$TV("P", C$.ZERO);
};
{
C$.small.put$TK$TV("I", C$.ZERO);
C$.small.put$TK$TV("L", C$.ZERO);
C$.small.put$TK$TV("V", C$.ONE);
C$.small.put$TK$TV("C", C$.ONE);
C$.small.put$TK$TV("A", C$.ONE);
C$.small.put$TK$TV("G", C$.ONE);
C$.small.put$TK$TV("M", C$.ZERO);
C$.small.put$TK$TV("F", C$.ZERO);
C$.small.put$TK$TV("Y", C$.ZERO);
C$.small.put$TK$TV("W", C$.ZERO);
C$.small.put$TK$TV("H", C$.ZERO);
C$.small.put$TK$TV("K", C$.ZERO);
C$.small.put$TK$TV("R", C$.ZERO);
C$.small.put$TK$TV("E", C$.ZERO);
C$.small.put$TK$TV("Q", C$.ZERO);
C$.small.put$TK$TV("D", C$.ONE);
C$.small.put$TK$TV("N", C$.ONE);
C$.small.put$TK$TV("S", C$.ONE);
C$.small.put$TK$TV("T", C$.ONE);
C$.small.put$TK$TV("P", C$.ONE);
C$.small.put$TK$TV("-", C$.ONE);
C$.small.put$TK$TV("*", C$.ONE);
};
{
C$.positive.put$TK$TV("I", C$.ZERO);
C$.positive.put$TK$TV("L", C$.ZERO);
C$.positive.put$TK$TV("V", C$.ZERO);
C$.positive.put$TK$TV("C", C$.ZERO);
C$.positive.put$TK$TV("A", C$.ZERO);
C$.positive.put$TK$TV("G", C$.ZERO);
C$.positive.put$TK$TV("M", C$.ZERO);
C$.positive.put$TK$TV("F", C$.ZERO);
C$.positive.put$TK$TV("Y", C$.ZERO);
C$.positive.put$TK$TV("W", C$.ZERO);
C$.positive.put$TK$TV("H", C$.ONE);
C$.positive.put$TK$TV("K", C$.ONE);
C$.positive.put$TK$TV("R", C$.ONE);
C$.positive.put$TK$TV("E", C$.ZERO);
C$.positive.put$TK$TV("Q", C$.ZERO);
C$.positive.put$TK$TV("D", C$.ZERO);
C$.positive.put$TK$TV("N", C$.ZERO);
C$.positive.put$TK$TV("S", C$.ZERO);
C$.positive.put$TK$TV("T", C$.ZERO);
C$.positive.put$TK$TV("P", C$.ZERO);
C$.positive.put$TK$TV("-", C$.ONE);
C$.positive.put$TK$TV("*", C$.ONE);
};
{
C$.negative.put$TK$TV("I", C$.ZERO);
C$.negative.put$TK$TV("L", C$.ZERO);
C$.negative.put$TK$TV("V", C$.ZERO);
C$.negative.put$TK$TV("C", C$.ZERO);
C$.negative.put$TK$TV("A", C$.ZERO);
C$.negative.put$TK$TV("G", C$.ZERO);
C$.negative.put$TK$TV("M", C$.ZERO);
C$.negative.put$TK$TV("F", C$.ZERO);
C$.negative.put$TK$TV("Y", C$.ZERO);
C$.negative.put$TK$TV("W", C$.ZERO);
C$.negative.put$TK$TV("H", C$.ZERO);
C$.negative.put$TK$TV("K", C$.ZERO);
C$.negative.put$TK$TV("R", C$.ZERO);
C$.negative.put$TK$TV("E", C$.ONE);
C$.negative.put$TK$TV("Q", C$.ZERO);
C$.negative.put$TK$TV("D", C$.ONE);
C$.negative.put$TK$TV("N", C$.ZERO);
C$.negative.put$TK$TV("S", C$.ZERO);
C$.negative.put$TK$TV("T", C$.ZERO);
C$.negative.put$TK$TV("P", C$.ZERO);
C$.negative.put$TK$TV("-", C$.ONE);
C$.negative.put$TK$TV("*", C$.ONE);
};
{
C$.charged.put$TK$TV("I", C$.ZERO);
C$.charged.put$TK$TV("L", C$.ZERO);
C$.charged.put$TK$TV("V", C$.ZERO);
C$.charged.put$TK$TV("C", C$.ZERO);
C$.charged.put$TK$TV("A", C$.ZERO);
C$.charged.put$TK$TV("G", C$.ZERO);
C$.charged.put$TK$TV("M", C$.ZERO);
C$.charged.put$TK$TV("F", C$.ZERO);
C$.charged.put$TK$TV("Y", C$.ZERO);
C$.charged.put$TK$TV("W", C$.ZERO);
C$.charged.put$TK$TV("H", C$.ONE);
C$.charged.put$TK$TV("K", C$.ONE);
C$.charged.put$TK$TV("R", C$.ONE);
C$.charged.put$TK$TV("E", C$.ONE);
C$.charged.put$TK$TV("Q", C$.ZERO);
C$.charged.put$TK$TV("D", C$.ONE);
C$.charged.put$TK$TV("N", C$.ZERO);
C$.charged.put$TK$TV("S", C$.ZERO);
C$.charged.put$TK$TV("T", C$.ZERO);
C$.charged.put$TK$TV("P", C$.ZERO);
C$.charged.put$TK$TV("-", C$.ONE);
C$.charged.put$TK$TV("*", C$.ONE);
};
{
C$.aromatic.put$TK$TV("I", C$.ZERO);
C$.aromatic.put$TK$TV("L", C$.ZERO);
C$.aromatic.put$TK$TV("V", C$.ZERO);
C$.aromatic.put$TK$TV("C", C$.ZERO);
C$.aromatic.put$TK$TV("A", C$.ZERO);
C$.aromatic.put$TK$TV("G", C$.ZERO);
C$.aromatic.put$TK$TV("M", C$.ZERO);
C$.aromatic.put$TK$TV("F", C$.ONE);
C$.aromatic.put$TK$TV("Y", C$.ONE);
C$.aromatic.put$TK$TV("W", C$.ONE);
C$.aromatic.put$TK$TV("H", C$.ONE);
C$.aromatic.put$TK$TV("K", C$.ZERO);
C$.aromatic.put$TK$TV("R", C$.ZERO);
C$.aromatic.put$TK$TV("E", C$.ZERO);
C$.aromatic.put$TK$TV("Q", C$.ZERO);
C$.aromatic.put$TK$TV("D", C$.ZERO);
C$.aromatic.put$TK$TV("N", C$.ZERO);
C$.aromatic.put$TK$TV("S", C$.ZERO);
C$.aromatic.put$TK$TV("T", C$.ZERO);
C$.aromatic.put$TK$TV("P", C$.ZERO);
C$.aromatic.put$TK$TV("-", C$.ONE);
C$.aromatic.put$TK$TV("*", C$.ONE);
};
{
C$.aliphatic.put$TK$TV("I", C$.ONE);
C$.aliphatic.put$TK$TV("L", C$.ONE);
C$.aliphatic.put$TK$TV("V", C$.ONE);
C$.aliphatic.put$TK$TV("C", C$.ZERO);
C$.aliphatic.put$TK$TV("A", C$.ZERO);
C$.aliphatic.put$TK$TV("G", C$.ZERO);
C$.aliphatic.put$TK$TV("M", C$.ZERO);
C$.aliphatic.put$TK$TV("F", C$.ZERO);
C$.aliphatic.put$TK$TV("Y", C$.ZERO);
C$.aliphatic.put$TK$TV("W", C$.ZERO);
C$.aliphatic.put$TK$TV("H", C$.ZERO);
C$.aliphatic.put$TK$TV("K", C$.ZERO);
C$.aliphatic.put$TK$TV("R", C$.ZERO);
C$.aliphatic.put$TK$TV("E", C$.ZERO);
C$.aliphatic.put$TK$TV("Q", C$.ZERO);
C$.aliphatic.put$TK$TV("D", C$.ZERO);
C$.aliphatic.put$TK$TV("N", C$.ZERO);
C$.aliphatic.put$TK$TV("S", C$.ZERO);
C$.aliphatic.put$TK$TV("T", C$.ZERO);
C$.aliphatic.put$TK$TV("P", C$.ZERO);
C$.aliphatic.put$TK$TV("-", C$.ONE);
C$.aliphatic.put$TK$TV("*", C$.ONE);
};
{
C$.tiny.put$TK$TV("I", C$.ZERO);
C$.tiny.put$TK$TV("L", C$.ZERO);
C$.tiny.put$TK$TV("V", C$.ZERO);
C$.tiny.put$TK$TV("C", C$.ZERO);
C$.tiny.put$TK$TV("A", C$.ONE);
C$.tiny.put$TK$TV("G", C$.ONE);
C$.tiny.put$TK$TV("M", C$.ZERO);
C$.tiny.put$TK$TV("F", C$.ZERO);
C$.tiny.put$TK$TV("Y", C$.ZERO);
C$.tiny.put$TK$TV("W", C$.ZERO);
C$.tiny.put$TK$TV("H", C$.ZERO);
C$.tiny.put$TK$TV("K", C$.ZERO);
C$.tiny.put$TK$TV("R", C$.ZERO);
C$.tiny.put$TK$TV("E", C$.ZERO);
C$.tiny.put$TK$TV("Q", C$.ZERO);
C$.tiny.put$TK$TV("D", C$.ZERO);
C$.tiny.put$TK$TV("N", C$.ZERO);
C$.tiny.put$TK$TV("S", C$.ONE);
C$.tiny.put$TK$TV("T", C$.ZERO);
C$.tiny.put$TK$TV("P", C$.ZERO);
C$.tiny.put$TK$TV("-", C$.ONE);
C$.tiny.put$TK$TV("*", C$.ONE);
};
{
C$.proline.put$TK$TV("I", C$.ZERO);
C$.proline.put$TK$TV("L", C$.ZERO);
C$.proline.put$TK$TV("V", C$.ZERO);
C$.proline.put$TK$TV("C", C$.ZERO);
C$.proline.put$TK$TV("A", C$.ZERO);
C$.proline.put$TK$TV("G", C$.ZERO);
C$.proline.put$TK$TV("M", C$.ZERO);
C$.proline.put$TK$TV("F", C$.ZERO);
C$.proline.put$TK$TV("Y", C$.ZERO);
C$.proline.put$TK$TV("W", C$.ZERO);
C$.proline.put$TK$TV("H", C$.ZERO);
C$.proline.put$TK$TV("K", C$.ZERO);
C$.proline.put$TK$TV("R", C$.ZERO);
C$.proline.put$TK$TV("E", C$.ZERO);
C$.proline.put$TK$TV("Q", C$.ZERO);
C$.proline.put$TK$TV("D", C$.ZERO);
C$.proline.put$TK$TV("N", C$.ZERO);
C$.proline.put$TK$TV("S", C$.ZERO);
C$.proline.put$TK$TV("T", C$.ZERO);
C$.proline.put$TK$TV("P", C$.ONE);
C$.proline.put$TK$TV("-", C$.ONE);
C$.proline.put$TK$TV("*", C$.ONE);
};
{
C$.propHash.put$TK$TV("hydrophobic", C$.hydrophobic);
C$.propHash.put$TK$TV("small", C$.small);
C$.propHash.put$TK$TV("positive", C$.positive);
C$.propHash.put$TK$TV("negative", C$.negative);
C$.propHash.put$TK$TV("charged", C$.charged);
C$.propHash.put$TK$TV("aromatic", C$.aromatic);
C$.propHash.put$TK$TV("aliphatic", C$.aliphatic);
C$.propHash.put$TK$TV("tiny", C$.tiny);
C$.propHash.put$TK$TV("proline", C$.proline);
C$.propHash.put$TK$TV("polar", C$.polar);
};
{
var propMatrixF=Clazz.array(Integer.TYPE, [23, 23]);
var propMatrixPos=Clazz.array(Integer.TYPE, [23, 23]);
var propMatrixEpos=Clazz.array(Integer.TYPE, [23, 23]);
for (var i=0; i < 23; i++) {
var maxF=0;
var maxP=0;
var maxEP=0;
var ic="";
if (C$.aa.length > i) {
ic += C$.aa[i];
} else {
ic="-";
}for (var j=i + 1; j < 23; j++) {
var jc="";
if (C$.aa.length > j) {
jc += C$.aa[j];
} else {
jc="-";
}propMatrixF[i][j]=0;
propMatrixPos[i][j]=0;
propMatrixEpos[i][j]=0;
for (var ph, $ph = C$.propHash.keySet$().iterator$(); $ph.hasNext$()&&((ph=($ph.next$())),1);) {
var pph=C$.propHash.get$O(ph);
if (pph.get$O(ic) != null  && pph.get$O(jc) != null  ) {
var icp=pph.get$O(ic).intValue$();
var jcp=pph.get$O(jc).intValue$();
propMatrixPos[i][j]+=icp == jcp && icp > 0  ? 2 : 0;
propMatrixPos[j][i]+=icp == jcp && icp > 0  ? 2 : 0;
propMatrixF[i][j]+=icp == jcp ? 2 : 0;
propMatrixF[j][i]+=icp == jcp ? 2 : 0;
propMatrixEpos[i][j]+=icp == jcp ? (1 + icp * 2) : 0;
propMatrixEpos[j][i]+=icp == jcp ? (1 + icp * 2) : 0;
}}
if (maxF < propMatrixF[i][j]) {
maxF=propMatrixF[i][j];
}if (maxP < propMatrixPos[i][j]) {
maxP=propMatrixPos[i][j];
}if (maxEP < propMatrixEpos[i][j]) {
maxEP=propMatrixEpos[i][j];
}}
propMatrixF[i][i]=maxF;
propMatrixPos[i][i]=maxP;
propMatrixEpos[i][i]=maxEP;
}
};
{
C$.toDssp3State=Clazz.array(Character.TYPE, [9]);
$I$(3).fill$CA$C(C$.toDssp3State, " ");
C$.toDssp3State[1]="E";
C$.toDssp3State[4]="E";
C$.toDssp3State[6]="H";
C$.toDssp3State[7]="H";
C$.toDssp3State[8]="H";
};
{
C$.modifications.put$TK$TV("MSE", "MET");
C$.modifications.put$TK$TV("00C", "CYS");
C$.modifications.put$TK$TV("01W", "XAA");
C$.modifications.put$TK$TV("02K", "ALA");
C$.modifications.put$TK$TV("03Y", "CYS");
C$.modifications.put$TK$TV("07O", "CYS");
C$.modifications.put$TK$TV("08P", "CYS");
C$.modifications.put$TK$TV("0A0", "ASP");
C$.modifications.put$TK$TV("0A1", "TYR");
C$.modifications.put$TK$TV("0A2", "LYS");
C$.modifications.put$TK$TV("0A8", "CYS");
C$.modifications.put$TK$TV("0AA", "VAL");
C$.modifications.put$TK$TV("0AB", "VAL");
C$.modifications.put$TK$TV("0AC", "GLY");
C$.modifications.put$TK$TV("0AD", "GLY");
C$.modifications.put$TK$TV("0AF", "TRP");
C$.modifications.put$TK$TV("0AG", "LEU");
C$.modifications.put$TK$TV("0AH", "SER");
C$.modifications.put$TK$TV("0AK", "ASP");
C$.modifications.put$TK$TV("0AM", "ALA");
C$.modifications.put$TK$TV("0AP", "CYS");
C$.modifications.put$TK$TV("0AU", "UR3");
C$.modifications.put$TK$TV("0AV", "ALA");
C$.modifications.put$TK$TV("0AZ", "PRO");
C$.modifications.put$TK$TV("0BN", "PHE");
C$.modifications.put$TK$TV("0C ", "CYS");
C$.modifications.put$TK$TV("0CS", "ALA");
C$.modifications.put$TK$TV("0DC", "CYS");
C$.modifications.put$TK$TV("0DG", "GLY");
C$.modifications.put$TK$TV("0DT", "THR");
C$.modifications.put$TK$TV("0FL", "ALA");
C$.modifications.put$TK$TV("0G ", "GLY");
C$.modifications.put$TK$TV("0NC", "ALA");
C$.modifications.put$TK$TV("0SP", "ALA");
C$.modifications.put$TK$TV("0U ", "UR3");
C$.modifications.put$TK$TV("0YG", "YG");
C$.modifications.put$TK$TV("10C", "CYS");
C$.modifications.put$TK$TV("125", "UR3");
C$.modifications.put$TK$TV("126", "UR3");
C$.modifications.put$TK$TV("127", "UR3");
C$.modifications.put$TK$TV("128", "ASN");
C$.modifications.put$TK$TV("12A", "ALA");
C$.modifications.put$TK$TV("143", "CYS");
C$.modifications.put$TK$TV("175", "ASG");
C$.modifications.put$TK$TV("193", "XAA");
C$.modifications.put$TK$TV("1AP", "ALA");
C$.modifications.put$TK$TV("1MA", "ALA");
C$.modifications.put$TK$TV("1MG", "GLY");
C$.modifications.put$TK$TV("1PA", "PHE");
C$.modifications.put$TK$TV("1PI", "ALA");
C$.modifications.put$TK$TV("1PR", "ASN");
C$.modifications.put$TK$TV("1SC", "CYS");
C$.modifications.put$TK$TV("1TQ", "TRP");
C$.modifications.put$TK$TV("1TY", "TYR");
C$.modifications.put$TK$TV("1X6", "SER");
C$.modifications.put$TK$TV("200", "PHE");
C$.modifications.put$TK$TV("23F", "PHE");
C$.modifications.put$TK$TV("23S", "XAA");
C$.modifications.put$TK$TV("26B", "THR");
C$.modifications.put$TK$TV("2AD", "XAA");
C$.modifications.put$TK$TV("2AG", "ALA");
C$.modifications.put$TK$TV("2AO", "XAA");
C$.modifications.put$TK$TV("2AR", "ALA");
C$.modifications.put$TK$TV("2AS", "XAA");
C$.modifications.put$TK$TV("2AT", "THR");
C$.modifications.put$TK$TV("2AU", "UR3");
C$.modifications.put$TK$TV("2BD", "ILE");
C$.modifications.put$TK$TV("2BT", "THR");
C$.modifications.put$TK$TV("2BU", "ALA");
C$.modifications.put$TK$TV("2CO", "CYS");
C$.modifications.put$TK$TV("2DA", "ALA");
C$.modifications.put$TK$TV("2DF", "ASN");
C$.modifications.put$TK$TV("2DM", "ASN");
C$.modifications.put$TK$TV("2DO", "XAA");
C$.modifications.put$TK$TV("2DT", "THR");
C$.modifications.put$TK$TV("2EG", "GLY");
C$.modifications.put$TK$TV("2FE", "ASN");
C$.modifications.put$TK$TV("2FI", "ASN");
C$.modifications.put$TK$TV("2FM", "MET");
C$.modifications.put$TK$TV("2GT", "THR");
C$.modifications.put$TK$TV("2HF", "HIS");
C$.modifications.put$TK$TV("2LU", "LEU");
C$.modifications.put$TK$TV("2MA", "ALA");
C$.modifications.put$TK$TV("2MG", "GLY");
C$.modifications.put$TK$TV("2ML", "LEU");
C$.modifications.put$TK$TV("2MR", "ARG");
C$.modifications.put$TK$TV("2MT", "PRO");
C$.modifications.put$TK$TV("2MU", "UR3");
C$.modifications.put$TK$TV("2NT", "THR");
C$.modifications.put$TK$TV("2OM", "UR3");
C$.modifications.put$TK$TV("2OT", "THR");
C$.modifications.put$TK$TV("2PI", "XAA");
C$.modifications.put$TK$TV("2PR", "GLY");
C$.modifications.put$TK$TV("2SA", "ASN");
C$.modifications.put$TK$TV("2SI", "XAA");
C$.modifications.put$TK$TV("2ST", "THR");
C$.modifications.put$TK$TV("2TL", "THR");
C$.modifications.put$TK$TV("2TY", "TYR");
C$.modifications.put$TK$TV("2VA", "VAL");
C$.modifications.put$TK$TV("2XA", "CYS");
C$.modifications.put$TK$TV("32S", "XAA");
C$.modifications.put$TK$TV("32T", "XAA");
C$.modifications.put$TK$TV("3AH", "HIS");
C$.modifications.put$TK$TV("3AR", "XAA");
C$.modifications.put$TK$TV("3CF", "PHE");
C$.modifications.put$TK$TV("3DA", "ALA");
C$.modifications.put$TK$TV("3DR", "ASN");
C$.modifications.put$TK$TV("3GA", "ALA");
C$.modifications.put$TK$TV("3MD", "ASP");
C$.modifications.put$TK$TV("3ME", "UR3");
C$.modifications.put$TK$TV("3NF", "TYR");
C$.modifications.put$TK$TV("3QN", "LYS");
C$.modifications.put$TK$TV("3TY", "XAA");
C$.modifications.put$TK$TV("3XH", "GLY");
C$.modifications.put$TK$TV("4AC", "ASN");
C$.modifications.put$TK$TV("4BF", "TYR");
C$.modifications.put$TK$TV("4CF", "PHE");
C$.modifications.put$TK$TV("4CY", "MET");
C$.modifications.put$TK$TV("4DP", "TRP");
C$.modifications.put$TK$TV("4F3", "GYG");
C$.modifications.put$TK$TV("4FB", "PRO");
C$.modifications.put$TK$TV("4FW", "TRP");
C$.modifications.put$TK$TV("4HT", "TRP");
C$.modifications.put$TK$TV("4IN", "TRP");
C$.modifications.put$TK$TV("4MF", "ASN");
C$.modifications.put$TK$TV("4MM", "XAA");
C$.modifications.put$TK$TV("4OC", "CYS");
C$.modifications.put$TK$TV("4PC", "CYS");
C$.modifications.put$TK$TV("4PD", "CYS");
C$.modifications.put$TK$TV("4PE", "CYS");
C$.modifications.put$TK$TV("4PH", "PHE");
C$.modifications.put$TK$TV("4SC", "CYS");
C$.modifications.put$TK$TV("4SU", "UR3");
C$.modifications.put$TK$TV("4TA", "ASN");
C$.modifications.put$TK$TV("4U7", "ALA");
C$.modifications.put$TK$TV("56A", "HIS");
C$.modifications.put$TK$TV("5AA", "ALA");
C$.modifications.put$TK$TV("5AB", "ALA");
C$.modifications.put$TK$TV("5AT", "THR");
C$.modifications.put$TK$TV("5BU", "UR3");
C$.modifications.put$TK$TV("5CG", "GLY");
C$.modifications.put$TK$TV("5CM", "CYS");
C$.modifications.put$TK$TV("5CS", "CYS");
C$.modifications.put$TK$TV("5FA", "ALA");
C$.modifications.put$TK$TV("5FC", "CYS");
C$.modifications.put$TK$TV("5FU", "UR3");
C$.modifications.put$TK$TV("5HP", "GLU");
C$.modifications.put$TK$TV("5HT", "THR");
C$.modifications.put$TK$TV("5HU", "UR3");
C$.modifications.put$TK$TV("5IC", "CYS");
C$.modifications.put$TK$TV("5IT", "THR");
C$.modifications.put$TK$TV("5IU", "UR3");
C$.modifications.put$TK$TV("5MC", "CYS");
C$.modifications.put$TK$TV("5MD", "ASN");
C$.modifications.put$TK$TV("5MU", "UR3");
C$.modifications.put$TK$TV("5NC", "CYS");
C$.modifications.put$TK$TV("5PC", "CYS");
C$.modifications.put$TK$TV("5PY", "THR");
C$.modifications.put$TK$TV("5SE", "UR3");
C$.modifications.put$TK$TV("5ZA", "TWG");
C$.modifications.put$TK$TV("64T", "THR");
C$.modifications.put$TK$TV("6CL", "LYS");
C$.modifications.put$TK$TV("6CT", "THR");
C$.modifications.put$TK$TV("6CW", "TRP");
C$.modifications.put$TK$TV("6HA", "ALA");
C$.modifications.put$TK$TV("6HC", "CYS");
C$.modifications.put$TK$TV("6HG", "GLY");
C$.modifications.put$TK$TV("6HN", "LYS");
C$.modifications.put$TK$TV("6HT", "THR");
C$.modifications.put$TK$TV("6IA", "ALA");
C$.modifications.put$TK$TV("6MA", "ALA");
C$.modifications.put$TK$TV("6MC", "ALA");
C$.modifications.put$TK$TV("6MI", "ASN");
C$.modifications.put$TK$TV("6MT", "ALA");
C$.modifications.put$TK$TV("6MZ", "ASN");
C$.modifications.put$TK$TV("6OG", "GLY");
C$.modifications.put$TK$TV("70U", "UR3");
C$.modifications.put$TK$TV("7DA", "ALA");
C$.modifications.put$TK$TV("7GU", "GLY");
C$.modifications.put$TK$TV("7JA", "ILE");
C$.modifications.put$TK$TV("7MG", "GLY");
C$.modifications.put$TK$TV("8AN", "ALA");
C$.modifications.put$TK$TV("8FG", "GLY");
C$.modifications.put$TK$TV("8MG", "GLY");
C$.modifications.put$TK$TV("8OG", "GLY");
C$.modifications.put$TK$TV("9NE", "GLU");
C$.modifications.put$TK$TV("9NF", "PHE");
C$.modifications.put$TK$TV("9NR", "ARG");
C$.modifications.put$TK$TV("9NV", "VAL");
C$.modifications.put$TK$TV("A  ", "ALA");
C$.modifications.put$TK$TV("A1P", "ASN");
C$.modifications.put$TK$TV("A23", "ALA");
C$.modifications.put$TK$TV("A2L", "ALA");
C$.modifications.put$TK$TV("A2M", "ALA");
C$.modifications.put$TK$TV("A34", "ALA");
C$.modifications.put$TK$TV("A35", "ALA");
C$.modifications.put$TK$TV("A38", "ALA");
C$.modifications.put$TK$TV("A39", "ALA");
C$.modifications.put$TK$TV("A3A", "ALA");
C$.modifications.put$TK$TV("A3P", "ALA");
C$.modifications.put$TK$TV("A40", "ALA");
C$.modifications.put$TK$TV("A43", "ALA");
C$.modifications.put$TK$TV("A44", "ALA");
C$.modifications.put$TK$TV("A47", "ALA");
C$.modifications.put$TK$TV("A5L", "ALA");
C$.modifications.put$TK$TV("A5M", "CYS");
C$.modifications.put$TK$TV("A5N", "ASN");
C$.modifications.put$TK$TV("A5O", "ALA");
C$.modifications.put$TK$TV("A66", "XAA");
C$.modifications.put$TK$TV("AA3", "ALA");
C$.modifications.put$TK$TV("AA4", "ALA");
C$.modifications.put$TK$TV("AAR", "ARG");
C$.modifications.put$TK$TV("AB7", "XAA");
C$.modifications.put$TK$TV("ABA", "ALA");
C$.modifications.put$TK$TV("ABR", "ALA");
C$.modifications.put$TK$TV("ABS", "ALA");
C$.modifications.put$TK$TV("ABT", "ASN");
C$.modifications.put$TK$TV("ACB", "ASP");
C$.modifications.put$TK$TV("ACL", "ARG");
C$.modifications.put$TK$TV("AD2", "ALA");
C$.modifications.put$TK$TV("ADD", "XAA");
C$.modifications.put$TK$TV("ADX", "ASN");
C$.modifications.put$TK$TV("AEA", "XAA");
C$.modifications.put$TK$TV("AEI", "ASP");
C$.modifications.put$TK$TV("AET", "ALA");
C$.modifications.put$TK$TV("AFA", "ASN");
C$.modifications.put$TK$TV("AFF", "ASN");
C$.modifications.put$TK$TV("AFG", "GLY");
C$.modifications.put$TK$TV("AGM", "ARG");
C$.modifications.put$TK$TV("AGT", "CYS");
C$.modifications.put$TK$TV("AHB", "ASN");
C$.modifications.put$TK$TV("AHH", "XAA");
C$.modifications.put$TK$TV("AHO", "ALA");
C$.modifications.put$TK$TV("AHP", "ALA");
C$.modifications.put$TK$TV("AHS", "XAA");
C$.modifications.put$TK$TV("AHT", "XAA");
C$.modifications.put$TK$TV("AIB", "ALA");
C$.modifications.put$TK$TV("AKL", "ASP");
C$.modifications.put$TK$TV("AKZ", "ASP");
C$.modifications.put$TK$TV("ALA", "ALA");
C$.modifications.put$TK$TV("ALC", "ALA");
C$.modifications.put$TK$TV("ALM", "ALA");
C$.modifications.put$TK$TV("ALN", "ALA");
C$.modifications.put$TK$TV("ALO", "THR");
C$.modifications.put$TK$TV("ALQ", "XAA");
C$.modifications.put$TK$TV("ALS", "ALA");
C$.modifications.put$TK$TV("ALT", "ALA");
C$.modifications.put$TK$TV("ALV", "ALA");
C$.modifications.put$TK$TV("ALY", "LYS");
C$.modifications.put$TK$TV("AN8", "ALA");
C$.modifications.put$TK$TV("AP7", "ALA");
C$.modifications.put$TK$TV("APE", "XAA");
C$.modifications.put$TK$TV("APH", "ALA");
C$.modifications.put$TK$TV("API", "LYS");
C$.modifications.put$TK$TV("APK", "LYS");
C$.modifications.put$TK$TV("APM", "XAA");
C$.modifications.put$TK$TV("APP", "XAA");
C$.modifications.put$TK$TV("AR2", "ARG");
C$.modifications.put$TK$TV("AR4", "GLU");
C$.modifications.put$TK$TV("AR7", "ARG");
C$.modifications.put$TK$TV("ARG", "ARG");
C$.modifications.put$TK$TV("ARM", "ARG");
C$.modifications.put$TK$TV("ARO", "ARG");
C$.modifications.put$TK$TV("ARV", "XAA");
C$.modifications.put$TK$TV("AS ", "ALA");
C$.modifications.put$TK$TV("AS2", "ASP");
C$.modifications.put$TK$TV("AS9", "XAA");
C$.modifications.put$TK$TV("ASA", "ASP");
C$.modifications.put$TK$TV("ASB", "ASP");
C$.modifications.put$TK$TV("ASI", "ASP");
C$.modifications.put$TK$TV("ASK", "ASP");
C$.modifications.put$TK$TV("ASL", "ASP");
C$.modifications.put$TK$TV("ASM", "XAA");
C$.modifications.put$TK$TV("ASN", "ASN");
C$.modifications.put$TK$TV("ASP", "ASP");
C$.modifications.put$TK$TV("ASQ", "ASP");
C$.modifications.put$TK$TV("ASU", "ASN");
C$.modifications.put$TK$TV("ASX", "ASX");
C$.modifications.put$TK$TV("ATD", "THR");
C$.modifications.put$TK$TV("ATL", "THR");
C$.modifications.put$TK$TV("ATM", "THR");
C$.modifications.put$TK$TV("AVC", "ALA");
C$.modifications.put$TK$TV("AVN", "XAA");
C$.modifications.put$TK$TV("AYA", "ALA");
C$.modifications.put$TK$TV("AYG", "AYG");
C$.modifications.put$TK$TV("AZK", "LYS");
C$.modifications.put$TK$TV("AZS", "SER");
C$.modifications.put$TK$TV("AZY", "TYR");
C$.modifications.put$TK$TV("B1F", "PHE");
C$.modifications.put$TK$TV("B1P", "ASN");
C$.modifications.put$TK$TV("B2A", "ALA");
C$.modifications.put$TK$TV("B2F", "PHE");
C$.modifications.put$TK$TV("B2I", "ILE");
C$.modifications.put$TK$TV("B2V", "VAL");
C$.modifications.put$TK$TV("B3A", "ALA");
C$.modifications.put$TK$TV("B3D", "ASP");
C$.modifications.put$TK$TV("B3E", "GLU");
C$.modifications.put$TK$TV("B3K", "LYS");
C$.modifications.put$TK$TV("B3L", "XAA");
C$.modifications.put$TK$TV("B3M", "XAA");
C$.modifications.put$TK$TV("B3Q", "XAA");
C$.modifications.put$TK$TV("B3S", "SER");
C$.modifications.put$TK$TV("B3T", "XAA");
C$.modifications.put$TK$TV("B3U", "HIS");
C$.modifications.put$TK$TV("B3X", "ASN");
C$.modifications.put$TK$TV("B3Y", "TYR");
C$.modifications.put$TK$TV("BB6", "CYS");
C$.modifications.put$TK$TV("BB7", "CYS");
C$.modifications.put$TK$TV("BB8", "PHE");
C$.modifications.put$TK$TV("BB9", "CYS");
C$.modifications.put$TK$TV("BBC", "CYS");
C$.modifications.put$TK$TV("BCS", "CYS");
C$.modifications.put$TK$TV("BE2", "XAA");
C$.modifications.put$TK$TV("BFD", "ASP");
C$.modifications.put$TK$TV("BG1", "SER");
C$.modifications.put$TK$TV("BGM", "GLY");
C$.modifications.put$TK$TV("BH2", "ASP");
C$.modifications.put$TK$TV("BHD", "ASP");
C$.modifications.put$TK$TV("BIF", "PHE");
C$.modifications.put$TK$TV("BIL", "XAA");
C$.modifications.put$TK$TV("BIU", "ILE");
C$.modifications.put$TK$TV("BJH", "XAA");
C$.modifications.put$TK$TV("BLE", "LEU");
C$.modifications.put$TK$TV("BLY", "LYS");
C$.modifications.put$TK$TV("BMP", "ASN");
C$.modifications.put$TK$TV("BMT", "THR");
C$.modifications.put$TK$TV("BNN", "PHE");
C$.modifications.put$TK$TV("BNO", "XAA");
C$.modifications.put$TK$TV("BOE", "THR");
C$.modifications.put$TK$TV("BOR", "ARG");
C$.modifications.put$TK$TV("BPE", "CYS");
C$.modifications.put$TK$TV("BRU", "UR3");
C$.modifications.put$TK$TV("BSE", "SER");
C$.modifications.put$TK$TV("BT5", "ASN");
C$.modifications.put$TK$TV("BTA", "LEU");
C$.modifications.put$TK$TV("BTC", "CYS");
C$.modifications.put$TK$TV("BTR", "TRP");
C$.modifications.put$TK$TV("BUC", "CYS");
C$.modifications.put$TK$TV("BUG", "VAL");
C$.modifications.put$TK$TV("BVP", "UR3");
C$.modifications.put$TK$TV("BZG", "ASN");
C$.modifications.put$TK$TV("C  ", "CYS");
C$.modifications.put$TK$TV("C12", "TYG");
C$.modifications.put$TK$TV("C1X", "LYS");
C$.modifications.put$TK$TV("C25", "CYS");
C$.modifications.put$TK$TV("C2L", "CYS");
C$.modifications.put$TK$TV("C2S", "CYS");
C$.modifications.put$TK$TV("C31", "CYS");
C$.modifications.put$TK$TV("C32", "CYS");
C$.modifications.put$TK$TV("C34", "CYS");
C$.modifications.put$TK$TV("C36", "CYS");
C$.modifications.put$TK$TV("C37", "CYS");
C$.modifications.put$TK$TV("C38", "CYS");
C$.modifications.put$TK$TV("C3Y", "CYS");
C$.modifications.put$TK$TV("C42", "CYS");
C$.modifications.put$TK$TV("C43", "CYS");
C$.modifications.put$TK$TV("C45", "CYS");
C$.modifications.put$TK$TV("C46", "CYS");
C$.modifications.put$TK$TV("C49", "CYS");
C$.modifications.put$TK$TV("C4R", "CYS");
C$.modifications.put$TK$TV("C4S", "CYS");
C$.modifications.put$TK$TV("C5C", "CYS");
C$.modifications.put$TK$TV("C66", "XAA");
C$.modifications.put$TK$TV("C6C", "CYS");
C$.modifications.put$TK$TV("C99", "TFG");
C$.modifications.put$TK$TV("CAF", "CYS");
C$.modifications.put$TK$TV("CAL", "XAA");
C$.modifications.put$TK$TV("CAR", "CYS");
C$.modifications.put$TK$TV("CAS", "CYS");
C$.modifications.put$TK$TV("CAV", "XAA");
C$.modifications.put$TK$TV("CAY", "CYS");
C$.modifications.put$TK$TV("CB2", "CYS");
C$.modifications.put$TK$TV("CBR", "CYS");
C$.modifications.put$TK$TV("CBV", "CYS");
C$.modifications.put$TK$TV("CCC", "CYS");
C$.modifications.put$TK$TV("CCL", "LYS");
C$.modifications.put$TK$TV("CCS", "CYS");
C$.modifications.put$TK$TV("CCY", "CYG");
C$.modifications.put$TK$TV("CDE", "XAA");
C$.modifications.put$TK$TV("CDV", "XAA");
C$.modifications.put$TK$TV("CDW", "CYS");
C$.modifications.put$TK$TV("CEA", "CYS");
C$.modifications.put$TK$TV("CFL", "CYS");
C$.modifications.put$TK$TV("CFY", "FCYG");
C$.modifications.put$TK$TV("CG1", "GLY");
C$.modifications.put$TK$TV("CGA", "GLU");
C$.modifications.put$TK$TV("CGU", "GLU");
C$.modifications.put$TK$TV("CH ", "CYS");
C$.modifications.put$TK$TV("CH6", "MYG");
C$.modifications.put$TK$TV("CH7", "KYG");
C$.modifications.put$TK$TV("CHF", "XAA");
C$.modifications.put$TK$TV("CHG", "XAA");
C$.modifications.put$TK$TV("CHP", "GLY");
C$.modifications.put$TK$TV("CHS", "XAA");
C$.modifications.put$TK$TV("CIR", "ARG");
C$.modifications.put$TK$TV("CJO", "GYG");
C$.modifications.put$TK$TV("CLE", "LEU");
C$.modifications.put$TK$TV("CLG", "LYS");
C$.modifications.put$TK$TV("CLH", "LYS");
C$.modifications.put$TK$TV("CLV", "AFG");
C$.modifications.put$TK$TV("CM0", "ASN");
C$.modifications.put$TK$TV("CME", "CYS");
C$.modifications.put$TK$TV("CMH", "CYS");
C$.modifications.put$TK$TV("CML", "CYS");
C$.modifications.put$TK$TV("CMR", "CYS");
C$.modifications.put$TK$TV("CMT", "CYS");
C$.modifications.put$TK$TV("CNU", "UR3");
C$.modifications.put$TK$TV("CP1", "CYS");
C$.modifications.put$TK$TV("CPC", "XAA");
C$.modifications.put$TK$TV("CPI", "XAA");
C$.modifications.put$TK$TV("CQR", "GYG");
C$.modifications.put$TK$TV("CR0", "TLG");
C$.modifications.put$TK$TV("CR2", "GYG");
C$.modifications.put$TK$TV("CR5", "GLY");
C$.modifications.put$TK$TV("CR7", "KYG");
C$.modifications.put$TK$TV("CR8", "HYG");
C$.modifications.put$TK$TV("CRF", "TWG");
C$.modifications.put$TK$TV("CRG", "THG");
C$.modifications.put$TK$TV("CRK", "MYG");
C$.modifications.put$TK$TV("CRO", "GYG");
C$.modifications.put$TK$TV("CRQ", "QYG");
C$.modifications.put$TK$TV("CRU", "EYG");
C$.modifications.put$TK$TV("CRW", "ASG");
C$.modifications.put$TK$TV("CRX", "ASG");
C$.modifications.put$TK$TV("CS0", "CYS");
C$.modifications.put$TK$TV("CS1", "CYS");
C$.modifications.put$TK$TV("CS3", "CYS");
C$.modifications.put$TK$TV("CS4", "CYS");
C$.modifications.put$TK$TV("CS8", "ASN");
C$.modifications.put$TK$TV("CSA", "CYS");
C$.modifications.put$TK$TV("CSB", "CYS");
C$.modifications.put$TK$TV("CSD", "CYS");
C$.modifications.put$TK$TV("CSE", "CYS");
C$.modifications.put$TK$TV("CSF", "CYS");
C$.modifications.put$TK$TV("CSH", "SHG");
C$.modifications.put$TK$TV("CSI", "GLY");
C$.modifications.put$TK$TV("CSJ", "CYS");
C$.modifications.put$TK$TV("CSL", "CYS");
C$.modifications.put$TK$TV("CSO", "CYS");
C$.modifications.put$TK$TV("CSP", "CYS");
C$.modifications.put$TK$TV("CSR", "CYS");
C$.modifications.put$TK$TV("CSS", "CYS");
C$.modifications.put$TK$TV("CSU", "CYS");
C$.modifications.put$TK$TV("CSW", "CYS");
C$.modifications.put$TK$TV("CSX", "CYS");
C$.modifications.put$TK$TV("CSY", "SYG");
C$.modifications.put$TK$TV("CSZ", "CYS");
C$.modifications.put$TK$TV("CTE", "TRP");
C$.modifications.put$TK$TV("CTG", "THR");
C$.modifications.put$TK$TV("CTH", "THR");
C$.modifications.put$TK$TV("CUC", "XAA");
C$.modifications.put$TK$TV("CWR", "SER");
C$.modifications.put$TK$TV("CXM", "MET");
C$.modifications.put$TK$TV("CY0", "CYS");
C$.modifications.put$TK$TV("CY1", "CYS");
C$.modifications.put$TK$TV("CY3", "CYS");
C$.modifications.put$TK$TV("CY4", "CYS");
C$.modifications.put$TK$TV("CYA", "CYS");
C$.modifications.put$TK$TV("CYD", "CYS");
C$.modifications.put$TK$TV("CYF", "CYS");
C$.modifications.put$TK$TV("CYG", "CYS");
C$.modifications.put$TK$TV("CYJ", "XAA");
C$.modifications.put$TK$TV("CYM", "CYS");
C$.modifications.put$TK$TV("CYQ", "CYS");
C$.modifications.put$TK$TV("CYR", "CYS");
C$.modifications.put$TK$TV("CYS", "CYS");
C$.modifications.put$TK$TV("CZ2", "CYS");
C$.modifications.put$TK$TV("CZO", "GYG");
C$.modifications.put$TK$TV("CZZ", "CYS");
C$.modifications.put$TK$TV("D11", "THR");
C$.modifications.put$TK$TV("D1P", "ASN");
C$.modifications.put$TK$TV("D3 ", "ASN");
C$.modifications.put$TK$TV("D33", "ASN");
C$.modifications.put$TK$TV("D3P", "GLY");
C$.modifications.put$TK$TV("D3T", "THR");
C$.modifications.put$TK$TV("D4M", "THR");
C$.modifications.put$TK$TV("D4P", "XAA");
C$.modifications.put$TK$TV("DA ", "ALA");
C$.modifications.put$TK$TV("DA2", "XAA");
C$.modifications.put$TK$TV("DAB", "ALA");
C$.modifications.put$TK$TV("DAH", "PHE");
C$.modifications.put$TK$TV("DAL", "ALA");
C$.modifications.put$TK$TV("DAR", "ARG");
C$.modifications.put$TK$TV("DAS", "ASP");
C$.modifications.put$TK$TV("DBB", "THR");
C$.modifications.put$TK$TV("DBM", "ASN");
C$.modifications.put$TK$TV("DBS", "SER");
C$.modifications.put$TK$TV("DBU", "THR");
C$.modifications.put$TK$TV("DBY", "TYR");
C$.modifications.put$TK$TV("DBZ", "ALA");
C$.modifications.put$TK$TV("DC ", "CYS");
C$.modifications.put$TK$TV("DC2", "CYS");
C$.modifications.put$TK$TV("DCG", "GLY");
C$.modifications.put$TK$TV("DCI", "XAA");
C$.modifications.put$TK$TV("DCL", "XAA");
C$.modifications.put$TK$TV("DCT", "CYS");
C$.modifications.put$TK$TV("DCY", "CYS");
C$.modifications.put$TK$TV("DDE", "HIS");
C$.modifications.put$TK$TV("DDG", "GLY");
C$.modifications.put$TK$TV("DDN", "UR3");
C$.modifications.put$TK$TV("DDX", "ASN");
C$.modifications.put$TK$TV("DFC", "CYS");
C$.modifications.put$TK$TV("DFG", "GLY");
C$.modifications.put$TK$TV("DFI", "XAA");
C$.modifications.put$TK$TV("DFO", "XAA");
C$.modifications.put$TK$TV("DFT", "ASN");
C$.modifications.put$TK$TV("DG ", "GLY");
C$.modifications.put$TK$TV("DGH", "GLY");
C$.modifications.put$TK$TV("DGI", "GLY");
C$.modifications.put$TK$TV("DGL", "GLU");
C$.modifications.put$TK$TV("DGN", "GLN");
C$.modifications.put$TK$TV("DHA", "SER");
C$.modifications.put$TK$TV("DHI", "HIS");
C$.modifications.put$TK$TV("DHL", "XAA");
C$.modifications.put$TK$TV("DHN", "VAL");
C$.modifications.put$TK$TV("DHP", "XAA");
C$.modifications.put$TK$TV("DHU", "UR3");
C$.modifications.put$TK$TV("DHV", "VAL");
C$.modifications.put$TK$TV("DI ", "ILE");
C$.modifications.put$TK$TV("DIL", "ILE");
C$.modifications.put$TK$TV("DIR", "ARG");
C$.modifications.put$TK$TV("DIV", "VAL");
C$.modifications.put$TK$TV("DLE", "LEU");
C$.modifications.put$TK$TV("DLS", "LYS");
C$.modifications.put$TK$TV("DLY", "LYS");
C$.modifications.put$TK$TV("DM0", "LYS");
C$.modifications.put$TK$TV("DMH", "ASN");
C$.modifications.put$TK$TV("DMK", "ASP");
C$.modifications.put$TK$TV("DMT", "XAA");
C$.modifications.put$TK$TV("DN ", "ASN");
C$.modifications.put$TK$TV("DNE", "LEU");
C$.modifications.put$TK$TV("DNG", "LEU");
C$.modifications.put$TK$TV("DNL", "LYS");
C$.modifications.put$TK$TV("DNM", "LEU");
C$.modifications.put$TK$TV("DNP", "ALA");
C$.modifications.put$TK$TV("DNR", "CYS");
C$.modifications.put$TK$TV("DNS", "LYS");
C$.modifications.put$TK$TV("DOA", "XAA");
C$.modifications.put$TK$TV("DOC", "CYS");
C$.modifications.put$TK$TV("DOH", "ASP");
C$.modifications.put$TK$TV("DON", "LEU");
C$.modifications.put$TK$TV("DPB", "THR");
C$.modifications.put$TK$TV("DPH", "PHE");
C$.modifications.put$TK$TV("DPL", "PRO");
C$.modifications.put$TK$TV("DPP", "ALA");
C$.modifications.put$TK$TV("DPQ", "TYR");
C$.modifications.put$TK$TV("DPR", "PRO");
C$.modifications.put$TK$TV("DPY", "ASN");
C$.modifications.put$TK$TV("DRM", "UR3");
C$.modifications.put$TK$TV("DRP", "ASN");
C$.modifications.put$TK$TV("DRT", "THR");
C$.modifications.put$TK$TV("DRZ", "ASN");
C$.modifications.put$TK$TV("DSE", "SER");
C$.modifications.put$TK$TV("DSG", "ASN");
C$.modifications.put$TK$TV("DSN", "SER");
C$.modifications.put$TK$TV("DSP", "ASP");
C$.modifications.put$TK$TV("DT ", "THR");
C$.modifications.put$TK$TV("DTH", "THR");
C$.modifications.put$TK$TV("DTR", "TRP");
C$.modifications.put$TK$TV("DTY", "TYR");
C$.modifications.put$TK$TV("DU ", "UR3");
C$.modifications.put$TK$TV("DVA", "VAL");
C$.modifications.put$TK$TV("DXD", "ASN");
C$.modifications.put$TK$TV("DXN", "ASN");
C$.modifications.put$TK$TV("DYG", "DYG");
C$.modifications.put$TK$TV("DYS", "CYS");
C$.modifications.put$TK$TV("DZM", "ALA");
C$.modifications.put$TK$TV("E  ", "ALA");
C$.modifications.put$TK$TV("E1X", "ALA");
C$.modifications.put$TK$TV("ECC", "GLN");
C$.modifications.put$TK$TV("EDA", "ALA");
C$.modifications.put$TK$TV("EFC", "CYS");
C$.modifications.put$TK$TV("EHP", "PHE");
C$.modifications.put$TK$TV("EIT", "THR");
C$.modifications.put$TK$TV("ENP", "ASN");
C$.modifications.put$TK$TV("ESB", "TYR");
C$.modifications.put$TK$TV("ESC", "MET");
C$.modifications.put$TK$TV("EXB", "XAA");
C$.modifications.put$TK$TV("EXY", "LEU");
C$.modifications.put$TK$TV("EY5", "ASN");
C$.modifications.put$TK$TV("EYS", "XAA");
C$.modifications.put$TK$TV("F2F", "PHE");
C$.modifications.put$TK$TV("FA2", "ALA");
C$.modifications.put$TK$TV("FA5", "ASN");
C$.modifications.put$TK$TV("FAG", "ASN");
C$.modifications.put$TK$TV("FAI", "ASN");
C$.modifications.put$TK$TV("FB5", "ALA");
C$.modifications.put$TK$TV("FB6", "ALA");
C$.modifications.put$TK$TV("FCL", "PHE");
C$.modifications.put$TK$TV("FFD", "ASN");
C$.modifications.put$TK$TV("FGA", "GLU");
C$.modifications.put$TK$TV("FGL", "GLY");
C$.modifications.put$TK$TV("FGP", "SER");
C$.modifications.put$TK$TV("FHL", "XAA");
C$.modifications.put$TK$TV("FHO", "LYS");
C$.modifications.put$TK$TV("FHU", "UR3");
C$.modifications.put$TK$TV("FLA", "ALA");
C$.modifications.put$TK$TV("FLE", "LEU");
C$.modifications.put$TK$TV("FLT", "TYR");
C$.modifications.put$TK$TV("FME", "MET");
C$.modifications.put$TK$TV("FMG", "GLY");
C$.modifications.put$TK$TV("FMU", "ASN");
C$.modifications.put$TK$TV("FOE", "CYS");
C$.modifications.put$TK$TV("FOX", "GLY");
C$.modifications.put$TK$TV("FP9", "PRO");
C$.modifications.put$TK$TV("FPA", "PHE");
C$.modifications.put$TK$TV("FRD", "XAA");
C$.modifications.put$TK$TV("FT6", "TRP");
C$.modifications.put$TK$TV("FTR", "TRP");
C$.modifications.put$TK$TV("FTY", "TYR");
C$.modifications.put$TK$TV("FVA", "VAL");
C$.modifications.put$TK$TV("FZN", "LYS");
C$.modifications.put$TK$TV("G  ", "GLY");
C$.modifications.put$TK$TV("G25", "GLY");
C$.modifications.put$TK$TV("G2L", "GLY");
C$.modifications.put$TK$TV("G2S", "GLY");
C$.modifications.put$TK$TV("G31", "GLY");
C$.modifications.put$TK$TV("G32", "GLY");
C$.modifications.put$TK$TV("G33", "GLY");
C$.modifications.put$TK$TV("G36", "GLY");
C$.modifications.put$TK$TV("G38", "GLY");
C$.modifications.put$TK$TV("G42", "GLY");
C$.modifications.put$TK$TV("G46", "GLY");
C$.modifications.put$TK$TV("G47", "GLY");
C$.modifications.put$TK$TV("G48", "GLY");
C$.modifications.put$TK$TV("G49", "GLY");
C$.modifications.put$TK$TV("G4P", "ASN");
C$.modifications.put$TK$TV("G7M", "GLY");
C$.modifications.put$TK$TV("GAO", "GLY");
C$.modifications.put$TK$TV("GAU", "GLU");
C$.modifications.put$TK$TV("GCK", "CYS");
C$.modifications.put$TK$TV("GCM", "XAA");
C$.modifications.put$TK$TV("GDP", "GLY");
C$.modifications.put$TK$TV("GDR", "GLY");
C$.modifications.put$TK$TV("GFL", "GLY");
C$.modifications.put$TK$TV("GGL", "GLU");
C$.modifications.put$TK$TV("GH3", "GLY");
C$.modifications.put$TK$TV("GHG", "GLN");
C$.modifications.put$TK$TV("GHP", "GLY");
C$.modifications.put$TK$TV("GL3", "GLY");
C$.modifications.put$TK$TV("GLH", "GLN");
C$.modifications.put$TK$TV("GLJ", "GLU");
C$.modifications.put$TK$TV("GLK", "GLU");
C$.modifications.put$TK$TV("GLM", "XAA");
C$.modifications.put$TK$TV("GLN", "GLN");
C$.modifications.put$TK$TV("GLQ", "GLU");
C$.modifications.put$TK$TV("GLU", "GLU");
C$.modifications.put$TK$TV("GLX", "GLX");
C$.modifications.put$TK$TV("GLY", "GLY");
C$.modifications.put$TK$TV("GLZ", "GLY");
C$.modifications.put$TK$TV("GMA", "GLU");
C$.modifications.put$TK$TV("GMS", "GLY");
C$.modifications.put$TK$TV("GMU", "UR3");
C$.modifications.put$TK$TV("GN7", "GLY");
C$.modifications.put$TK$TV("GND", "XAA");
C$.modifications.put$TK$TV("GNE", "ASN");
C$.modifications.put$TK$TV("GOM", "GLY");
C$.modifications.put$TK$TV("GPL", "LYS");
C$.modifications.put$TK$TV("GS ", "GLY");
C$.modifications.put$TK$TV("GSC", "GLY");
C$.modifications.put$TK$TV("GSR", "GLY");
C$.modifications.put$TK$TV("GSS", "GLY");
C$.modifications.put$TK$TV("GSU", "GLU");
C$.modifications.put$TK$TV("GT9", "CYS");
C$.modifications.put$TK$TV("GTP", "GLY");
C$.modifications.put$TK$TV("GVL", "XAA");
C$.modifications.put$TK$TV("GYC", "CYG");
C$.modifications.put$TK$TV("GYS", "SYG");
C$.modifications.put$TK$TV("H2U", "UR3");
C$.modifications.put$TK$TV("H5M", "PRO");
C$.modifications.put$TK$TV("HAC", "ALA");
C$.modifications.put$TK$TV("HAR", "ARG");
C$.modifications.put$TK$TV("HBN", "HIS");
C$.modifications.put$TK$TV("HCS", "XAA");
C$.modifications.put$TK$TV("HDP", "UR3");
C$.modifications.put$TK$TV("HEU", "UR3");
C$.modifications.put$TK$TV("HFA", "XAA");
C$.modifications.put$TK$TV("HGL", "XAA");
C$.modifications.put$TK$TV("HHI", "HIS");
C$.modifications.put$TK$TV("HHK", "AK");
C$.modifications.put$TK$TV("HIA", "HIS");
C$.modifications.put$TK$TV("HIC", "HIS");
C$.modifications.put$TK$TV("HIP", "HIS");
C$.modifications.put$TK$TV("HIQ", "HIS");
C$.modifications.put$TK$TV("HIS", "HIS");
C$.modifications.put$TK$TV("HL2", "LEU");
C$.modifications.put$TK$TV("HLU", "LEU");
C$.modifications.put$TK$TV("HMR", "ARG");
C$.modifications.put$TK$TV("HOL", "ASN");
C$.modifications.put$TK$TV("HPC", "PHE");
C$.modifications.put$TK$TV("HPE", "PHE");
C$.modifications.put$TK$TV("HPH", "PHE");
C$.modifications.put$TK$TV("HPQ", "PHE");
C$.modifications.put$TK$TV("HQA", "ALA");
C$.modifications.put$TK$TV("HRG", "ARG");
C$.modifications.put$TK$TV("HRP", "TRP");
C$.modifications.put$TK$TV("HS8", "HIS");
C$.modifications.put$TK$TV("HS9", "HIS");
C$.modifications.put$TK$TV("HSE", "SER");
C$.modifications.put$TK$TV("HSL", "SER");
C$.modifications.put$TK$TV("HSO", "HIS");
C$.modifications.put$TK$TV("HTI", "CYS");
C$.modifications.put$TK$TV("HTN", "ASN");
C$.modifications.put$TK$TV("HTR", "TRP");
C$.modifications.put$TK$TV("HV5", "ALA");
C$.modifications.put$TK$TV("HVA", "VAL");
C$.modifications.put$TK$TV("HY3", "PRO");
C$.modifications.put$TK$TV("HYP", "PRO");
C$.modifications.put$TK$TV("HZP", "PRO");
C$.modifications.put$TK$TV("I  ", "ILE");
C$.modifications.put$TK$TV("I2M", "ILE");
C$.modifications.put$TK$TV("I58", "LYS");
C$.modifications.put$TK$TV("I5C", "CYS");
C$.modifications.put$TK$TV("IAM", "ALA");
C$.modifications.put$TK$TV("IAR", "ARG");
C$.modifications.put$TK$TV("IAS", "ASP");
C$.modifications.put$TK$TV("IC ", "CYS");
C$.modifications.put$TK$TV("IEL", "LYS");
C$.modifications.put$TK$TV("IEY", "HYG");
C$.modifications.put$TK$TV("IG ", "GLY");
C$.modifications.put$TK$TV("IGL", "GLY");
C$.modifications.put$TK$TV("IGU", "GLY");
C$.modifications.put$TK$TV("IIC", "SHG");
C$.modifications.put$TK$TV("IIL", "ILE");
C$.modifications.put$TK$TV("ILE", "ILE");
C$.modifications.put$TK$TV("ILG", "GLU");
C$.modifications.put$TK$TV("ILX", "ILE");
C$.modifications.put$TK$TV("IMC", "CYS");
C$.modifications.put$TK$TV("IML", "ILE");
C$.modifications.put$TK$TV("IOY", "PHE");
C$.modifications.put$TK$TV("IPG", "GLY");
C$.modifications.put$TK$TV("IPN", "ASN");
C$.modifications.put$TK$TV("IRN", "ASN");
C$.modifications.put$TK$TV("IT1", "LYS");
C$.modifications.put$TK$TV("IU ", "UR3");
C$.modifications.put$TK$TV("IYR", "TYR");
C$.modifications.put$TK$TV("IYT", "THR");
C$.modifications.put$TK$TV("IZO", "MET");
C$.modifications.put$TK$TV("JJJ", "CYS");
C$.modifications.put$TK$TV("JJK", "CYS");
C$.modifications.put$TK$TV("JJL", "CYS");
C$.modifications.put$TK$TV("JW5", "ASN");
C$.modifications.put$TK$TV("K1R", "CYS");
C$.modifications.put$TK$TV("KAG", "GLY");
C$.modifications.put$TK$TV("KCX", "LYS");
C$.modifications.put$TK$TV("KGC", "LYS");
C$.modifications.put$TK$TV("KNB", "ALA");
C$.modifications.put$TK$TV("KOR", "MET");
C$.modifications.put$TK$TV("KPI", "LYS");
C$.modifications.put$TK$TV("KST", "LYS");
C$.modifications.put$TK$TV("KYQ", "LYS");
C$.modifications.put$TK$TV("L2A", "XAA");
C$.modifications.put$TK$TV("LA2", "LYS");
C$.modifications.put$TK$TV("LAA", "ASP");
C$.modifications.put$TK$TV("LAL", "ALA");
C$.modifications.put$TK$TV("LBY", "LYS");
C$.modifications.put$TK$TV("LC ", "CYS");
C$.modifications.put$TK$TV("LCA", "ALA");
C$.modifications.put$TK$TV("LCC", "ASN");
C$.modifications.put$TK$TV("LCG", "GLY");
C$.modifications.put$TK$TV("LCH", "ASN");
C$.modifications.put$TK$TV("LCK", "LYS");
C$.modifications.put$TK$TV("LCX", "LYS");
C$.modifications.put$TK$TV("LDH", "LYS");
C$.modifications.put$TK$TV("LED", "LEU");
C$.modifications.put$TK$TV("LEF", "LEU");
C$.modifications.put$TK$TV("LEH", "LEU");
C$.modifications.put$TK$TV("LEI", "VAL");
C$.modifications.put$TK$TV("LEM", "LEU");
C$.modifications.put$TK$TV("LEN", "LEU");
C$.modifications.put$TK$TV("LET", "XAA");
C$.modifications.put$TK$TV("LEU", "LEU");
C$.modifications.put$TK$TV("LEX", "LEU");
C$.modifications.put$TK$TV("LG ", "GLY");
C$.modifications.put$TK$TV("LGP", "GLY");
C$.modifications.put$TK$TV("LHC", "XAA");
C$.modifications.put$TK$TV("LHU", "UR3");
C$.modifications.put$TK$TV("LKC", "ASN");
C$.modifications.put$TK$TV("LLP", "LYS");
C$.modifications.put$TK$TV("LLY", "LYS");
C$.modifications.put$TK$TV("LME", "GLU");
C$.modifications.put$TK$TV("LMF", "LYS");
C$.modifications.put$TK$TV("LMQ", "GLN");
C$.modifications.put$TK$TV("LMS", "ASN");
C$.modifications.put$TK$TV("LP6", "LYS");
C$.modifications.put$TK$TV("LPD", "PRO");
C$.modifications.put$TK$TV("LPG", "GLY");
C$.modifications.put$TK$TV("LPL", "XAA");
C$.modifications.put$TK$TV("LPS", "SER");
C$.modifications.put$TK$TV("LSO", "XAA");
C$.modifications.put$TK$TV("LTA", "XAA");
C$.modifications.put$TK$TV("LTR", "TRP");
C$.modifications.put$TK$TV("LVG", "GLY");
C$.modifications.put$TK$TV("LVN", "VAL");
C$.modifications.put$TK$TV("LYF", "LYS");
C$.modifications.put$TK$TV("LYK", "LYS");
C$.modifications.put$TK$TV("LYM", "LYS");
C$.modifications.put$TK$TV("LYN", "LYS");
C$.modifications.put$TK$TV("LYR", "LYS");
C$.modifications.put$TK$TV("LYS", "LYS");
C$.modifications.put$TK$TV("LYX", "LYS");
C$.modifications.put$TK$TV("LYZ", "LYS");
C$.modifications.put$TK$TV("M0H", "CYS");
C$.modifications.put$TK$TV("M1G", "GLY");
C$.modifications.put$TK$TV("M2G", "GLY");
C$.modifications.put$TK$TV("M2L", "LYS");
C$.modifications.put$TK$TV("M2S", "MET");
C$.modifications.put$TK$TV("M30", "GLY");
C$.modifications.put$TK$TV("M3L", "LYS");
C$.modifications.put$TK$TV("M5M", "CYS");
C$.modifications.put$TK$TV("MA ", "ALA");
C$.modifications.put$TK$TV("MA6", "ALA");
C$.modifications.put$TK$TV("MA7", "ALA");
C$.modifications.put$TK$TV("MAA", "ALA");
C$.modifications.put$TK$TV("MAD", "ALA");
C$.modifications.put$TK$TV("MAI", "ARG");
C$.modifications.put$TK$TV("MBQ", "TYR");
C$.modifications.put$TK$TV("MBZ", "ASN");
C$.modifications.put$TK$TV("MC1", "SER");
C$.modifications.put$TK$TV("MCG", "XAA");
C$.modifications.put$TK$TV("MCL", "LYS");
C$.modifications.put$TK$TV("MCS", "CYS");
C$.modifications.put$TK$TV("MCY", "CYS");
C$.modifications.put$TK$TV("MD3", "CYS");
C$.modifications.put$TK$TV("MD6", "GLY");
C$.modifications.put$TK$TV("MDH", "XAA");
C$.modifications.put$TK$TV("MDO", "ASG");
C$.modifications.put$TK$TV("MDR", "ASN");
C$.modifications.put$TK$TV("MEA", "PHE");
C$.modifications.put$TK$TV("MED", "MET");
C$.modifications.put$TK$TV("MEG", "GLU");
C$.modifications.put$TK$TV("MEN", "ASN");
C$.modifications.put$TK$TV("MEP", "UR3");
C$.modifications.put$TK$TV("MEQ", "GLN");
C$.modifications.put$TK$TV("MET", "MET");
C$.modifications.put$TK$TV("MEU", "GLY");
C$.modifications.put$TK$TV("MF3", "XAA");
C$.modifications.put$TK$TV("MFC", "GYG");
C$.modifications.put$TK$TV("MG1", "GLY");
C$.modifications.put$TK$TV("MGG", "ARG");
C$.modifications.put$TK$TV("MGN", "GLN");
C$.modifications.put$TK$TV("MGQ", "ALA");
C$.modifications.put$TK$TV("MGV", "GLY");
C$.modifications.put$TK$TV("MGY", "GLY");
C$.modifications.put$TK$TV("MHL", "LEU");
C$.modifications.put$TK$TV("MHO", "MET");
C$.modifications.put$TK$TV("MHS", "HIS");
C$.modifications.put$TK$TV("MIA", "ALA");
C$.modifications.put$TK$TV("MIS", "SER");
C$.modifications.put$TK$TV("MK8", "LEU");
C$.modifications.put$TK$TV("ML3", "LYS");
C$.modifications.put$TK$TV("MLE", "LEU");
C$.modifications.put$TK$TV("MLL", "LEU");
C$.modifications.put$TK$TV("MLY", "LYS");
C$.modifications.put$TK$TV("MLZ", "LYS");
C$.modifications.put$TK$TV("MME", "MET");
C$.modifications.put$TK$TV("MMO", "ARG");
C$.modifications.put$TK$TV("MMT", "THR");
C$.modifications.put$TK$TV("MND", "ASN");
C$.modifications.put$TK$TV("MNL", "LEU");
C$.modifications.put$TK$TV("MNU", "UR3");
C$.modifications.put$TK$TV("MNV", "VAL");
C$.modifications.put$TK$TV("MOD", "XAA");
C$.modifications.put$TK$TV("MP8", "PRO");
C$.modifications.put$TK$TV("MPH", "XAA");
C$.modifications.put$TK$TV("MPJ", "XAA");
C$.modifications.put$TK$TV("MPQ", "GLY");
C$.modifications.put$TK$TV("MRG", "GLY");
C$.modifications.put$TK$TV("MSA", "GLY");
C$.modifications.put$TK$TV("MSE", "MET");
C$.modifications.put$TK$TV("MSL", "MET");
C$.modifications.put$TK$TV("MSO", "MET");
C$.modifications.put$TK$TV("MSP", "XAA");
C$.modifications.put$TK$TV("MT2", "MET");
C$.modifications.put$TK$TV("MTR", "THR");
C$.modifications.put$TK$TV("MTU", "ALA");
C$.modifications.put$TK$TV("MTY", "TYR");
C$.modifications.put$TK$TV("MVA", "VAL");
C$.modifications.put$TK$TV("N  ", "ASN");
C$.modifications.put$TK$TV("N10", "SER");
C$.modifications.put$TK$TV("N2C", "XAA");
C$.modifications.put$TK$TV("N5I", "ASN");
C$.modifications.put$TK$TV("N5M", "CYS");
C$.modifications.put$TK$TV("N6G", "GLY");
C$.modifications.put$TK$TV("N7P", "PRO");
C$.modifications.put$TK$TV("NA8", "ALA");
C$.modifications.put$TK$TV("NAL", "ALA");
C$.modifications.put$TK$TV("NAM", "ALA");
C$.modifications.put$TK$TV("NB8", "ASN");
C$.modifications.put$TK$TV("NBQ", "TYR");
C$.modifications.put$TK$TV("NC1", "SER");
C$.modifications.put$TK$TV("NCB", "ALA");
C$.modifications.put$TK$TV("NCX", "ASN");
C$.modifications.put$TK$TV("NCY", "XAA");
C$.modifications.put$TK$TV("NDF", "PHE");
C$.modifications.put$TK$TV("NDN", "UR3");
C$.modifications.put$TK$TV("NEM", "HIS");
C$.modifications.put$TK$TV("NEP", "HIS");
C$.modifications.put$TK$TV("NF2", "ASN");
C$.modifications.put$TK$TV("NFA", "PHE");
C$.modifications.put$TK$TV("NHL", "GLU");
C$.modifications.put$TK$TV("NIT", "XAA");
C$.modifications.put$TK$TV("NIY", "TYR");
C$.modifications.put$TK$TV("NLE", "LEU");
C$.modifications.put$TK$TV("NLN", "LEU");
C$.modifications.put$TK$TV("NLO", "LEU");
C$.modifications.put$TK$TV("NLP", "LEU");
C$.modifications.put$TK$TV("NLQ", "GLN");
C$.modifications.put$TK$TV("NMC", "GLY");
C$.modifications.put$TK$TV("NMM", "ARG");
C$.modifications.put$TK$TV("NMS", "THR");
C$.modifications.put$TK$TV("NMT", "THR");
C$.modifications.put$TK$TV("NNH", "ARG");
C$.modifications.put$TK$TV("NP3", "ASN");
C$.modifications.put$TK$TV("NPH", "CYS");
C$.modifications.put$TK$TV("NPI", "ALA");
C$.modifications.put$TK$TV("NRP", "LYG");
C$.modifications.put$TK$TV("NRQ", "MYG");
C$.modifications.put$TK$TV("NSK", "XAA");
C$.modifications.put$TK$TV("NTY", "TYR");
C$.modifications.put$TK$TV("NVA", "VAL");
C$.modifications.put$TK$TV("NYC", "TWG");
C$.modifications.put$TK$TV("NYG", "NYG");
C$.modifications.put$TK$TV("NYM", "ASN");
C$.modifications.put$TK$TV("NYS", "CYS");
C$.modifications.put$TK$TV("NZH", "HIS");
C$.modifications.put$TK$TV("O12", "XAA");
C$.modifications.put$TK$TV("O2C", "ASN");
C$.modifications.put$TK$TV("O2G", "GLY");
C$.modifications.put$TK$TV("OAD", "ASN");
C$.modifications.put$TK$TV("OAS", "SER");
C$.modifications.put$TK$TV("OBF", "XAA");
C$.modifications.put$TK$TV("OBS", "XAA");
C$.modifications.put$TK$TV("OCS", "CYS");
C$.modifications.put$TK$TV("OCY", "CYS");
C$.modifications.put$TK$TV("ODP", "ASN");
C$.modifications.put$TK$TV("OHI", "HIS");
C$.modifications.put$TK$TV("OHS", "ASP");
C$.modifications.put$TK$TV("OIC", "XAA");
C$.modifications.put$TK$TV("OIP", "ILE");
C$.modifications.put$TK$TV("OLE", "XAA");
C$.modifications.put$TK$TV("OLT", "THR");
C$.modifications.put$TK$TV("OLZ", "SER");
C$.modifications.put$TK$TV("OMC", "CYS");
C$.modifications.put$TK$TV("OMG", "GLY");
C$.modifications.put$TK$TV("OMT", "MET");
C$.modifications.put$TK$TV("OMU", "UR3");
C$.modifications.put$TK$TV("ONE", "UR3");
C$.modifications.put$TK$TV("ONH", "ALA");
C$.modifications.put$TK$TV("ONL", "XAA");
C$.modifications.put$TK$TV("OPR", "ARG");
C$.modifications.put$TK$TV("ORN", "ALA");
C$.modifications.put$TK$TV("ORQ", "ARG");
C$.modifications.put$TK$TV("OSE", "SER");
C$.modifications.put$TK$TV("OTB", "XAA");
C$.modifications.put$TK$TV("OTH", "THR");
C$.modifications.put$TK$TV("OTY", "TYR");
C$.modifications.put$TK$TV("OXX", "ASP");
C$.modifications.put$TK$TV("P  ", "GLY");
C$.modifications.put$TK$TV("P1L", "CYS");
C$.modifications.put$TK$TV("P1P", "ASN");
C$.modifications.put$TK$TV("P2T", "THR");
C$.modifications.put$TK$TV("P2U", "UR3");
C$.modifications.put$TK$TV("P2Y", "PRO");
C$.modifications.put$TK$TV("P5P", "ALA");
C$.modifications.put$TK$TV("PAQ", "TYR");
C$.modifications.put$TK$TV("PAS", "ASP");
C$.modifications.put$TK$TV("PAT", "TRP");
C$.modifications.put$TK$TV("PAU", "ALA");
C$.modifications.put$TK$TV("PBB", "CYS");
C$.modifications.put$TK$TV("PBF", "PHE");
C$.modifications.put$TK$TV("PBT", "ASN");
C$.modifications.put$TK$TV("PCA", "GLU");
C$.modifications.put$TK$TV("PCC", "PRO");
C$.modifications.put$TK$TV("PCE", "XAA");
C$.modifications.put$TK$TV("PCS", "PHE");
C$.modifications.put$TK$TV("PDL", "XAA");
C$.modifications.put$TK$TV("PDU", "UR3");
C$.modifications.put$TK$TV("PEC", "CYS");
C$.modifications.put$TK$TV("PF5", "PHE");
C$.modifications.put$TK$TV("PFF", "PHE");
C$.modifications.put$TK$TV("PFX", "XAA");
C$.modifications.put$TK$TV("PG1", "SER");
C$.modifications.put$TK$TV("PG7", "GLY");
C$.modifications.put$TK$TV("PG9", "GLY");
C$.modifications.put$TK$TV("PGL", "XAA");
C$.modifications.put$TK$TV("PGN", "GLY");
C$.modifications.put$TK$TV("PGP", "GLY");
C$.modifications.put$TK$TV("PGY", "GLY");
C$.modifications.put$TK$TV("PHA", "PHE");
C$.modifications.put$TK$TV("PHD", "ASP");
C$.modifications.put$TK$TV("PHE", "PHE");
C$.modifications.put$TK$TV("PHI", "PHE");
C$.modifications.put$TK$TV("PHL", "PHE");
C$.modifications.put$TK$TV("PHM", "PHE");
C$.modifications.put$TK$TV("PIA", "AYG");
C$.modifications.put$TK$TV("PIV", "XAA");
C$.modifications.put$TK$TV("PLE", "LEU");
C$.modifications.put$TK$TV("PM3", "PHE");
C$.modifications.put$TK$TV("PMT", "CYS");
C$.modifications.put$TK$TV("POM", "PRO");
C$.modifications.put$TK$TV("PPN", "PHE");
C$.modifications.put$TK$TV("PPU", "ALA");
C$.modifications.put$TK$TV("PPW", "GLY");
C$.modifications.put$TK$TV("PQ1", "ASN");
C$.modifications.put$TK$TV("PR3", "CYS");
C$.modifications.put$TK$TV("PR5", "ALA");
C$.modifications.put$TK$TV("PR9", "PRO");
C$.modifications.put$TK$TV("PRN", "ALA");
C$.modifications.put$TK$TV("PRO", "PRO");
C$.modifications.put$TK$TV("PRS", "PRO");
C$.modifications.put$TK$TV("PSA", "PHE");
C$.modifications.put$TK$TV("PSH", "HIS");
C$.modifications.put$TK$TV("PST", "THR");
C$.modifications.put$TK$TV("PSU", "UR3");
C$.modifications.put$TK$TV("PSW", "CYS");
C$.modifications.put$TK$TV("PTA", "XAA");
C$.modifications.put$TK$TV("PTH", "TYR");
C$.modifications.put$TK$TV("PTM", "TYR");
C$.modifications.put$TK$TV("PTR", "TYR");
C$.modifications.put$TK$TV("PU ", "ALA");
C$.modifications.put$TK$TV("PUY", "ASN");
C$.modifications.put$TK$TV("PVH", "HIS");
C$.modifications.put$TK$TV("PVL", "XAA");
C$.modifications.put$TK$TV("PYA", "ALA");
C$.modifications.put$TK$TV("PYO", "UR3");
C$.modifications.put$TK$TV("PYX", "CYS");
C$.modifications.put$TK$TV("PYY", "ASN");
C$.modifications.put$TK$TV("QLG", "QLG");
C$.modifications.put$TK$TV("QMM", "GLN");
C$.modifications.put$TK$TV("QPA", "CYS");
C$.modifications.put$TK$TV("QPH", "PHE");
C$.modifications.put$TK$TV("QUO", "GLY");
C$.modifications.put$TK$TV("R  ", "ALA");
C$.modifications.put$TK$TV("R1A", "CYS");
C$.modifications.put$TK$TV("R4K", "TRP");
C$.modifications.put$TK$TV("RC7", "HYG");
C$.modifications.put$TK$TV("RE0", "TRP");
C$.modifications.put$TK$TV("RE3", "TRP");
C$.modifications.put$TK$TV("RIA", "ALA");
C$.modifications.put$TK$TV("RMP", "ALA");
C$.modifications.put$TK$TV("RON", "XAA");
C$.modifications.put$TK$TV("RT ", "THR");
C$.modifications.put$TK$TV("RTP", "ASN");
C$.modifications.put$TK$TV("S1H", "SER");
C$.modifications.put$TK$TV("S2C", "CYS");
C$.modifications.put$TK$TV("S2D", "ALA");
C$.modifications.put$TK$TV("S2M", "THR");
C$.modifications.put$TK$TV("S2P", "ALA");
C$.modifications.put$TK$TV("S4A", "ALA");
C$.modifications.put$TK$TV("S4C", "CYS");
C$.modifications.put$TK$TV("S4G", "GLY");
C$.modifications.put$TK$TV("S4U", "UR3");
C$.modifications.put$TK$TV("S6G", "GLY");
C$.modifications.put$TK$TV("SAC", "SER");
C$.modifications.put$TK$TV("SAH", "CYS");
C$.modifications.put$TK$TV("SAR", "GLY");
C$.modifications.put$TK$TV("SBL", "SER");
C$.modifications.put$TK$TV("SC ", "CYS");
C$.modifications.put$TK$TV("SCH", "CYS");
C$.modifications.put$TK$TV("SCS", "CYS");
C$.modifications.put$TK$TV("SCY", "CYS");
C$.modifications.put$TK$TV("SD2", "XAA");
C$.modifications.put$TK$TV("SDG", "GLY");
C$.modifications.put$TK$TV("SDP", "SER");
C$.modifications.put$TK$TV("SEB", "SER");
C$.modifications.put$TK$TV("SEC", "ALA");
C$.modifications.put$TK$TV("SEG", "ALA");
C$.modifications.put$TK$TV("SEL", "SER");
C$.modifications.put$TK$TV("SEM", "SER");
C$.modifications.put$TK$TV("SEN", "SER");
C$.modifications.put$TK$TV("SEP", "SER");
C$.modifications.put$TK$TV("SER", "SER");
C$.modifications.put$TK$TV("SET", "SER");
C$.modifications.put$TK$TV("SGB", "SER");
C$.modifications.put$TK$TV("SHC", "CYS");
C$.modifications.put$TK$TV("SHP", "GLY");
C$.modifications.put$TK$TV("SHR", "LYS");
C$.modifications.put$TK$TV("SIB", "CYS");
C$.modifications.put$TK$TV("SIC", "DC");
C$.modifications.put$TK$TV("SLA", "PRO");
C$.modifications.put$TK$TV("SLR", "PRO");
C$.modifications.put$TK$TV("SLZ", "LYS");
C$.modifications.put$TK$TV("SMC", "CYS");
C$.modifications.put$TK$TV("SME", "MET");
C$.modifications.put$TK$TV("SMF", "PHE");
C$.modifications.put$TK$TV("SMP", "ALA");
C$.modifications.put$TK$TV("SMT", "THR");
C$.modifications.put$TK$TV("SNC", "CYS");
C$.modifications.put$TK$TV("SNN", "ASN");
C$.modifications.put$TK$TV("SOC", "CYS");
C$.modifications.put$TK$TV("SOS", "ASN");
C$.modifications.put$TK$TV("SOY", "SER");
C$.modifications.put$TK$TV("SPT", "THR");
C$.modifications.put$TK$TV("SRA", "ALA");
C$.modifications.put$TK$TV("SSU", "UR3");
C$.modifications.put$TK$TV("STY", "TYR");
C$.modifications.put$TK$TV("SUB", "XAA");
C$.modifications.put$TK$TV("SUI", "DG");
C$.modifications.put$TK$TV("SUN", "SER");
C$.modifications.put$TK$TV("SUR", "UR3");
C$.modifications.put$TK$TV("SVA", "SER");
C$.modifications.put$TK$TV("SVV", "SER");
C$.modifications.put$TK$TV("SVW", "SER");
C$.modifications.put$TK$TV("SVX", "SER");
C$.modifications.put$TK$TV("SVY", "SER");
C$.modifications.put$TK$TV("SVZ", "XAA");
C$.modifications.put$TK$TV("SWG", "SWG");
C$.modifications.put$TK$TV("SYS", "CYS");
C$.modifications.put$TK$TV("T  ", "THR");
C$.modifications.put$TK$TV("T11", "PHE");
C$.modifications.put$TK$TV("T23", "THR");
C$.modifications.put$TK$TV("T2S", "THR");
C$.modifications.put$TK$TV("T2T", "ASN");
C$.modifications.put$TK$TV("T31", "UR3");
C$.modifications.put$TK$TV("T32", "THR");
C$.modifications.put$TK$TV("T36", "THR");
C$.modifications.put$TK$TV("T37", "THR");
C$.modifications.put$TK$TV("T38", "THR");
C$.modifications.put$TK$TV("T39", "THR");
C$.modifications.put$TK$TV("T3P", "THR");
C$.modifications.put$TK$TV("T41", "THR");
C$.modifications.put$TK$TV("T48", "THR");
C$.modifications.put$TK$TV("T49", "THR");
C$.modifications.put$TK$TV("T4S", "THR");
C$.modifications.put$TK$TV("T5O", "UR3");
C$.modifications.put$TK$TV("T5S", "THR");
C$.modifications.put$TK$TV("T66", "XAA");
C$.modifications.put$TK$TV("T6A", "ALA");
C$.modifications.put$TK$TV("TA3", "THR");
C$.modifications.put$TK$TV("TA4", "XAA");
C$.modifications.put$TK$TV("TAF", "THR");
C$.modifications.put$TK$TV("TAL", "ASN");
C$.modifications.put$TK$TV("TAV", "ASP");
C$.modifications.put$TK$TV("TBG", "VAL");
C$.modifications.put$TK$TV("TBM", "THR");
C$.modifications.put$TK$TV("TC1", "CYS");
C$.modifications.put$TK$TV("TCP", "THR");
C$.modifications.put$TK$TV("TCQ", "TYR");
C$.modifications.put$TK$TV("TCR", "TRP");
C$.modifications.put$TK$TV("TCY", "ALA");
C$.modifications.put$TK$TV("TDD", "LEU");
C$.modifications.put$TK$TV("TDY", "THR");
C$.modifications.put$TK$TV("TFE", "THR");
C$.modifications.put$TK$TV("TFO", "ALA");
C$.modifications.put$TK$TV("TFQ", "PHE");
C$.modifications.put$TK$TV("TFT", "THR");
C$.modifications.put$TK$TV("TGP", "GLY");
C$.modifications.put$TK$TV("TH6", "THR");
C$.modifications.put$TK$TV("THC", "THR");
C$.modifications.put$TK$TV("THO", "XAA");
C$.modifications.put$TK$TV("THR", "THR");
C$.modifications.put$TK$TV("THX", "ASN");
C$.modifications.put$TK$TV("THZ", "ARG");
C$.modifications.put$TK$TV("TIH", "ALA");
C$.modifications.put$TK$TV("TLB", "ASN");
C$.modifications.put$TK$TV("TLC", "THR");
C$.modifications.put$TK$TV("TLN", "UR3");
C$.modifications.put$TK$TV("TMB", "THR");
C$.modifications.put$TK$TV("TMD", "THR");
C$.modifications.put$TK$TV("TNB", "CYS");
C$.modifications.put$TK$TV("TNR", "SER");
C$.modifications.put$TK$TV("TOX", "TRP");
C$.modifications.put$TK$TV("TP1", "THR");
C$.modifications.put$TK$TV("TPC", "CYS");
C$.modifications.put$TK$TV("TPG", "GLY");
C$.modifications.put$TK$TV("TPH", "XAA");
C$.modifications.put$TK$TV("TPL", "TRP");
C$.modifications.put$TK$TV("TPO", "THR");
C$.modifications.put$TK$TV("TPQ", "TYR");
C$.modifications.put$TK$TV("TQI", "TRP");
C$.modifications.put$TK$TV("TQQ", "TRP");
C$.modifications.put$TK$TV("TRF", "TRP");
C$.modifications.put$TK$TV("TRG", "LYS");
C$.modifications.put$TK$TV("TRN", "TRP");
C$.modifications.put$TK$TV("TRO", "TRP");
C$.modifications.put$TK$TV("TRP", "TRP");
C$.modifications.put$TK$TV("TRQ", "TRP");
C$.modifications.put$TK$TV("TRW", "TRP");
C$.modifications.put$TK$TV("TRX", "TRP");
C$.modifications.put$TK$TV("TS ", "ASN");
C$.modifications.put$TK$TV("TST", "XAA");
C$.modifications.put$TK$TV("TT ", "ASN");
C$.modifications.put$TK$TV("TTD", "THR");
C$.modifications.put$TK$TV("TTI", "UR3");
C$.modifications.put$TK$TV("TTM", "THR");
C$.modifications.put$TK$TV("TTQ", "TRP");
C$.modifications.put$TK$TV("TTS", "TYR");
C$.modifications.put$TK$TV("TY1", "TYR");
C$.modifications.put$TK$TV("TY2", "TYR");
C$.modifications.put$TK$TV("TY3", "TYR");
C$.modifications.put$TK$TV("TY5", "TYR");
C$.modifications.put$TK$TV("TYB", "TYR");
C$.modifications.put$TK$TV("TYI", "TYR");
C$.modifications.put$TK$TV("TYJ", "TYR");
C$.modifications.put$TK$TV("TYN", "TYR");
C$.modifications.put$TK$TV("TYO", "TYR");
C$.modifications.put$TK$TV("TYQ", "TYR");
C$.modifications.put$TK$TV("TYR", "TYR");
C$.modifications.put$TK$TV("TYS", "TYR");
C$.modifications.put$TK$TV("TYT", "TYR");
C$.modifications.put$TK$TV("TYU", "ASN");
C$.modifications.put$TK$TV("TYW", "TYR");
C$.modifications.put$TK$TV("TYX", "XAA");
C$.modifications.put$TK$TV("TYY", "TYR");
C$.modifications.put$TK$TV("TZB", "XAA");
C$.modifications.put$TK$TV("TZO", "XAA");
C$.modifications.put$TK$TV("U  ", "UR3");
C$.modifications.put$TK$TV("U25", "UR3");
C$.modifications.put$TK$TV("U2L", "UR3");
C$.modifications.put$TK$TV("U2N", "UR3");
C$.modifications.put$TK$TV("U2P", "UR3");
C$.modifications.put$TK$TV("U31", "UR3");
C$.modifications.put$TK$TV("U33", "UR3");
C$.modifications.put$TK$TV("U34", "UR3");
C$.modifications.put$TK$TV("U36", "UR3");
C$.modifications.put$TK$TV("U37", "UR3");
C$.modifications.put$TK$TV("U8U", "UR3");
C$.modifications.put$TK$TV("UAR", "UR3");
C$.modifications.put$TK$TV("UCL", "UR3");
C$.modifications.put$TK$TV("UD5", "UR3");
C$.modifications.put$TK$TV("UDP", "ASN");
C$.modifications.put$TK$TV("UFP", "ASN");
C$.modifications.put$TK$TV("UFR", "UR3");
C$.modifications.put$TK$TV("UFT", "UR3");
C$.modifications.put$TK$TV("UMA", "ALA");
C$.modifications.put$TK$TV("UMP", "UR3");
C$.modifications.put$TK$TV("UMS", "UR3");
C$.modifications.put$TK$TV("UN1", "XAA");
C$.modifications.put$TK$TV("UN2", "XAA");
C$.modifications.put$TK$TV("UNK", "XAA");
C$.modifications.put$TK$TV("UR3", "UR3");
C$.modifications.put$TK$TV("URD", "UR3");
C$.modifications.put$TK$TV("US1", "UR3");
C$.modifications.put$TK$TV("US2", "UR3");
C$.modifications.put$TK$TV("US3", "THR");
C$.modifications.put$TK$TV("US5", "UR3");
C$.modifications.put$TK$TV("USM", "UR3");
C$.modifications.put$TK$TV("VAD", "VAL");
C$.modifications.put$TK$TV("VAF", "VAL");
C$.modifications.put$TK$TV("VAL", "VAL");
C$.modifications.put$TK$TV("VB1", "LYS");
C$.modifications.put$TK$TV("VDL", "XAA");
C$.modifications.put$TK$TV("VLL", "XAA");
C$.modifications.put$TK$TV("VLM", "XAA");
C$.modifications.put$TK$TV("VMS", "XAA");
C$.modifications.put$TK$TV("VOL", "XAA");
C$.modifications.put$TK$TV("WCR", "GYG");
C$.modifications.put$TK$TV("X  ", "GLY");
C$.modifications.put$TK$TV("X2W", "GLU");
C$.modifications.put$TK$TV("X4A", "ASN");
C$.modifications.put$TK$TV("X9Q", "AFG");
C$.modifications.put$TK$TV("XAD", "ALA");
C$.modifications.put$TK$TV("XAE", "ASN");
C$.modifications.put$TK$TV("XAL", "ALA");
C$.modifications.put$TK$TV("XAR", "ASN");
C$.modifications.put$TK$TV("XCL", "CYS");
C$.modifications.put$TK$TV("XCN", "CYS");
C$.modifications.put$TK$TV("XCP", "XAA");
C$.modifications.put$TK$TV("XCR", "CYS");
C$.modifications.put$TK$TV("XCS", "ASN");
C$.modifications.put$TK$TV("XCT", "CYS");
C$.modifications.put$TK$TV("XCY", "CYS");
C$.modifications.put$TK$TV("XGA", "ASN");
C$.modifications.put$TK$TV("XGL", "GLY");
C$.modifications.put$TK$TV("XGR", "GLY");
C$.modifications.put$TK$TV("XGU", "GLY");
C$.modifications.put$TK$TV("XPR", "PRO");
C$.modifications.put$TK$TV("XSN", "ASN");
C$.modifications.put$TK$TV("XTH", "THR");
C$.modifications.put$TK$TV("XTL", "THR");
C$.modifications.put$TK$TV("XTR", "THR");
C$.modifications.put$TK$TV("XTS", "GLY");
C$.modifications.put$TK$TV("XTY", "ASN");
C$.modifications.put$TK$TV("XUA", "ALA");
C$.modifications.put$TK$TV("XUG", "GLY");
C$.modifications.put$TK$TV("XX1", "LYS");
C$.modifications.put$TK$TV("XXY", "THG");
C$.modifications.put$TK$TV("XYG", "DYG");
C$.modifications.put$TK$TV("Y  ", "ALA");
C$.modifications.put$TK$TV("YCM", "CYS");
C$.modifications.put$TK$TV("YG ", "GLY");
C$.modifications.put$TK$TV("YOF", "TYR");
C$.modifications.put$TK$TV("YRR", "ASN");
C$.modifications.put$TK$TV("YYG", "GLY");
C$.modifications.put$TK$TV("Z  ", "CYS");
C$.modifications.put$TK$TV("Z01", "ALA");
C$.modifications.put$TK$TV("ZAD", "ALA");
C$.modifications.put$TK$TV("ZAL", "ALA");
C$.modifications.put$TK$TV("ZBC", "CYS");
C$.modifications.put$TK$TV("ZBU", "UR3");
C$.modifications.put$TK$TV("ZCL", "PHE");
C$.modifications.put$TK$TV("ZCY", "CYS");
C$.modifications.put$TK$TV("ZDU", "UR3");
C$.modifications.put$TK$TV("ZFB", "XAA");
C$.modifications.put$TK$TV("ZGU", "GLY");
C$.modifications.put$TK$TV("ZHP", "ASN");
C$.modifications.put$TK$TV("ZTH", "THR");
C$.modifications.put$TK$TV("ZU0", "THR");
C$.modifications.put$TK$TV("ZZJ", "ALA");
};
}

Clazz.newMeth(C$, '$init$', function () {
}, 1);

Clazz.newMeth(C$, 'c$', function () {
C$.$init$.apply(this);
}, 1);

Clazz.newMeth(C$, 'getHydmax$', function () {
return 4.5;
}, 1);

Clazz.newMeth(C$, 'getHydmin$', function () {
return -3.9;
}, 1);

Clazz.newMeth(C$, 'getHyd$', function () {
return C$.hyd;
}, 1);

Clazz.newMeth(C$, 'getAA3Hash$', function () {
return C$.aa3Hash;
}, 1);

Clazz.newMeth(C$, 'codonTranslate$S', function (lccodon) {
var peptide=$I$(5).getInstance$().getStandardCodeTable$().translate$S(lccodon);
if ("*".equals$O(peptide)) {
return "STOP";
}return peptide;
}, 1);

Clazz.newMeth(C$, 'getDssp3state$S', function (ssString) {
if (ssString == null ) {
return null;
}var lookupSize=C$.toDssp3State.length;
var len=ssString.length$();
var trans=Clazz.array(Character.TYPE, [len]);
for (var i=0; i < len; i++) {
var c=ssString.charAt$I(i);
var index=c.$c() - 65;
if (index < 0 || index >= lookupSize ) {
trans[i]=" ";
} else {
trans[i]=C$.toDssp3State[index];
}}
return  String.instantialize(trans);
}, 1);

Clazz.newMeth(C$, 'getCanonicalAminoAcid$S', function (aA) {
var canonical=C$.modifications.get$O(aA);
return canonical == null  ? aA : canonical;
}, 1);

Clazz.newMeth(C$, 'getResidues$Z$Z', function (forNucleotide, includeAmbiguous) {
var result=Clazz.new_($I$(6));
if (forNucleotide) {
for (var nuc, $nuc = C$.nucleotideName.keySet$().iterator$(); $nuc.hasNext$()&&((nuc=($nuc.next$())),1);) {
var val=C$.nucleotideIndex[(nuc.charCodeAt$I(0))];
if ((!includeAmbiguous && val > 4 ) || (val >= 10) ) {
continue;
}nuc=nuc.toUpperCase$();
if (!result.contains$O(nuc)) {
result.add$TE(nuc);
}}
} else {
for (var res, $res = C$.aa3Hash.keySet$().iterator$(); $res.hasNext$()&&((res=($res.next$())),1);) {
var index=C$.aa3Hash.get$O(res).intValue$();
if ((!includeAmbiguous && index >= 20 ) || index >= 23 ) {
continue;
}res=res.toUpperCase$();
if (!result.contains$O(res)) {
result.add$TE(res);
}}
}return result;
}, 1);

Clazz.newMeth(C$, 'getSingleCharacterCode$S', function (threeLetterCode) {
if (threeLetterCode == null ) {
return "0";
}var index=C$.aa3Hash.get$O(threeLetterCode.toUpperCase$());
return index == null  ? "0" : C$.aa[(index).intValue$()].charAt$I(0);
}, 1);
})();
;Clazz.setTVer('3.2.4.07');//Created 2019-05-24 12:54:17 Java2ScriptVisitor version 3.2.4.07 net.sf.j2s.core.jar version 3.2.4.07
