(function(){var P$=Clazz.newPackage("jalview.schemes"),I$=[[0,'java.util.HashMap','java.awt.Color','java.util.Arrays','java.util.Hashtable','jalview.analysis.GeneticCodes','java.util.ArrayList','java.util.Locale']],I$0=I$[0],$I$=function(i,n,m){return m?$I$(i)[n].apply(null,m):((i=(I$[i]||(I$[i]=Clazz.load(I$0[i])))),!n&&i.$load$&&Clazz.load(i,2),i)};
/*c*/var C$=Clazz.newClass(P$, "ResidueProperties");

C$.$clinit$=2;

Clazz.newMeth(C$, '$init$', function () {
},1);

C$.$fields$=[[]
,['S',['STOP','START'],'O',['aaIndex','int[]','+nucleotideIndex','+purinepyrimidineIndex','aa3Hash','java.util.Map','+aa2Triplet','+nucleotideName','+modifications','ONE','Integer','+ZERO','aa','String[]','midBlue','java.awt.Color','taylor','java.awt.Color[]','+nucleotide','+purinepyrimidine','+zappo','hyd2','double[]','+helix','+strand','+turn','+buried','+hyd','STOP_CODONS','java.util.List','propHash','java.util.Map','+hydrophobic','+polar','+small','+positive','+negative','+charged','+aromatic','+aliphatic','+tiny','+proline','toDssp3State','char[]']]]

Clazz.newMeth(C$, 'c$',  function () {
;C$.$init$.apply(this);
}, 1);

Clazz.newMeth(C$, 'getHydmax$',  function () {
return 4.5;
}, 1);

Clazz.newMeth(C$, 'getHydmin$',  function () {
return -3.9;
}, 1);

Clazz.newMeth(C$, 'getHyd$',  function () {
return C$.hyd;
}, 1);

Clazz.newMeth(C$, 'getAA3Hash$',  function () {
return C$.aa3Hash;
}, 1);

Clazz.newMeth(C$, 'codonTranslate$S',  function (lccodon) {
var peptide=$I$(5).getInstance$().getStandardCodeTable$().translate$S(lccodon);
if ("*".equals$O(peptide)) {
return "STOP";
}return peptide;
}, 1);

Clazz.newMeth(C$, 'getDssp3state$S',  function (ssString) {
if (ssString == null ) {
return null;
}var lookupSize=C$.toDssp3State.length;
var len=ssString.length$();
var trans=Clazz.array(Character.TYPE, [len]);
for (var i=0; i < len; i++) {
var c=ssString.charAt$I(i);
var index=c.$c() - 65;
if (index < 0 || index >= lookupSize ) {
trans[i]=" ";
} else {
trans[i]=C$.toDssp3State[index];
}}
return  String.instantialize(trans);
}, 1);

Clazz.newMeth(C$, 'getCanonicalAminoAcid$S',  function (aA) {
var canonical=C$.modifications.get$O(aA);
return canonical == null  ? aA : canonical;
}, 1);

Clazz.newMeth(C$, 'getResidues$Z$Z',  function (forNucleotide, includeAmbiguous) {
var result=Clazz.new_($I$(6,1));
if (forNucleotide) {
for (var nuc, $nuc = C$.nucleotideName.keySet$().iterator$(); $nuc.hasNext$()&&((nuc=($nuc.next$())),1);) {
var val=C$.nucleotideIndex[(nuc.charCodeAt$I(0))];
if ((!includeAmbiguous && val > 4 ) || (val >= 10) ) {
continue;
}nuc=nuc.toUpperCase$java_util_Locale($I$(7).ROOT);
if (!result.contains$O(nuc)) {
result.add$O(nuc);
}}
} else {
for (var res, $res = C$.aa3Hash.keySet$().iterator$(); $res.hasNext$()&&((res=($res.next$())),1);) {
var index=C$.aa3Hash.get$O(res).intValue$();
if ((!includeAmbiguous && index >= 20 ) || index >= 23 ) {
continue;
}res=res.toUpperCase$java_util_Locale($I$(7).ROOT);
if (!result.contains$O(res)) {
result.add$O(res);
}}
}return result;
}, 1);

Clazz.newMeth(C$, 'getSingleCharacterCode$S',  function (threeLetterCode) {
if (threeLetterCode == null ) {
return "0";
}var index=C$.aa3Hash.get$O(threeLetterCode.toUpperCase$java_util_Locale($I$(7).ROOT));
return index == null  ? "0" : C$.aa[(index).$c()].charAt$I(0);
}, 1);

C$.$static$=function(){C$.$static$=0;
C$.aa3Hash=Clazz.new_($I$(1,1));
C$.aa2Triplet=Clazz.new_($I$(1,1));
C$.nucleotideName=Clazz.new_($I$(1,1));
C$.modifications=Clazz.new_($I$(1,1));
{
C$.aaIndex=Clazz.array(Integer.TYPE, [255]);
for (var i=0; i < 255; i++) {
C$.aaIndex[i]=23;
}
C$.aaIndex[65]=0;
C$.aaIndex[82]=1;
C$.aaIndex[78]=2;
C$.aaIndex[68]=3;
C$.aaIndex[67]=4;
C$.aaIndex[81]=5;
C$.aaIndex[69]=6;
C$.aaIndex[71]=7;
C$.aaIndex[72]=8;
C$.aaIndex[73]=9;
C$.aaIndex[76]=10;
C$.aaIndex[75]=11;
C$.aaIndex[77]=12;
C$.aaIndex[70]=13;
C$.aaIndex[80]=14;
C$.aaIndex[83]=15;
C$.aaIndex[84]=16;
C$.aaIndex[87]=17;
C$.aaIndex[89]=18;
C$.aaIndex[86]=19;
C$.aaIndex[66]=20;
C$.aaIndex[90]=21;
C$.aaIndex[88]=22;
C$.aaIndex[85]=22;
C$.aaIndex[97]=0;
C$.aaIndex[114]=1;
C$.aaIndex[110]=2;
C$.aaIndex[100]=3;
C$.aaIndex[99]=4;
C$.aaIndex[113]=5;
C$.aaIndex[101]=6;
C$.aaIndex[103]=7;
C$.aaIndex[104]=8;
C$.aaIndex[105]=9;
C$.aaIndex[108]=10;
C$.aaIndex[107]=11;
C$.aaIndex[109]=12;
C$.aaIndex[102]=13;
C$.aaIndex[112]=14;
C$.aaIndex[115]=15;
C$.aaIndex[116]=16;
C$.aaIndex[119]=17;
C$.aaIndex[121]=18;
C$.aaIndex[118]=19;
C$.aaIndex[98]=20;
C$.aaIndex[122]=21;
C$.aaIndex[120]=22;
C$.aaIndex[117]=22;
};
{
C$.nucleotideIndex=Clazz.array(Integer.TYPE, [255]);
for (var i=0; i < 255; i++) {
C$.nucleotideIndex[i]=10;
}
C$.nucleotideIndex[65]=0;
C$.nucleotideIndex[97]=0;
C$.nucleotideIndex[67]=1;
C$.nucleotideIndex[99]=1;
C$.nucleotideIndex[71]=2;
C$.nucleotideIndex[103]=2;
C$.nucleotideIndex[84]=3;
C$.nucleotideIndex[116]=3;
C$.nucleotideIndex[85]=4;
C$.nucleotideIndex[117]=4;
C$.nucleotideIndex[73]=5;
C$.nucleotideIndex[105]=5;
C$.nucleotideIndex[88]=6;
C$.nucleotideIndex[120]=6;
C$.nucleotideIndex[82]=7;
C$.nucleotideIndex[114]=7;
C$.nucleotideIndex[89]=8;
C$.nucleotideIndex[121]=8;
C$.nucleotideIndex[78]=9;
C$.nucleotideIndex[110]=9;
C$.nucleotideName.put$O$O("A", "Adenine");
C$.nucleotideName.put$O$O("a", "Adenine");
C$.nucleotideName.put$O$O("G", "Guanine");
C$.nucleotideName.put$O$O("g", "Guanine");
C$.nucleotideName.put$O$O("C", "Cytosine");
C$.nucleotideName.put$O$O("c", "Cytosine");
C$.nucleotideName.put$O$O("T", "Thymine");
C$.nucleotideName.put$O$O("t", "Thymine");
C$.nucleotideName.put$O$O("U", "Uracil");
C$.nucleotideName.put$O$O("u", "Uracil");
C$.nucleotideName.put$O$O("I", "Inosine");
C$.nucleotideName.put$O$O("i", "Inosine");
C$.nucleotideName.put$O$O("X", "Xanthine");
C$.nucleotideName.put$O$O("x", "Xanthine");
C$.nucleotideName.put$O$O("R", "Unknown Purine");
C$.nucleotideName.put$O$O("r", "Unknown Purine");
C$.nucleotideName.put$O$O("Y", "Unknown Pyrimidine");
C$.nucleotideName.put$O$O("y", "Unknown Pyrimidine");
C$.nucleotideName.put$O$O("N", "Unknown");
C$.nucleotideName.put$O$O("n", "Unknown");
C$.nucleotideName.put$O$O("W", "Weak nucleotide (A or T)");
C$.nucleotideName.put$O$O("w", "Weak nucleotide (A or T)");
C$.nucleotideName.put$O$O("S", "Strong nucleotide (G or C)");
C$.nucleotideName.put$O$O("s", "Strong nucleotide (G or C)");
C$.nucleotideName.put$O$O("M", "Amino (A or C)");
C$.nucleotideName.put$O$O("m", "Amino (A or C)");
C$.nucleotideName.put$O$O("K", "Keto (G or T)");
C$.nucleotideName.put$O$O("k", "Keto (G or T)");
C$.nucleotideName.put$O$O("B", "Not A (G or C or T)");
C$.nucleotideName.put$O$O("b", "Not A (G or C or T)");
C$.nucleotideName.put$O$O("H", "Not G (A or C or T)");
C$.nucleotideName.put$O$O("h", "Not G (A or C or T)");
C$.nucleotideName.put$O$O("D", "Not C (A or G or T)");
C$.nucleotideName.put$O$O("d", "Not C (A or G or T)");
C$.nucleotideName.put$O$O("V", "Not T (A or G or C");
C$.nucleotideName.put$O$O("v", "Not T (A or G or C");
};
{
C$.purinepyrimidineIndex=Clazz.array(Integer.TYPE, [255]);
for (var i=0; i < 255; i++) {
C$.purinepyrimidineIndex[i]=3;
}
C$.purinepyrimidineIndex[65]=0;
C$.purinepyrimidineIndex[97]=0;
C$.purinepyrimidineIndex[67]=1;
C$.purinepyrimidineIndex[99]=1;
C$.purinepyrimidineIndex[71]=0;
C$.purinepyrimidineIndex[103]=0;
C$.purinepyrimidineIndex[84]=1;
C$.purinepyrimidineIndex[116]=1;
C$.purinepyrimidineIndex[85]=1;
C$.purinepyrimidineIndex[117]=1;
C$.purinepyrimidineIndex[73]=2;
C$.purinepyrimidineIndex[105]=2;
C$.purinepyrimidineIndex[88]=2;
C$.purinepyrimidineIndex[120]=2;
C$.purinepyrimidineIndex[82]=0;
C$.purinepyrimidineIndex[114]=0;
C$.purinepyrimidineIndex[89]=1;
C$.purinepyrimidineIndex[121]=1;
C$.purinepyrimidineIndex[78]=2;
C$.purinepyrimidineIndex[110]=2;
};
C$.ONE=Integer.valueOf$I(1);
C$.ZERO=Integer.valueOf$I(0);
{
C$.aa3Hash.put$O$O("ALA", C$.ZERO);
C$.aa3Hash.put$O$O("ARG", C$.ONE);
C$.aa3Hash.put$O$O("ASN", Integer.valueOf$I(2));
C$.aa3Hash.put$O$O("ASP", Integer.valueOf$I(3));
C$.aa3Hash.put$O$O("CYS", Integer.valueOf$I(4));
C$.aa3Hash.put$O$O("GLN", Integer.valueOf$I(5));
C$.aa3Hash.put$O$O("GLU", Integer.valueOf$I(6));
C$.aa3Hash.put$O$O("GLY", Integer.valueOf$I(7));
C$.aa3Hash.put$O$O("HIS", Integer.valueOf$I(8));
C$.aa3Hash.put$O$O("ILE", Integer.valueOf$I(9));
C$.aa3Hash.put$O$O("LEU", Integer.valueOf$I(10));
C$.aa3Hash.put$O$O("LYS", Integer.valueOf$I(11));
C$.aa3Hash.put$O$O("MET", Integer.valueOf$I(12));
C$.aa3Hash.put$O$O("PHE", Integer.valueOf$I(13));
C$.aa3Hash.put$O$O("PRO", Integer.valueOf$I(14));
C$.aa3Hash.put$O$O("SER", Integer.valueOf$I(15));
C$.aa3Hash.put$O$O("THR", Integer.valueOf$I(16));
C$.aa3Hash.put$O$O("TRP", Integer.valueOf$I(17));
C$.aa3Hash.put$O$O("TYR", Integer.valueOf$I(18));
C$.aa3Hash.put$O$O("VAL", Integer.valueOf$I(19));
C$.aa3Hash.put$O$O("ASX", Integer.valueOf$I(20));
C$.aa3Hash.put$O$O("GLX", Integer.valueOf$I(21));
C$.aa3Hash.put$O$O("XAA", Integer.valueOf$I(22));
C$.aa3Hash.put$O$O("-", Integer.valueOf$I(23));
C$.aa3Hash.put$O$O("*", Integer.valueOf$I(23));
C$.aa3Hash.put$O$O(".", Integer.valueOf$I(23));
C$.aa3Hash.put$O$O(" ", Integer.valueOf$I(23));
C$.aa3Hash.put$O$O("Gap", Integer.valueOf$I(23));
C$.aa3Hash.put$O$O("UR3", Integer.valueOf$I(24));
};
{
C$.aa2Triplet.put$O$O("A", "ALA");
C$.aa2Triplet.put$O$O("a", "ALA");
C$.aa2Triplet.put$O$O("R", "ARG");
C$.aa2Triplet.put$O$O("r", "ARG");
C$.aa2Triplet.put$O$O("N", "ASN");
C$.aa2Triplet.put$O$O("n", "ASN");
C$.aa2Triplet.put$O$O("D", "ASP");
C$.aa2Triplet.put$O$O("d", "ASP");
C$.aa2Triplet.put$O$O("C", "CYS");
C$.aa2Triplet.put$O$O("c", "CYS");
C$.aa2Triplet.put$O$O("Q", "GLN");
C$.aa2Triplet.put$O$O("q", "GLN");
C$.aa2Triplet.put$O$O("E", "GLU");
C$.aa2Triplet.put$O$O("e", "GLU");
C$.aa2Triplet.put$O$O("G", "GLY");
C$.aa2Triplet.put$O$O("g", "GLY");
C$.aa2Triplet.put$O$O("H", "HIS");
C$.aa2Triplet.put$O$O("h", "HIS");
C$.aa2Triplet.put$O$O("I", "ILE");
C$.aa2Triplet.put$O$O("i", "ILE");
C$.aa2Triplet.put$O$O("L", "LEU");
C$.aa2Triplet.put$O$O("l", "LEU");
C$.aa2Triplet.put$O$O("K", "LYS");
C$.aa2Triplet.put$O$O("k", "LYS");
C$.aa2Triplet.put$O$O("M", "MET");
C$.aa2Triplet.put$O$O("m", "MET");
C$.aa2Triplet.put$O$O("F", "PHE");
C$.aa2Triplet.put$O$O("f", "PHE");
C$.aa2Triplet.put$O$O("P", "PRO");
C$.aa2Triplet.put$O$O("p", "PRO");
C$.aa2Triplet.put$O$O("S", "SER");
C$.aa2Triplet.put$O$O("s", "SER");
C$.aa2Triplet.put$O$O("T", "THR");
C$.aa2Triplet.put$O$O("t", "THR");
C$.aa2Triplet.put$O$O("W", "TRP");
C$.aa2Triplet.put$O$O("w", "TRP");
C$.aa2Triplet.put$O$O("Y", "TYR");
C$.aa2Triplet.put$O$O("y", "TYR");
C$.aa2Triplet.put$O$O("V", "VAL");
C$.aa2Triplet.put$O$O("v", "VAL");
};
C$.aa=Clazz.array(String, -1, ["A", "R", "N", "D", "C", "Q", "E", "G", "H", "I", "L", "K", "M", "F", "P", "S", "T", "W", "Y", "V", "B", "Z", "X", "_", "*", ".", " ", "U"]);
C$.midBlue=Clazz.new_($I$(2,1).c$$I$I$I,[100, 100, 255]);
C$.taylor=Clazz.array($I$(2), -1, [Clazz.new_($I$(2,1).c$$I$I$I,[204, 255, 0]), Clazz.new_($I$(2,1).c$$I$I$I,[0, 0, 255]), Clazz.new_($I$(2,1).c$$I$I$I,[204, 0, 255]), Clazz.new_($I$(2,1).c$$I$I$I,[255, 0, 0]), Clazz.new_($I$(2,1).c$$I$I$I,[255, 255, 0]), Clazz.new_($I$(2,1).c$$I$I$I,[255, 0, 204]), Clazz.new_($I$(2,1).c$$I$I$I,[255, 0, 102]), Clazz.new_($I$(2,1).c$$I$I$I,[255, 153, 0]), Clazz.new_($I$(2,1).c$$I$I$I,[0, 102, 255]), Clazz.new_($I$(2,1).c$$I$I$I,[102, 255, 0]), Clazz.new_($I$(2,1).c$$I$I$I,[51, 255, 0]), Clazz.new_($I$(2,1).c$$I$I$I,[102, 0, 255]), Clazz.new_($I$(2,1).c$$I$I$I,[0, 255, 0]), Clazz.new_($I$(2,1).c$$I$I$I,[0, 255, 102]), Clazz.new_($I$(2,1).c$$I$I$I,[255, 204, 0]), Clazz.new_($I$(2,1).c$$I$I$I,[255, 51, 0]), Clazz.new_($I$(2,1).c$$I$I$I,[255, 102, 0]), Clazz.new_($I$(2,1).c$$I$I$I,[0, 204, 255]), Clazz.new_($I$(2,1).c$$I$I$I,[0, 255, 204]), Clazz.new_($I$(2,1).c$$I$I$I,[153, 255, 0]), $I$(2).white, $I$(2).white, $I$(2).white, $I$(2).white, $I$(2).white, $I$(2).white]);
C$.nucleotide=Clazz.array($I$(2), -1, [Clazz.new_($I$(2,1).c$$I$I$I,[100, 247, 63]), Clazz.new_($I$(2,1).c$$I$I$I,[255, 179, 64]), Clazz.new_($I$(2,1).c$$I$I$I,[235, 65, 60]), Clazz.new_($I$(2,1).c$$I$I$I,[60, 136, 238]), Clazz.new_($I$(2,1).c$$I$I$I,[60, 136, 238]), $I$(2).white, $I$(2).white, $I$(2).white, $I$(2).white, $I$(2).white, $I$(2).white]);
C$.purinepyrimidine=Clazz.array($I$(2), -1, [Clazz.new_($I$(2,1).c$$I$I$I,[255, 131, 250]), Clazz.new_($I$(2,1).c$$I$I$I,[64, 224, 208]), $I$(2).white, $I$(2).white]);
C$.zappo=Clazz.array($I$(2), -1, [$I$(2).pink, C$.midBlue, $I$(2).green, $I$(2).red, $I$(2).yellow, $I$(2).green, $I$(2).red, $I$(2).magenta, C$.midBlue, $I$(2).pink, $I$(2).pink, C$.midBlue, $I$(2).pink, $I$(2).orange, $I$(2).magenta, $I$(2).green, $I$(2).green, $I$(2).orange, $I$(2).orange, $I$(2).pink, $I$(2).white, $I$(2).white, $I$(2).white, $I$(2).white, $I$(2).white, $I$(2).white, $I$(2).white]);
C$.hyd2=Clazz.array(Double.TYPE, -1, [0.62, 0.29, -0.9, -0.74, 1.19, 0.48, -0.4, 1.38, -1.5, 1.06, 0.64, -0.78, 0.12, -0.85, -2.53, -0.18, -0.05, 1.08, 0.81, 0.0, 0.26, 0.0, 0.0]);
C$.helix=Clazz.array(Double.TYPE, -1, [1.42, 0.98, 0.67, 1.01, 0.7, 1.11, 1.51, 0.57, 1.0, 1.08, 1.21, 1.16, 1.45, 1.13, 0.57, 0.77, 0.83, 1.08, 0.69, 1.06, 0.84, 1.31, 1.0, 0.0]);
C$.strand=Clazz.array(Double.TYPE, -1, [0.83, 0.93, 0.89, 0.54, 1.19, 1.1, 0.37, 0.75, 0.87, 1.6, 1.3, 0.74, 1.05, 1.38, 0.55, 0.75, 1.19, 1.37, 1.47, 1.7, 0.72, 0.74, 1.0, 0.0]);
C$.turn=Clazz.array(Double.TYPE, -1, [0.66, 0.95, 1.56, 1.46, 1.19, 0.98, 0.74, 1.56, 0.95, 0.47, 0.59, 1.01, 0.6, 0.6, 1.52, 1.43, 0.96, 0.96, 1.14, 0.5, 1.51, 0.86, 1.0, 0, 0]);
C$.buried=Clazz.array(Double.TYPE, -1, [1.7, 0.1, 0.4, 0.4, 4.6, 0.3, 0.3, 1.8, 0.8, 3.1, 2.4, 0.05, 1.9, 2.2, 0.6, 0.8, 0.7, 1.6, 0.5, 2.9, 0.4, 0.3, 1.358, 0.0]);
C$.hyd=Clazz.array(Double.TYPE, -1, [1.8, -4.5, -3.5, -3.5, 2.5, -3.5, -3.5, -0.4, -3.2, 4.5, 3.8, -3.9, 1.9, 2.8, -1.6, -0.8, -0.7, -0.9, -1.3, 4.2, -3.5, -3.5, -0.49, 0.0]);
C$.STOP="STOP";
C$.STOP_CODONS=$I$(3,"asList$OA",[Clazz.array(String, -1, ["TGA", "TAA", "TAG"])]);
C$.START="ATG";
C$.propHash=Clazz.new_($I$(4,1));
C$.hydrophobic=Clazz.new_($I$(4,1));
C$.polar=Clazz.new_($I$(4,1));
C$.small=Clazz.new_($I$(4,1));
C$.positive=Clazz.new_($I$(4,1));
C$.negative=Clazz.new_($I$(4,1));
C$.charged=Clazz.new_($I$(4,1));
C$.aromatic=Clazz.new_($I$(4,1));
C$.aliphatic=Clazz.new_($I$(4,1));
C$.tiny=Clazz.new_($I$(4,1));
C$.proline=Clazz.new_($I$(4,1));
{
C$.hydrophobic.put$O$O("I", C$.ONE);
C$.hydrophobic.put$O$O("L", C$.ONE);
C$.hydrophobic.put$O$O("V", C$.ONE);
C$.hydrophobic.put$O$O("C", C$.ONE);
C$.hydrophobic.put$O$O("A", C$.ONE);
C$.hydrophobic.put$O$O("G", C$.ONE);
C$.hydrophobic.put$O$O("M", C$.ONE);
C$.hydrophobic.put$O$O("F", C$.ONE);
C$.hydrophobic.put$O$O("Y", C$.ONE);
C$.hydrophobic.put$O$O("W", C$.ONE);
C$.hydrophobic.put$O$O("H", C$.ONE);
C$.hydrophobic.put$O$O("K", C$.ONE);
C$.hydrophobic.put$O$O("X", C$.ONE);
C$.hydrophobic.put$O$O("-", C$.ONE);
C$.hydrophobic.put$O$O("*", C$.ONE);
C$.hydrophobic.put$O$O("R", C$.ZERO);
C$.hydrophobic.put$O$O("E", C$.ZERO);
C$.hydrophobic.put$O$O("Q", C$.ZERO);
C$.hydrophobic.put$O$O("D", C$.ZERO);
C$.hydrophobic.put$O$O("N", C$.ZERO);
C$.hydrophobic.put$O$O("S", C$.ZERO);
C$.hydrophobic.put$O$O("T", C$.ONE);
C$.hydrophobic.put$O$O("P", C$.ZERO);
};
{
C$.polar.put$O$O("Y", C$.ONE);
C$.polar.put$O$O("W", C$.ONE);
C$.polar.put$O$O("H", C$.ONE);
C$.polar.put$O$O("K", C$.ONE);
C$.polar.put$O$O("R", C$.ONE);
C$.polar.put$O$O("E", C$.ONE);
C$.polar.put$O$O("Q", C$.ONE);
C$.polar.put$O$O("D", C$.ONE);
C$.polar.put$O$O("N", C$.ONE);
C$.polar.put$O$O("S", C$.ONE);
C$.polar.put$O$O("T", C$.ONE);
C$.polar.put$O$O("X", C$.ONE);
C$.polar.put$O$O("-", C$.ONE);
C$.polar.put$O$O("*", C$.ONE);
C$.polar.put$O$O("I", C$.ZERO);
C$.polar.put$O$O("L", C$.ZERO);
C$.polar.put$O$O("V", C$.ZERO);
C$.polar.put$O$O("C", C$.ZERO);
C$.polar.put$O$O("A", C$.ZERO);
C$.polar.put$O$O("G", C$.ZERO);
C$.polar.put$O$O("M", C$.ZERO);
C$.polar.put$O$O("F", C$.ZERO);
C$.polar.put$O$O("P", C$.ZERO);
};
{
C$.small.put$O$O("I", C$.ZERO);
C$.small.put$O$O("L", C$.ZERO);
C$.small.put$O$O("V", C$.ONE);
C$.small.put$O$O("C", C$.ONE);
C$.small.put$O$O("A", C$.ONE);
C$.small.put$O$O("G", C$.ONE);
C$.small.put$O$O("M", C$.ZERO);
C$.small.put$O$O("F", C$.ZERO);
C$.small.put$O$O("Y", C$.ZERO);
C$.small.put$O$O("W", C$.ZERO);
C$.small.put$O$O("H", C$.ZERO);
C$.small.put$O$O("K", C$.ZERO);
C$.small.put$O$O("R", C$.ZERO);
C$.small.put$O$O("E", C$.ZERO);
C$.small.put$O$O("Q", C$.ZERO);
C$.small.put$O$O("D", C$.ONE);
C$.small.put$O$O("N", C$.ONE);
C$.small.put$O$O("S", C$.ONE);
C$.small.put$O$O("T", C$.ONE);
C$.small.put$O$O("P", C$.ONE);
C$.small.put$O$O("-", C$.ONE);
C$.small.put$O$O("*", C$.ONE);
};
{
C$.positive.put$O$O("I", C$.ZERO);
C$.positive.put$O$O("L", C$.ZERO);
C$.positive.put$O$O("V", C$.ZERO);
C$.positive.put$O$O("C", C$.ZERO);
C$.positive.put$O$O("A", C$.ZERO);
C$.positive.put$O$O("G", C$.ZERO);
C$.positive.put$O$O("M", C$.ZERO);
C$.positive.put$O$O("F", C$.ZERO);
C$.positive.put$O$O("Y", C$.ZERO);
C$.positive.put$O$O("W", C$.ZERO);
C$.positive.put$O$O("H", C$.ONE);
C$.positive.put$O$O("K", C$.ONE);
C$.positive.put$O$O("R", C$.ONE);
C$.positive.put$O$O("E", C$.ZERO);
C$.positive.put$O$O("Q", C$.ZERO);
C$.positive.put$O$O("D", C$.ZERO);
C$.positive.put$O$O("N", C$.ZERO);
C$.positive.put$O$O("S", C$.ZERO);
C$.positive.put$O$O("T", C$.ZERO);
C$.positive.put$O$O("P", C$.ZERO);
C$.positive.put$O$O("-", C$.ONE);
C$.positive.put$O$O("*", C$.ONE);
};
{
C$.negative.put$O$O("I", C$.ZERO);
C$.negative.put$O$O("L", C$.ZERO);
C$.negative.put$O$O("V", C$.ZERO);
C$.negative.put$O$O("C", C$.ZERO);
C$.negative.put$O$O("A", C$.ZERO);
C$.negative.put$O$O("G", C$.ZERO);
C$.negative.put$O$O("M", C$.ZERO);
C$.negative.put$O$O("F", C$.ZERO);
C$.negative.put$O$O("Y", C$.ZERO);
C$.negative.put$O$O("W", C$.ZERO);
C$.negative.put$O$O("H", C$.ZERO);
C$.negative.put$O$O("K", C$.ZERO);
C$.negative.put$O$O("R", C$.ZERO);
C$.negative.put$O$O("E", C$.ONE);
C$.negative.put$O$O("Q", C$.ZERO);
C$.negative.put$O$O("D", C$.ONE);
C$.negative.put$O$O("N", C$.ZERO);
C$.negative.put$O$O("S", C$.ZERO);
C$.negative.put$O$O("T", C$.ZERO);
C$.negative.put$O$O("P", C$.ZERO);
C$.negative.put$O$O("-", C$.ONE);
C$.negative.put$O$O("*", C$.ONE);
};
{
C$.charged.put$O$O("I", C$.ZERO);
C$.charged.put$O$O("L", C$.ZERO);
C$.charged.put$O$O("V", C$.ZERO);
C$.charged.put$O$O("C", C$.ZERO);
C$.charged.put$O$O("A", C$.ZERO);
C$.charged.put$O$O("G", C$.ZERO);
C$.charged.put$O$O("M", C$.ZERO);
C$.charged.put$O$O("F", C$.ZERO);
C$.charged.put$O$O("Y", C$.ZERO);
C$.charged.put$O$O("W", C$.ZERO);
C$.charged.put$O$O("H", C$.ONE);
C$.charged.put$O$O("K", C$.ONE);
C$.charged.put$O$O("R", C$.ONE);
C$.charged.put$O$O("E", C$.ONE);
C$.charged.put$O$O("Q", C$.ZERO);
C$.charged.put$O$O("D", C$.ONE);
C$.charged.put$O$O("N", C$.ZERO);
C$.charged.put$O$O("S", C$.ZERO);
C$.charged.put$O$O("T", C$.ZERO);
C$.charged.put$O$O("P", C$.ZERO);
C$.charged.put$O$O("-", C$.ONE);
C$.charged.put$O$O("*", C$.ONE);
};
{
C$.aromatic.put$O$O("I", C$.ZERO);
C$.aromatic.put$O$O("L", C$.ZERO);
C$.aromatic.put$O$O("V", C$.ZERO);
C$.aromatic.put$O$O("C", C$.ZERO);
C$.aromatic.put$O$O("A", C$.ZERO);
C$.aromatic.put$O$O("G", C$.ZERO);
C$.aromatic.put$O$O("M", C$.ZERO);
C$.aromatic.put$O$O("F", C$.ONE);
C$.aromatic.put$O$O("Y", C$.ONE);
C$.aromatic.put$O$O("W", C$.ONE);
C$.aromatic.put$O$O("H", C$.ONE);
C$.aromatic.put$O$O("K", C$.ZERO);
C$.aromatic.put$O$O("R", C$.ZERO);
C$.aromatic.put$O$O("E", C$.ZERO);
C$.aromatic.put$O$O("Q", C$.ZERO);
C$.aromatic.put$O$O("D", C$.ZERO);
C$.aromatic.put$O$O("N", C$.ZERO);
C$.aromatic.put$O$O("S", C$.ZERO);
C$.aromatic.put$O$O("T", C$.ZERO);
C$.aromatic.put$O$O("P", C$.ZERO);
C$.aromatic.put$O$O("-", C$.ONE);
C$.aromatic.put$O$O("*", C$.ONE);
};
{
C$.aliphatic.put$O$O("I", C$.ONE);
C$.aliphatic.put$O$O("L", C$.ONE);
C$.aliphatic.put$O$O("V", C$.ONE);
C$.aliphatic.put$O$O("C", C$.ZERO);
C$.aliphatic.put$O$O("A", C$.ZERO);
C$.aliphatic.put$O$O("G", C$.ZERO);
C$.aliphatic.put$O$O("M", C$.ZERO);
C$.aliphatic.put$O$O("F", C$.ZERO);
C$.aliphatic.put$O$O("Y", C$.ZERO);
C$.aliphatic.put$O$O("W", C$.ZERO);
C$.aliphatic.put$O$O("H", C$.ZERO);
C$.aliphatic.put$O$O("K", C$.ZERO);
C$.aliphatic.put$O$O("R", C$.ZERO);
C$.aliphatic.put$O$O("E", C$.ZERO);
C$.aliphatic.put$O$O("Q", C$.ZERO);
C$.aliphatic.put$O$O("D", C$.ZERO);
C$.aliphatic.put$O$O("N", C$.ZERO);
C$.aliphatic.put$O$O("S", C$.ZERO);
C$.aliphatic.put$O$O("T", C$.ZERO);
C$.aliphatic.put$O$O("P", C$.ZERO);
C$.aliphatic.put$O$O("-", C$.ONE);
C$.aliphatic.put$O$O("*", C$.ONE);
};
{
C$.tiny.put$O$O("I", C$.ZERO);
C$.tiny.put$O$O("L", C$.ZERO);
C$.tiny.put$O$O("V", C$.ZERO);
C$.tiny.put$O$O("C", C$.ZERO);
C$.tiny.put$O$O("A", C$.ONE);
C$.tiny.put$O$O("G", C$.ONE);
C$.tiny.put$O$O("M", C$.ZERO);
C$.tiny.put$O$O("F", C$.ZERO);
C$.tiny.put$O$O("Y", C$.ZERO);
C$.tiny.put$O$O("W", C$.ZERO);
C$.tiny.put$O$O("H", C$.ZERO);
C$.tiny.put$O$O("K", C$.ZERO);
C$.tiny.put$O$O("R", C$.ZERO);
C$.tiny.put$O$O("E", C$.ZERO);
C$.tiny.put$O$O("Q", C$.ZERO);
C$.tiny.put$O$O("D", C$.ZERO);
C$.tiny.put$O$O("N", C$.ZERO);
C$.tiny.put$O$O("S", C$.ONE);
C$.tiny.put$O$O("T", C$.ZERO);
C$.tiny.put$O$O("P", C$.ZERO);
C$.tiny.put$O$O("-", C$.ONE);
C$.tiny.put$O$O("*", C$.ONE);
};
{
C$.proline.put$O$O("I", C$.ZERO);
C$.proline.put$O$O("L", C$.ZERO);
C$.proline.put$O$O("V", C$.ZERO);
C$.proline.put$O$O("C", C$.ZERO);
C$.proline.put$O$O("A", C$.ZERO);
C$.proline.put$O$O("G", C$.ZERO);
C$.proline.put$O$O("M", C$.ZERO);
C$.proline.put$O$O("F", C$.ZERO);
C$.proline.put$O$O("Y", C$.ZERO);
C$.proline.put$O$O("W", C$.ZERO);
C$.proline.put$O$O("H", C$.ZERO);
C$.proline.put$O$O("K", C$.ZERO);
C$.proline.put$O$O("R", C$.ZERO);
C$.proline.put$O$O("E", C$.ZERO);
C$.proline.put$O$O("Q", C$.ZERO);
C$.proline.put$O$O("D", C$.ZERO);
C$.proline.put$O$O("N", C$.ZERO);
C$.proline.put$O$O("S", C$.ZERO);
C$.proline.put$O$O("T", C$.ZERO);
C$.proline.put$O$O("P", C$.ONE);
C$.proline.put$O$O("-", C$.ONE);
C$.proline.put$O$O("*", C$.ONE);
};
{
C$.propHash.put$O$O("hydrophobic", C$.hydrophobic);
C$.propHash.put$O$O("small", C$.small);
C$.propHash.put$O$O("positive", C$.positive);
C$.propHash.put$O$O("negative", C$.negative);
C$.propHash.put$O$O("charged", C$.charged);
C$.propHash.put$O$O("aromatic", C$.aromatic);
C$.propHash.put$O$O("aliphatic", C$.aliphatic);
C$.propHash.put$O$O("tiny", C$.tiny);
C$.propHash.put$O$O("proline", C$.proline);
C$.propHash.put$O$O("polar", C$.polar);
};
{
var propMatrixF=Clazz.array(Integer.TYPE, [23, 23]);
var propMatrixPos=Clazz.array(Integer.TYPE, [23, 23]);
var propMatrixEpos=Clazz.array(Integer.TYPE, [23, 23]);
for (var i=0; i < 23; i++) {
var maxF=0;
var maxP=0;
var maxEP=0;
var ic="";
if (C$.aa.length > i) {
ic+=C$.aa[i];
} else {
ic="-";
}for (var j=i + 1; j < 23; j++) {
var jc="";
if (C$.aa.length > j) {
jc+=C$.aa[j];
} else {
jc="-";
}propMatrixF[i][j]=0;
propMatrixPos[i][j]=0;
propMatrixEpos[i][j]=0;
for (var ph, $ph = C$.propHash.keySet$().iterator$(); $ph.hasNext$()&&((ph=($ph.next$())),1);) {
var pph=C$.propHash.get$O(ph);
if (pph.get$O(ic) != null  && pph.get$O(jc) != null  ) {
var icp=pph.get$O(ic).intValue$();
var jcp=pph.get$O(jc).intValue$();
propMatrixPos[i][j]+=icp == jcp && icp > 0  ? 2 : 0;
propMatrixPos[j][i]+=icp == jcp && icp > 0  ? 2 : 0;
propMatrixF[i][j]+=icp == jcp ? 2 : 0;
propMatrixF[j][i]+=icp == jcp ? 2 : 0;
propMatrixEpos[i][j]+=icp == jcp ? (1 + icp * 2) : 0;
propMatrixEpos[j][i]+=icp == jcp ? (1 + icp * 2) : 0;
}}
if (maxF < propMatrixF[i][j]) {
maxF=propMatrixF[i][j];
}if (maxP < propMatrixPos[i][j]) {
maxP=propMatrixPos[i][j];
}if (maxEP < propMatrixEpos[i][j]) {
maxEP=propMatrixEpos[i][j];
}}
propMatrixF[i][i]=maxF;
propMatrixPos[i][i]=maxP;
propMatrixEpos[i][i]=maxEP;
}
};
{
C$.toDssp3State=Clazz.array(Character.TYPE, [9]);
$I$(3).fill$CA$C(C$.toDssp3State, " ");
C$.toDssp3State[1]="E";
C$.toDssp3State[4]="E";
C$.toDssp3State[6]="H";
C$.toDssp3State[7]="H";
C$.toDssp3State[8]="H";
};
{
C$.modifications.put$O$O("MSE", "MET");
C$.modifications.put$O$O("00C", "CYS");
C$.modifications.put$O$O("01W", "XAA");
C$.modifications.put$O$O("02K", "ALA");
C$.modifications.put$O$O("03Y", "CYS");
C$.modifications.put$O$O("07O", "CYS");
C$.modifications.put$O$O("08P", "CYS");
C$.modifications.put$O$O("0A0", "ASP");
C$.modifications.put$O$O("0A1", "TYR");
C$.modifications.put$O$O("0A2", "LYS");
C$.modifications.put$O$O("0A8", "CYS");
C$.modifications.put$O$O("0AA", "VAL");
C$.modifications.put$O$O("0AB", "VAL");
C$.modifications.put$O$O("0AC", "GLY");
C$.modifications.put$O$O("0AD", "GLY");
C$.modifications.put$O$O("0AF", "TRP");
C$.modifications.put$O$O("0AG", "LEU");
C$.modifications.put$O$O("0AH", "SER");
C$.modifications.put$O$O("0AK", "ASP");
C$.modifications.put$O$O("0AM", "ALA");
C$.modifications.put$O$O("0AP", "CYS");
C$.modifications.put$O$O("0AU", "UR3");
C$.modifications.put$O$O("0AV", "ALA");
C$.modifications.put$O$O("0AZ", "PRO");
C$.modifications.put$O$O("0BN", "PHE");
C$.modifications.put$O$O("0C ", "CYS");
C$.modifications.put$O$O("0CS", "ALA");
C$.modifications.put$O$O("0DC", "CYS");
C$.modifications.put$O$O("0DG", "GLY");
C$.modifications.put$O$O("0DT", "THR");
C$.modifications.put$O$O("0FL", "ALA");
C$.modifications.put$O$O("0G ", "GLY");
C$.modifications.put$O$O("0NC", "ALA");
C$.modifications.put$O$O("0SP", "ALA");
C$.modifications.put$O$O("0U ", "UR3");
C$.modifications.put$O$O("0YG", "YG");
C$.modifications.put$O$O("10C", "CYS");
C$.modifications.put$O$O("125", "UR3");
C$.modifications.put$O$O("126", "UR3");
C$.modifications.put$O$O("127", "UR3");
C$.modifications.put$O$O("128", "ASN");
C$.modifications.put$O$O("12A", "ALA");
C$.modifications.put$O$O("143", "CYS");
C$.modifications.put$O$O("175", "ASG");
C$.modifications.put$O$O("193", "XAA");
C$.modifications.put$O$O("1AP", "ALA");
C$.modifications.put$O$O("1MA", "ALA");
C$.modifications.put$O$O("1MG", "GLY");
C$.modifications.put$O$O("1PA", "PHE");
C$.modifications.put$O$O("1PI", "ALA");
C$.modifications.put$O$O("1PR", "ASN");
C$.modifications.put$O$O("1SC", "CYS");
C$.modifications.put$O$O("1TQ", "TRP");
C$.modifications.put$O$O("1TY", "TYR");
C$.modifications.put$O$O("1X6", "SER");
C$.modifications.put$O$O("200", "PHE");
C$.modifications.put$O$O("23F", "PHE");
C$.modifications.put$O$O("23S", "XAA");
C$.modifications.put$O$O("26B", "THR");
C$.modifications.put$O$O("2AD", "XAA");
C$.modifications.put$O$O("2AG", "ALA");
C$.modifications.put$O$O("2AO", "XAA");
C$.modifications.put$O$O("2AR", "ALA");
C$.modifications.put$O$O("2AS", "XAA");
C$.modifications.put$O$O("2AT", "THR");
C$.modifications.put$O$O("2AU", "UR3");
C$.modifications.put$O$O("2BD", "ILE");
C$.modifications.put$O$O("2BT", "THR");
C$.modifications.put$O$O("2BU", "ALA");
C$.modifications.put$O$O("2CO", "CYS");
C$.modifications.put$O$O("2DA", "ALA");
C$.modifications.put$O$O("2DF", "ASN");
C$.modifications.put$O$O("2DM", "ASN");
C$.modifications.put$O$O("2DO", "XAA");
C$.modifications.put$O$O("2DT", "THR");
C$.modifications.put$O$O("2EG", "GLY");
C$.modifications.put$O$O("2FE", "ASN");
C$.modifications.put$O$O("2FI", "ASN");
C$.modifications.put$O$O("2FM", "MET");
C$.modifications.put$O$O("2GT", "THR");
C$.modifications.put$O$O("2HF", "HIS");
C$.modifications.put$O$O("2LU", "LEU");
C$.modifications.put$O$O("2MA", "ALA");
C$.modifications.put$O$O("2MG", "GLY");
C$.modifications.put$O$O("2ML", "LEU");
C$.modifications.put$O$O("2MR", "ARG");
C$.modifications.put$O$O("2MT", "PRO");
C$.modifications.put$O$O("2MU", "UR3");
C$.modifications.put$O$O("2NT", "THR");
C$.modifications.put$O$O("2OM", "UR3");
C$.modifications.put$O$O("2OT", "THR");
C$.modifications.put$O$O("2PI", "XAA");
C$.modifications.put$O$O("2PR", "GLY");
C$.modifications.put$O$O("2SA", "ASN");
C$.modifications.put$O$O("2SI", "XAA");
C$.modifications.put$O$O("2ST", "THR");
C$.modifications.put$O$O("2TL", "THR");
C$.modifications.put$O$O("2TY", "TYR");
C$.modifications.put$O$O("2VA", "VAL");
C$.modifications.put$O$O("2XA", "CYS");
C$.modifications.put$O$O("32S", "XAA");
C$.modifications.put$O$O("32T", "XAA");
C$.modifications.put$O$O("3AH", "HIS");
C$.modifications.put$O$O("3AR", "XAA");
C$.modifications.put$O$O("3CF", "PHE");
C$.modifications.put$O$O("3DA", "ALA");
C$.modifications.put$O$O("3DR", "ASN");
C$.modifications.put$O$O("3GA", "ALA");
C$.modifications.put$O$O("3MD", "ASP");
C$.modifications.put$O$O("3ME", "UR3");
C$.modifications.put$O$O("3NF", "TYR");
C$.modifications.put$O$O("3QN", "LYS");
C$.modifications.put$O$O("3TY", "XAA");
C$.modifications.put$O$O("3XH", "GLY");
C$.modifications.put$O$O("4AC", "ASN");
C$.modifications.put$O$O("4BF", "TYR");
C$.modifications.put$O$O("4CF", "PHE");
C$.modifications.put$O$O("4CY", "MET");
C$.modifications.put$O$O("4DP", "TRP");
C$.modifications.put$O$O("4F3", "GYG");
C$.modifications.put$O$O("4FB", "PRO");
C$.modifications.put$O$O("4FW", "TRP");
C$.modifications.put$O$O("4HT", "TRP");
C$.modifications.put$O$O("4IN", "TRP");
C$.modifications.put$O$O("4MF", "ASN");
C$.modifications.put$O$O("4MM", "XAA");
C$.modifications.put$O$O("4OC", "CYS");
C$.modifications.put$O$O("4PC", "CYS");
C$.modifications.put$O$O("4PD", "CYS");
C$.modifications.put$O$O("4PE", "CYS");
C$.modifications.put$O$O("4PH", "PHE");
C$.modifications.put$O$O("4SC", "CYS");
C$.modifications.put$O$O("4SU", "UR3");
C$.modifications.put$O$O("4TA", "ASN");
C$.modifications.put$O$O("4U7", "ALA");
C$.modifications.put$O$O("56A", "HIS");
C$.modifications.put$O$O("5AA", "ALA");
C$.modifications.put$O$O("5AB", "ALA");
C$.modifications.put$O$O("5AT", "THR");
C$.modifications.put$O$O("5BU", "UR3");
C$.modifications.put$O$O("5CG", "GLY");
C$.modifications.put$O$O("5CM", "CYS");
C$.modifications.put$O$O("5CS", "CYS");
C$.modifications.put$O$O("5FA", "ALA");
C$.modifications.put$O$O("5FC", "CYS");
C$.modifications.put$O$O("5FU", "UR3");
C$.modifications.put$O$O("5HP", "GLU");
C$.modifications.put$O$O("5HT", "THR");
C$.modifications.put$O$O("5HU", "UR3");
C$.modifications.put$O$O("5IC", "CYS");
C$.modifications.put$O$O("5IT", "THR");
C$.modifications.put$O$O("5IU", "UR3");
C$.modifications.put$O$O("5MC", "CYS");
C$.modifications.put$O$O("5MD", "ASN");
C$.modifications.put$O$O("5MU", "UR3");
C$.modifications.put$O$O("5NC", "CYS");
C$.modifications.put$O$O("5PC", "CYS");
C$.modifications.put$O$O("5PY", "THR");
C$.modifications.put$O$O("5SE", "UR3");
C$.modifications.put$O$O("5ZA", "TWG");
C$.modifications.put$O$O("64T", "THR");
C$.modifications.put$O$O("6CL", "LYS");
C$.modifications.put$O$O("6CT", "THR");
C$.modifications.put$O$O("6CW", "TRP");
C$.modifications.put$O$O("6HA", "ALA");
C$.modifications.put$O$O("6HC", "CYS");
C$.modifications.put$O$O("6HG", "GLY");
C$.modifications.put$O$O("6HN", "LYS");
C$.modifications.put$O$O("6HT", "THR");
C$.modifications.put$O$O("6IA", "ALA");
C$.modifications.put$O$O("6MA", "ALA");
C$.modifications.put$O$O("6MC", "ALA");
C$.modifications.put$O$O("6MI", "ASN");
C$.modifications.put$O$O("6MT", "ALA");
C$.modifications.put$O$O("6MZ", "ASN");
C$.modifications.put$O$O("6OG", "GLY");
C$.modifications.put$O$O("70U", "UR3");
C$.modifications.put$O$O("7DA", "ALA");
C$.modifications.put$O$O("7GU", "GLY");
C$.modifications.put$O$O("7JA", "ILE");
C$.modifications.put$O$O("7MG", "GLY");
C$.modifications.put$O$O("8AN", "ALA");
C$.modifications.put$O$O("8FG", "GLY");
C$.modifications.put$O$O("8MG", "GLY");
C$.modifications.put$O$O("8OG", "GLY");
C$.modifications.put$O$O("9NE", "GLU");
C$.modifications.put$O$O("9NF", "PHE");
C$.modifications.put$O$O("9NR", "ARG");
C$.modifications.put$O$O("9NV", "VAL");
C$.modifications.put$O$O("A  ", "ALA");
C$.modifications.put$O$O("A1P", "ASN");
C$.modifications.put$O$O("A23", "ALA");
C$.modifications.put$O$O("A2L", "ALA");
C$.modifications.put$O$O("A2M", "ALA");
C$.modifications.put$O$O("A34", "ALA");
C$.modifications.put$O$O("A35", "ALA");
C$.modifications.put$O$O("A38", "ALA");
C$.modifications.put$O$O("A39", "ALA");
C$.modifications.put$O$O("A3A", "ALA");
C$.modifications.put$O$O("A3P", "ALA");
C$.modifications.put$O$O("A40", "ALA");
C$.modifications.put$O$O("A43", "ALA");
C$.modifications.put$O$O("A44", "ALA");
C$.modifications.put$O$O("A47", "ALA");
C$.modifications.put$O$O("A5L", "ALA");
C$.modifications.put$O$O("A5M", "CYS");
C$.modifications.put$O$O("A5N", "ASN");
C$.modifications.put$O$O("A5O", "ALA");
C$.modifications.put$O$O("A66", "XAA");
C$.modifications.put$O$O("AA3", "ALA");
C$.modifications.put$O$O("AA4", "ALA");
C$.modifications.put$O$O("AAR", "ARG");
C$.modifications.put$O$O("AB7", "XAA");
C$.modifications.put$O$O("ABA", "ALA");
C$.modifications.put$O$O("ABR", "ALA");
C$.modifications.put$O$O("ABS", "ALA");
C$.modifications.put$O$O("ABT", "ASN");
C$.modifications.put$O$O("ACB", "ASP");
C$.modifications.put$O$O("ACL", "ARG");
C$.modifications.put$O$O("AD2", "ALA");
C$.modifications.put$O$O("ADD", "XAA");
C$.modifications.put$O$O("ADX", "ASN");
C$.modifications.put$O$O("AEA", "XAA");
C$.modifications.put$O$O("AEI", "ASP");
C$.modifications.put$O$O("AET", "ALA");
C$.modifications.put$O$O("AFA", "ASN");
C$.modifications.put$O$O("AFF", "ASN");
C$.modifications.put$O$O("AFG", "GLY");
C$.modifications.put$O$O("AGM", "ARG");
C$.modifications.put$O$O("AGT", "CYS");
C$.modifications.put$O$O("AHB", "ASN");
C$.modifications.put$O$O("AHH", "XAA");
C$.modifications.put$O$O("AHO", "ALA");
C$.modifications.put$O$O("AHP", "ALA");
C$.modifications.put$O$O("AHS", "XAA");
C$.modifications.put$O$O("AHT", "XAA");
C$.modifications.put$O$O("AIB", "ALA");
C$.modifications.put$O$O("AKL", "ASP");
C$.modifications.put$O$O("AKZ", "ASP");
C$.modifications.put$O$O("ALA", "ALA");
C$.modifications.put$O$O("ALC", "ALA");
C$.modifications.put$O$O("ALM", "ALA");
C$.modifications.put$O$O("ALN", "ALA");
C$.modifications.put$O$O("ALO", "THR");
C$.modifications.put$O$O("ALQ", "XAA");
C$.modifications.put$O$O("ALS", "ALA");
C$.modifications.put$O$O("ALT", "ALA");
C$.modifications.put$O$O("ALV", "ALA");
C$.modifications.put$O$O("ALY", "LYS");
C$.modifications.put$O$O("AN8", "ALA");
C$.modifications.put$O$O("AP7", "ALA");
C$.modifications.put$O$O("APE", "XAA");
C$.modifications.put$O$O("APH", "ALA");
C$.modifications.put$O$O("API", "LYS");
C$.modifications.put$O$O("APK", "LYS");
C$.modifications.put$O$O("APM", "XAA");
C$.modifications.put$O$O("APP", "XAA");
C$.modifications.put$O$O("AR2", "ARG");
C$.modifications.put$O$O("AR4", "GLU");
C$.modifications.put$O$O("AR7", "ARG");
C$.modifications.put$O$O("ARG", "ARG");
C$.modifications.put$O$O("ARM", "ARG");
C$.modifications.put$O$O("ARO", "ARG");
C$.modifications.put$O$O("ARV", "XAA");
C$.modifications.put$O$O("AS ", "ALA");
C$.modifications.put$O$O("AS2", "ASP");
C$.modifications.put$O$O("AS9", "XAA");
C$.modifications.put$O$O("ASA", "ASP");
C$.modifications.put$O$O("ASB", "ASP");
C$.modifications.put$O$O("ASI", "ASP");
C$.modifications.put$O$O("ASK", "ASP");
C$.modifications.put$O$O("ASL", "ASP");
C$.modifications.put$O$O("ASM", "XAA");
C$.modifications.put$O$O("ASN", "ASN");
C$.modifications.put$O$O("ASP", "ASP");
C$.modifications.put$O$O("ASQ", "ASP");
C$.modifications.put$O$O("ASU", "ASN");
C$.modifications.put$O$O("ASX", "ASX");
C$.modifications.put$O$O("ATD", "THR");
C$.modifications.put$O$O("ATL", "THR");
C$.modifications.put$O$O("ATM", "THR");
C$.modifications.put$O$O("AVC", "ALA");
C$.modifications.put$O$O("AVN", "XAA");
C$.modifications.put$O$O("AYA", "ALA");
C$.modifications.put$O$O("AYG", "AYG");
C$.modifications.put$O$O("AZK", "LYS");
C$.modifications.put$O$O("AZS", "SER");
C$.modifications.put$O$O("AZY", "TYR");
C$.modifications.put$O$O("B1F", "PHE");
C$.modifications.put$O$O("B1P", "ASN");
C$.modifications.put$O$O("B2A", "ALA");
C$.modifications.put$O$O("B2F", "PHE");
C$.modifications.put$O$O("B2I", "ILE");
C$.modifications.put$O$O("B2V", "VAL");
C$.modifications.put$O$O("B3A", "ALA");
C$.modifications.put$O$O("B3D", "ASP");
C$.modifications.put$O$O("B3E", "GLU");
C$.modifications.put$O$O("B3K", "LYS");
C$.modifications.put$O$O("B3L", "XAA");
C$.modifications.put$O$O("B3M", "XAA");
C$.modifications.put$O$O("B3Q", "XAA");
C$.modifications.put$O$O("B3S", "SER");
C$.modifications.put$O$O("B3T", "XAA");
C$.modifications.put$O$O("B3U", "HIS");
C$.modifications.put$O$O("B3X", "ASN");
C$.modifications.put$O$O("B3Y", "TYR");
C$.modifications.put$O$O("BB6", "CYS");
C$.modifications.put$O$O("BB7", "CYS");
C$.modifications.put$O$O("BB8", "PHE");
C$.modifications.put$O$O("BB9", "CYS");
C$.modifications.put$O$O("BBC", "CYS");
C$.modifications.put$O$O("BCS", "CYS");
C$.modifications.put$O$O("BE2", "XAA");
C$.modifications.put$O$O("BFD", "ASP");
C$.modifications.put$O$O("BG1", "SER");
C$.modifications.put$O$O("BGM", "GLY");
C$.modifications.put$O$O("BH2", "ASP");
C$.modifications.put$O$O("BHD", "ASP");
C$.modifications.put$O$O("BIF", "PHE");
C$.modifications.put$O$O("BIL", "XAA");
C$.modifications.put$O$O("BIU", "ILE");
C$.modifications.put$O$O("BJH", "XAA");
C$.modifications.put$O$O("BLE", "LEU");
C$.modifications.put$O$O("BLY", "LYS");
C$.modifications.put$O$O("BMP", "ASN");
C$.modifications.put$O$O("BMT", "THR");
C$.modifications.put$O$O("BNN", "PHE");
C$.modifications.put$O$O("BNO", "XAA");
C$.modifications.put$O$O("BOE", "THR");
C$.modifications.put$O$O("BOR", "ARG");
C$.modifications.put$O$O("BPE", "CYS");
C$.modifications.put$O$O("BRU", "UR3");
C$.modifications.put$O$O("BSE", "SER");
C$.modifications.put$O$O("BT5", "ASN");
C$.modifications.put$O$O("BTA", "LEU");
C$.modifications.put$O$O("BTC", "CYS");
C$.modifications.put$O$O("BTR", "TRP");
C$.modifications.put$O$O("BUC", "CYS");
C$.modifications.put$O$O("BUG", "VAL");
C$.modifications.put$O$O("BVP", "UR3");
C$.modifications.put$O$O("BZG", "ASN");
C$.modifications.put$O$O("C  ", "CYS");
C$.modifications.put$O$O("C12", "TYG");
C$.modifications.put$O$O("C1X", "LYS");
C$.modifications.put$O$O("C25", "CYS");
C$.modifications.put$O$O("C2L", "CYS");
C$.modifications.put$O$O("C2S", "CYS");
C$.modifications.put$O$O("C31", "CYS");
C$.modifications.put$O$O("C32", "CYS");
C$.modifications.put$O$O("C34", "CYS");
C$.modifications.put$O$O("C36", "CYS");
C$.modifications.put$O$O("C37", "CYS");
C$.modifications.put$O$O("C38", "CYS");
C$.modifications.put$O$O("C3Y", "CYS");
C$.modifications.put$O$O("C42", "CYS");
C$.modifications.put$O$O("C43", "CYS");
C$.modifications.put$O$O("C45", "CYS");
C$.modifications.put$O$O("C46", "CYS");
C$.modifications.put$O$O("C49", "CYS");
C$.modifications.put$O$O("C4R", "CYS");
C$.modifications.put$O$O("C4S", "CYS");
C$.modifications.put$O$O("C5C", "CYS");
C$.modifications.put$O$O("C66", "XAA");
C$.modifications.put$O$O("C6C", "CYS");
C$.modifications.put$O$O("C99", "TFG");
C$.modifications.put$O$O("CAF", "CYS");
C$.modifications.put$O$O("CAL", "XAA");
C$.modifications.put$O$O("CAR", "CYS");
C$.modifications.put$O$O("CAS", "CYS");
C$.modifications.put$O$O("CAV", "XAA");
C$.modifications.put$O$O("CAY", "CYS");
C$.modifications.put$O$O("CB2", "CYS");
C$.modifications.put$O$O("CBR", "CYS");
C$.modifications.put$O$O("CBV", "CYS");
C$.modifications.put$O$O("CCC", "CYS");
C$.modifications.put$O$O("CCL", "LYS");
C$.modifications.put$O$O("CCS", "CYS");
C$.modifications.put$O$O("CCY", "CYG");
C$.modifications.put$O$O("CDE", "XAA");
C$.modifications.put$O$O("CDV", "XAA");
C$.modifications.put$O$O("CDW", "CYS");
C$.modifications.put$O$O("CEA", "CYS");
C$.modifications.put$O$O("CFL", "CYS");
C$.modifications.put$O$O("CFY", "FCYG");
C$.modifications.put$O$O("CG1", "GLY");
C$.modifications.put$O$O("CGA", "GLU");
C$.modifications.put$O$O("CGU", "GLU");
C$.modifications.put$O$O("CH ", "CYS");
C$.modifications.put$O$O("CH6", "MYG");
C$.modifications.put$O$O("CH7", "KYG");
C$.modifications.put$O$O("CHF", "XAA");
C$.modifications.put$O$O("CHG", "XAA");
C$.modifications.put$O$O("CHP", "GLY");
C$.modifications.put$O$O("CHS", "XAA");
C$.modifications.put$O$O("CIR", "ARG");
C$.modifications.put$O$O("CJO", "GYG");
C$.modifications.put$O$O("CLE", "LEU");
C$.modifications.put$O$O("CLG", "LYS");
C$.modifications.put$O$O("CLH", "LYS");
C$.modifications.put$O$O("CLV", "AFG");
C$.modifications.put$O$O("CM0", "ASN");
C$.modifications.put$O$O("CME", "CYS");
C$.modifications.put$O$O("CMH", "CYS");
C$.modifications.put$O$O("CML", "CYS");
C$.modifications.put$O$O("CMR", "CYS");
C$.modifications.put$O$O("CMT", "CYS");
C$.modifications.put$O$O("CNU", "UR3");
C$.modifications.put$O$O("CP1", "CYS");
C$.modifications.put$O$O("CPC", "XAA");
C$.modifications.put$O$O("CPI", "XAA");
C$.modifications.put$O$O("CQR", "GYG");
C$.modifications.put$O$O("CR0", "TLG");
C$.modifications.put$O$O("CR2", "GYG");
C$.modifications.put$O$O("CR5", "GLY");
C$.modifications.put$O$O("CR7", "KYG");
C$.modifications.put$O$O("CR8", "HYG");
C$.modifications.put$O$O("CRF", "TWG");
C$.modifications.put$O$O("CRG", "THG");
C$.modifications.put$O$O("CRK", "MYG");
C$.modifications.put$O$O("CRO", "GYG");
C$.modifications.put$O$O("CRQ", "QYG");
C$.modifications.put$O$O("CRU", "EYG");
C$.modifications.put$O$O("CRW", "ASG");
C$.modifications.put$O$O("CRX", "ASG");
C$.modifications.put$O$O("CS0", "CYS");
C$.modifications.put$O$O("CS1", "CYS");
C$.modifications.put$O$O("CS3", "CYS");
C$.modifications.put$O$O("CS4", "CYS");
C$.modifications.put$O$O("CS8", "ASN");
C$.modifications.put$O$O("CSA", "CYS");
C$.modifications.put$O$O("CSB", "CYS");
C$.modifications.put$O$O("CSD", "CYS");
C$.modifications.put$O$O("CSE", "CYS");
C$.modifications.put$O$O("CSF", "CYS");
C$.modifications.put$O$O("CSH", "SHG");
C$.modifications.put$O$O("CSI", "GLY");
C$.modifications.put$O$O("CSJ", "CYS");
C$.modifications.put$O$O("CSL", "CYS");
C$.modifications.put$O$O("CSO", "CYS");
C$.modifications.put$O$O("CSP", "CYS");
C$.modifications.put$O$O("CSR", "CYS");
C$.modifications.put$O$O("CSS", "CYS");
C$.modifications.put$O$O("CSU", "CYS");
C$.modifications.put$O$O("CSW", "CYS");
C$.modifications.put$O$O("CSX", "CYS");
C$.modifications.put$O$O("CSY", "SYG");
C$.modifications.put$O$O("CSZ", "CYS");
C$.modifications.put$O$O("CTE", "TRP");
C$.modifications.put$O$O("CTG", "THR");
C$.modifications.put$O$O("CTH", "THR");
C$.modifications.put$O$O("CUC", "XAA");
C$.modifications.put$O$O("CWR", "SER");
C$.modifications.put$O$O("CXM", "MET");
C$.modifications.put$O$O("CY0", "CYS");
C$.modifications.put$O$O("CY1", "CYS");
C$.modifications.put$O$O("CY3", "CYS");
C$.modifications.put$O$O("CY4", "CYS");
C$.modifications.put$O$O("CYA", "CYS");
C$.modifications.put$O$O("CYD", "CYS");
C$.modifications.put$O$O("CYF", "CYS");
C$.modifications.put$O$O("CYG", "CYS");
C$.modifications.put$O$O("CYJ", "XAA");
C$.modifications.put$O$O("CYM", "CYS");
C$.modifications.put$O$O("CYQ", "CYS");
C$.modifications.put$O$O("CYR", "CYS");
C$.modifications.put$O$O("CYS", "CYS");
C$.modifications.put$O$O("CZ2", "CYS");
C$.modifications.put$O$O("CZO", "GYG");
C$.modifications.put$O$O("CZZ", "CYS");
C$.modifications.put$O$O("D11", "THR");
C$.modifications.put$O$O("D1P", "ASN");
C$.modifications.put$O$O("D3 ", "ASN");
C$.modifications.put$O$O("D33", "ASN");
C$.modifications.put$O$O("D3P", "GLY");
C$.modifications.put$O$O("D3T", "THR");
C$.modifications.put$O$O("D4M", "THR");
C$.modifications.put$O$O("D4P", "XAA");
C$.modifications.put$O$O("DA ", "ALA");
C$.modifications.put$O$O("DA2", "XAA");
C$.modifications.put$O$O("DAB", "ALA");
C$.modifications.put$O$O("DAH", "PHE");
C$.modifications.put$O$O("DAL", "ALA");
C$.modifications.put$O$O("DAR", "ARG");
C$.modifications.put$O$O("DAS", "ASP");
C$.modifications.put$O$O("DBB", "THR");
C$.modifications.put$O$O("DBM", "ASN");
C$.modifications.put$O$O("DBS", "SER");
C$.modifications.put$O$O("DBU", "THR");
C$.modifications.put$O$O("DBY", "TYR");
C$.modifications.put$O$O("DBZ", "ALA");
C$.modifications.put$O$O("DC ", "CYS");
C$.modifications.put$O$O("DC2", "CYS");
C$.modifications.put$O$O("DCG", "GLY");
C$.modifications.put$O$O("DCI", "XAA");
C$.modifications.put$O$O("DCL", "XAA");
C$.modifications.put$O$O("DCT", "CYS");
C$.modifications.put$O$O("DCY", "CYS");
C$.modifications.put$O$O("DDE", "HIS");
C$.modifications.put$O$O("DDG", "GLY");
C$.modifications.put$O$O("DDN", "UR3");
C$.modifications.put$O$O("DDX", "ASN");
C$.modifications.put$O$O("DFC", "CYS");
C$.modifications.put$O$O("DFG", "GLY");
C$.modifications.put$O$O("DFI", "XAA");
C$.modifications.put$O$O("DFO", "XAA");
C$.modifications.put$O$O("DFT", "ASN");
C$.modifications.put$O$O("DG ", "GLY");
C$.modifications.put$O$O("DGH", "GLY");
C$.modifications.put$O$O("DGI", "GLY");
C$.modifications.put$O$O("DGL", "GLU");
C$.modifications.put$O$O("DGN", "GLN");
C$.modifications.put$O$O("DHA", "SER");
C$.modifications.put$O$O("DHI", "HIS");
C$.modifications.put$O$O("DHL", "XAA");
C$.modifications.put$O$O("DHN", "VAL");
C$.modifications.put$O$O("DHP", "XAA");
C$.modifications.put$O$O("DHU", "UR3");
C$.modifications.put$O$O("DHV", "VAL");
C$.modifications.put$O$O("DI ", "ILE");
C$.modifications.put$O$O("DIL", "ILE");
C$.modifications.put$O$O("DIR", "ARG");
C$.modifications.put$O$O("DIV", "VAL");
C$.modifications.put$O$O("DLE", "LEU");
C$.modifications.put$O$O("DLS", "LYS");
C$.modifications.put$O$O("DLY", "LYS");
C$.modifications.put$O$O("DM0", "LYS");
C$.modifications.put$O$O("DMH", "ASN");
C$.modifications.put$O$O("DMK", "ASP");
C$.modifications.put$O$O("DMT", "XAA");
C$.modifications.put$O$O("DN ", "ASN");
C$.modifications.put$O$O("DNE", "LEU");
C$.modifications.put$O$O("DNG", "LEU");
C$.modifications.put$O$O("DNL", "LYS");
C$.modifications.put$O$O("DNM", "LEU");
C$.modifications.put$O$O("DNP", "ALA");
C$.modifications.put$O$O("DNR", "CYS");
C$.modifications.put$O$O("DNS", "LYS");
C$.modifications.put$O$O("DOA", "XAA");
C$.modifications.put$O$O("DOC", "CYS");
C$.modifications.put$O$O("DOH", "ASP");
C$.modifications.put$O$O("DON", "LEU");
C$.modifications.put$O$O("DPB", "THR");
C$.modifications.put$O$O("DPH", "PHE");
C$.modifications.put$O$O("DPL", "PRO");
C$.modifications.put$O$O("DPP", "ALA");
C$.modifications.put$O$O("DPQ", "TYR");
C$.modifications.put$O$O("DPR", "PRO");
C$.modifications.put$O$O("DPY", "ASN");
C$.modifications.put$O$O("DRM", "UR3");
C$.modifications.put$O$O("DRP", "ASN");
C$.modifications.put$O$O("DRT", "THR");
C$.modifications.put$O$O("DRZ", "ASN");
C$.modifications.put$O$O("DSE", "SER");
C$.modifications.put$O$O("DSG", "ASN");
C$.modifications.put$O$O("DSN", "SER");
C$.modifications.put$O$O("DSP", "ASP");
C$.modifications.put$O$O("DT ", "THR");
C$.modifications.put$O$O("DTH", "THR");
C$.modifications.put$O$O("DTR", "TRP");
C$.modifications.put$O$O("DTY", "TYR");
C$.modifications.put$O$O("DU ", "UR3");
C$.modifications.put$O$O("DVA", "VAL");
C$.modifications.put$O$O("DXD", "ASN");
C$.modifications.put$O$O("DXN", "ASN");
C$.modifications.put$O$O("DYG", "DYG");
C$.modifications.put$O$O("DYS", "CYS");
C$.modifications.put$O$O("DZM", "ALA");
C$.modifications.put$O$O("E  ", "ALA");
C$.modifications.put$O$O("E1X", "ALA");
C$.modifications.put$O$O("ECC", "GLN");
C$.modifications.put$O$O("EDA", "ALA");
C$.modifications.put$O$O("EFC", "CYS");
C$.modifications.put$O$O("EHP", "PHE");
C$.modifications.put$O$O("EIT", "THR");
C$.modifications.put$O$O("ENP", "ASN");
C$.modifications.put$O$O("ESB", "TYR");
C$.modifications.put$O$O("ESC", "MET");
C$.modifications.put$O$O("EXB", "XAA");
C$.modifications.put$O$O("EXY", "LEU");
C$.modifications.put$O$O("EY5", "ASN");
C$.modifications.put$O$O("EYS", "XAA");
C$.modifications.put$O$O("F2F", "PHE");
C$.modifications.put$O$O("FA2", "ALA");
C$.modifications.put$O$O("FA5", "ASN");
C$.modifications.put$O$O("FAG", "ASN");
C$.modifications.put$O$O("FAI", "ASN");
C$.modifications.put$O$O("FB5", "ALA");
C$.modifications.put$O$O("FB6", "ALA");
C$.modifications.put$O$O("FCL", "PHE");
C$.modifications.put$O$O("FFD", "ASN");
C$.modifications.put$O$O("FGA", "GLU");
C$.modifications.put$O$O("FGL", "GLY");
C$.modifications.put$O$O("FGP", "SER");
C$.modifications.put$O$O("FHL", "XAA");
C$.modifications.put$O$O("FHO", "LYS");
C$.modifications.put$O$O("FHU", "UR3");
C$.modifications.put$O$O("FLA", "ALA");
C$.modifications.put$O$O("FLE", "LEU");
C$.modifications.put$O$O("FLT", "TYR");
C$.modifications.put$O$O("FME", "MET");
C$.modifications.put$O$O("FMG", "GLY");
C$.modifications.put$O$O("FMU", "ASN");
C$.modifications.put$O$O("FOE", "CYS");
C$.modifications.put$O$O("FOX", "GLY");
C$.modifications.put$O$O("FP9", "PRO");
C$.modifications.put$O$O("FPA", "PHE");
C$.modifications.put$O$O("FRD", "XAA");
C$.modifications.put$O$O("FT6", "TRP");
C$.modifications.put$O$O("FTR", "TRP");
C$.modifications.put$O$O("FTY", "TYR");
C$.modifications.put$O$O("FVA", "VAL");
C$.modifications.put$O$O("FZN", "LYS");
C$.modifications.put$O$O("G  ", "GLY");
C$.modifications.put$O$O("G25", "GLY");
C$.modifications.put$O$O("G2L", "GLY");
C$.modifications.put$O$O("G2S", "GLY");
C$.modifications.put$O$O("G31", "GLY");
C$.modifications.put$O$O("G32", "GLY");
C$.modifications.put$O$O("G33", "GLY");
C$.modifications.put$O$O("G36", "GLY");
C$.modifications.put$O$O("G38", "GLY");
C$.modifications.put$O$O("G42", "GLY");
C$.modifications.put$O$O("G46", "GLY");
C$.modifications.put$O$O("G47", "GLY");
C$.modifications.put$O$O("G48", "GLY");
C$.modifications.put$O$O("G49", "GLY");
C$.modifications.put$O$O("G4P", "ASN");
C$.modifications.put$O$O("G7M", "GLY");
C$.modifications.put$O$O("GAO", "GLY");
C$.modifications.put$O$O("GAU", "GLU");
C$.modifications.put$O$O("GCK", "CYS");
C$.modifications.put$O$O("GCM", "XAA");
C$.modifications.put$O$O("GDP", "GLY");
C$.modifications.put$O$O("GDR", "GLY");
C$.modifications.put$O$O("GFL", "GLY");
C$.modifications.put$O$O("GGL", "GLU");
C$.modifications.put$O$O("GH3", "GLY");
C$.modifications.put$O$O("GHG", "GLN");
C$.modifications.put$O$O("GHP", "GLY");
C$.modifications.put$O$O("GL3", "GLY");
C$.modifications.put$O$O("GLH", "GLN");
C$.modifications.put$O$O("GLJ", "GLU");
C$.modifications.put$O$O("GLK", "GLU");
C$.modifications.put$O$O("GLM", "XAA");
C$.modifications.put$O$O("GLN", "GLN");
C$.modifications.put$O$O("GLQ", "GLU");
C$.modifications.put$O$O("GLU", "GLU");
C$.modifications.put$O$O("GLX", "GLX");
C$.modifications.put$O$O("GLY", "GLY");
C$.modifications.put$O$O("GLZ", "GLY");
C$.modifications.put$O$O("GMA", "GLU");
C$.modifications.put$O$O("GMS", "GLY");
C$.modifications.put$O$O("GMU", "UR3");
C$.modifications.put$O$O("GN7", "GLY");
C$.modifications.put$O$O("GND", "XAA");
C$.modifications.put$O$O("GNE", "ASN");
C$.modifications.put$O$O("GOM", "GLY");
C$.modifications.put$O$O("GPL", "LYS");
C$.modifications.put$O$O("GS ", "GLY");
C$.modifications.put$O$O("GSC", "GLY");
C$.modifications.put$O$O("GSR", "GLY");
C$.modifications.put$O$O("GSS", "GLY");
C$.modifications.put$O$O("GSU", "GLU");
C$.modifications.put$O$O("GT9", "CYS");
C$.modifications.put$O$O("GTP", "GLY");
C$.modifications.put$O$O("GVL", "XAA");
C$.modifications.put$O$O("GYC", "CYG");
C$.modifications.put$O$O("GYS", "SYG");
C$.modifications.put$O$O("H2U", "UR3");
C$.modifications.put$O$O("H5M", "PRO");
C$.modifications.put$O$O("HAC", "ALA");
C$.modifications.put$O$O("HAR", "ARG");
C$.modifications.put$O$O("HBN", "HIS");
C$.modifications.put$O$O("HCS", "XAA");
C$.modifications.put$O$O("HDP", "UR3");
C$.modifications.put$O$O("HEU", "UR3");
C$.modifications.put$O$O("HFA", "XAA");
C$.modifications.put$O$O("HGL", "XAA");
C$.modifications.put$O$O("HHI", "HIS");
C$.modifications.put$O$O("HHK", "AK");
C$.modifications.put$O$O("HIA", "HIS");
C$.modifications.put$O$O("HIC", "HIS");
C$.modifications.put$O$O("HIP", "HIS");
C$.modifications.put$O$O("HIQ", "HIS");
C$.modifications.put$O$O("HIS", "HIS");
C$.modifications.put$O$O("HL2", "LEU");
C$.modifications.put$O$O("HLU", "LEU");
C$.modifications.put$O$O("HMR", "ARG");
C$.modifications.put$O$O("HOL", "ASN");
C$.modifications.put$O$O("HPC", "PHE");
C$.modifications.put$O$O("HPE", "PHE");
C$.modifications.put$O$O("HPH", "PHE");
C$.modifications.put$O$O("HPQ", "PHE");
C$.modifications.put$O$O("HQA", "ALA");
C$.modifications.put$O$O("HRG", "ARG");
C$.modifications.put$O$O("HRP", "TRP");
C$.modifications.put$O$O("HS8", "HIS");
C$.modifications.put$O$O("HS9", "HIS");
C$.modifications.put$O$O("HSE", "SER");
C$.modifications.put$O$O("HSL", "SER");
C$.modifications.put$O$O("HSO", "HIS");
C$.modifications.put$O$O("HTI", "CYS");
C$.modifications.put$O$O("HTN", "ASN");
C$.modifications.put$O$O("HTR", "TRP");
C$.modifications.put$O$O("HV5", "ALA");
C$.modifications.put$O$O("HVA", "VAL");
C$.modifications.put$O$O("HY3", "PRO");
C$.modifications.put$O$O("HYP", "PRO");
C$.modifications.put$O$O("HZP", "PRO");
C$.modifications.put$O$O("I  ", "ILE");
C$.modifications.put$O$O("I2M", "ILE");
C$.modifications.put$O$O("I58", "LYS");
C$.modifications.put$O$O("I5C", "CYS");
C$.modifications.put$O$O("IAM", "ALA");
C$.modifications.put$O$O("IAR", "ARG");
C$.modifications.put$O$O("IAS", "ASP");
C$.modifications.put$O$O("IC ", "CYS");
C$.modifications.put$O$O("IEL", "LYS");
C$.modifications.put$O$O("IEY", "HYG");
C$.modifications.put$O$O("IG ", "GLY");
C$.modifications.put$O$O("IGL", "GLY");
C$.modifications.put$O$O("IGU", "GLY");
C$.modifications.put$O$O("IIC", "SHG");
C$.modifications.put$O$O("IIL", "ILE");
C$.modifications.put$O$O("ILE", "ILE");
C$.modifications.put$O$O("ILG", "GLU");
C$.modifications.put$O$O("ILX", "ILE");
C$.modifications.put$O$O("IMC", "CYS");
C$.modifications.put$O$O("IML", "ILE");
C$.modifications.put$O$O("IOY", "PHE");
C$.modifications.put$O$O("IPG", "GLY");
C$.modifications.put$O$O("IPN", "ASN");
C$.modifications.put$O$O("IRN", "ASN");
C$.modifications.put$O$O("IT1", "LYS");
C$.modifications.put$O$O("IU ", "UR3");
C$.modifications.put$O$O("IYR", "TYR");
C$.modifications.put$O$O("IYT", "THR");
C$.modifications.put$O$O("IZO", "MET");
C$.modifications.put$O$O("JJJ", "CYS");
C$.modifications.put$O$O("JJK", "CYS");
C$.modifications.put$O$O("JJL", "CYS");
C$.modifications.put$O$O("JW5", "ASN");
C$.modifications.put$O$O("K1R", "CYS");
C$.modifications.put$O$O("KAG", "GLY");
C$.modifications.put$O$O("KCX", "LYS");
C$.modifications.put$O$O("KGC", "LYS");
C$.modifications.put$O$O("KNB", "ALA");
C$.modifications.put$O$O("KOR", "MET");
C$.modifications.put$O$O("KPI", "LYS");
C$.modifications.put$O$O("KST", "LYS");
C$.modifications.put$O$O("KYQ", "LYS");
C$.modifications.put$O$O("L2A", "XAA");
C$.modifications.put$O$O("LA2", "LYS");
C$.modifications.put$O$O("LAA", "ASP");
C$.modifications.put$O$O("LAL", "ALA");
C$.modifications.put$O$O("LBY", "LYS");
C$.modifications.put$O$O("LC ", "CYS");
C$.modifications.put$O$O("LCA", "ALA");
C$.modifications.put$O$O("LCC", "ASN");
C$.modifications.put$O$O("LCG", "GLY");
C$.modifications.put$O$O("LCH", "ASN");
C$.modifications.put$O$O("LCK", "LYS");
C$.modifications.put$O$O("LCX", "LYS");
C$.modifications.put$O$O("LDH", "LYS");
C$.modifications.put$O$O("LED", "LEU");
C$.modifications.put$O$O("LEF", "LEU");
C$.modifications.put$O$O("LEH", "LEU");
C$.modifications.put$O$O("LEI", "VAL");
C$.modifications.put$O$O("LEM", "LEU");
C$.modifications.put$O$O("LEN", "LEU");
C$.modifications.put$O$O("LET", "XAA");
C$.modifications.put$O$O("LEU", "LEU");
C$.modifications.put$O$O("LEX", "LEU");
C$.modifications.put$O$O("LG ", "GLY");
C$.modifications.put$O$O("LGP", "GLY");
C$.modifications.put$O$O("LHC", "XAA");
C$.modifications.put$O$O("LHU", "UR3");
C$.modifications.put$O$O("LKC", "ASN");
C$.modifications.put$O$O("LLP", "LYS");
C$.modifications.put$O$O("LLY", "LYS");
C$.modifications.put$O$O("LME", "GLU");
C$.modifications.put$O$O("LMF", "LYS");
C$.modifications.put$O$O("LMQ", "GLN");
C$.modifications.put$O$O("LMS", "ASN");
C$.modifications.put$O$O("LP6", "LYS");
C$.modifications.put$O$O("LPD", "PRO");
C$.modifications.put$O$O("LPG", "GLY");
C$.modifications.put$O$O("LPL", "XAA");
C$.modifications.put$O$O("LPS", "SER");
C$.modifications.put$O$O("LSO", "XAA");
C$.modifications.put$O$O("LTA", "XAA");
C$.modifications.put$O$O("LTR", "TRP");
C$.modifications.put$O$O("LVG", "GLY");
C$.modifications.put$O$O("LVN", "VAL");
C$.modifications.put$O$O("LYF", "LYS");
C$.modifications.put$O$O("LYK", "LYS");
C$.modifications.put$O$O("LYM", "LYS");
C$.modifications.put$O$O("LYN", "LYS");
C$.modifications.put$O$O("LYR", "LYS");
C$.modifications.put$O$O("LYS", "LYS");
C$.modifications.put$O$O("LYX", "LYS");
C$.modifications.put$O$O("LYZ", "LYS");
C$.modifications.put$O$O("M0H", "CYS");
C$.modifications.put$O$O("M1G", "GLY");
C$.modifications.put$O$O("M2G", "GLY");
C$.modifications.put$O$O("M2L", "LYS");
C$.modifications.put$O$O("M2S", "MET");
C$.modifications.put$O$O("M30", "GLY");
C$.modifications.put$O$O("M3L", "LYS");
C$.modifications.put$O$O("M5M", "CYS");
C$.modifications.put$O$O("MA ", "ALA");
C$.modifications.put$O$O("MA6", "ALA");
C$.modifications.put$O$O("MA7", "ALA");
C$.modifications.put$O$O("MAA", "ALA");
C$.modifications.put$O$O("MAD", "ALA");
C$.modifications.put$O$O("MAI", "ARG");
C$.modifications.put$O$O("MBQ", "TYR");
C$.modifications.put$O$O("MBZ", "ASN");
C$.modifications.put$O$O("MC1", "SER");
C$.modifications.put$O$O("MCG", "XAA");
C$.modifications.put$O$O("MCL", "LYS");
C$.modifications.put$O$O("MCS", "CYS");
C$.modifications.put$O$O("MCY", "CYS");
C$.modifications.put$O$O("MD3", "CYS");
C$.modifications.put$O$O("MD6", "GLY");
C$.modifications.put$O$O("MDH", "XAA");
C$.modifications.put$O$O("MDO", "ASG");
C$.modifications.put$O$O("MDR", "ASN");
C$.modifications.put$O$O("MEA", "PHE");
C$.modifications.put$O$O("MED", "MET");
C$.modifications.put$O$O("MEG", "GLU");
C$.modifications.put$O$O("MEN", "ASN");
C$.modifications.put$O$O("MEP", "UR3");
C$.modifications.put$O$O("MEQ", "GLN");
C$.modifications.put$O$O("MET", "MET");
C$.modifications.put$O$O("MEU", "GLY");
C$.modifications.put$O$O("MF3", "XAA");
C$.modifications.put$O$O("MFC", "GYG");
C$.modifications.put$O$O("MG1", "GLY");
C$.modifications.put$O$O("MGG", "ARG");
C$.modifications.put$O$O("MGN", "GLN");
C$.modifications.put$O$O("MGQ", "ALA");
C$.modifications.put$O$O("MGV", "GLY");
C$.modifications.put$O$O("MGY", "GLY");
C$.modifications.put$O$O("MHL", "LEU");
C$.modifications.put$O$O("MHO", "MET");
C$.modifications.put$O$O("MHS", "HIS");
C$.modifications.put$O$O("MIA", "ALA");
C$.modifications.put$O$O("MIS", "SER");
C$.modifications.put$O$O("MK8", "LEU");
C$.modifications.put$O$O("ML3", "LYS");
C$.modifications.put$O$O("MLE", "LEU");
C$.modifications.put$O$O("MLL", "LEU");
C$.modifications.put$O$O("MLY", "LYS");
C$.modifications.put$O$O("MLZ", "LYS");
C$.modifications.put$O$O("MME", "MET");
C$.modifications.put$O$O("MMO", "ARG");
C$.modifications.put$O$O("MMT", "THR");
C$.modifications.put$O$O("MND", "ASN");
C$.modifications.put$O$O("MNL", "LEU");
C$.modifications.put$O$O("MNU", "UR3");
C$.modifications.put$O$O("MNV", "VAL");
C$.modifications.put$O$O("MOD", "XAA");
C$.modifications.put$O$O("MP8", "PRO");
C$.modifications.put$O$O("MPH", "XAA");
C$.modifications.put$O$O("MPJ", "XAA");
C$.modifications.put$O$O("MPQ", "GLY");
C$.modifications.put$O$O("MRG", "GLY");
C$.modifications.put$O$O("MSA", "GLY");
C$.modifications.put$O$O("MSE", "MET");
C$.modifications.put$O$O("MSL", "MET");
C$.modifications.put$O$O("MSO", "MET");
C$.modifications.put$O$O("MSP", "XAA");
C$.modifications.put$O$O("MT2", "MET");
C$.modifications.put$O$O("MTR", "THR");
C$.modifications.put$O$O("MTU", "ALA");
C$.modifications.put$O$O("MTY", "TYR");
C$.modifications.put$O$O("MVA", "VAL");
C$.modifications.put$O$O("N  ", "ASN");
C$.modifications.put$O$O("N10", "SER");
C$.modifications.put$O$O("N2C", "XAA");
C$.modifications.put$O$O("N5I", "ASN");
C$.modifications.put$O$O("N5M", "CYS");
C$.modifications.put$O$O("N6G", "GLY");
C$.modifications.put$O$O("N7P", "PRO");
C$.modifications.put$O$O("NA8", "ALA");
C$.modifications.put$O$O("NAL", "ALA");
C$.modifications.put$O$O("NAM", "ALA");
C$.modifications.put$O$O("NB8", "ASN");
C$.modifications.put$O$O("NBQ", "TYR");
C$.modifications.put$O$O("NC1", "SER");
C$.modifications.put$O$O("NCB", "ALA");
C$.modifications.put$O$O("NCX", "ASN");
C$.modifications.put$O$O("NCY", "XAA");
C$.modifications.put$O$O("NDF", "PHE");
C$.modifications.put$O$O("NDN", "UR3");
C$.modifications.put$O$O("NEM", "HIS");
C$.modifications.put$O$O("NEP", "HIS");
C$.modifications.put$O$O("NF2", "ASN");
C$.modifications.put$O$O("NFA", "PHE");
C$.modifications.put$O$O("NHL", "GLU");
C$.modifications.put$O$O("NIT", "XAA");
C$.modifications.put$O$O("NIY", "TYR");
C$.modifications.put$O$O("NLE", "LEU");
C$.modifications.put$O$O("NLN", "LEU");
C$.modifications.put$O$O("NLO", "LEU");
C$.modifications.put$O$O("NLP", "LEU");
C$.modifications.put$O$O("NLQ", "GLN");
C$.modifications.put$O$O("NMC", "GLY");
C$.modifications.put$O$O("NMM", "ARG");
C$.modifications.put$O$O("NMS", "THR");
C$.modifications.put$O$O("NMT", "THR");
C$.modifications.put$O$O("NNH", "ARG");
C$.modifications.put$O$O("NP3", "ASN");
C$.modifications.put$O$O("NPH", "CYS");
C$.modifications.put$O$O("NPI", "ALA");
C$.modifications.put$O$O("NRP", "LYG");
C$.modifications.put$O$O("NRQ", "MYG");
C$.modifications.put$O$O("NSK", "XAA");
C$.modifications.put$O$O("NTY", "TYR");
C$.modifications.put$O$O("NVA", "VAL");
C$.modifications.put$O$O("NYC", "TWG");
C$.modifications.put$O$O("NYG", "NYG");
C$.modifications.put$O$O("NYM", "ASN");
C$.modifications.put$O$O("NYS", "CYS");
C$.modifications.put$O$O("NZH", "HIS");
C$.modifications.put$O$O("O12", "XAA");
C$.modifications.put$O$O("O2C", "ASN");
C$.modifications.put$O$O("O2G", "GLY");
C$.modifications.put$O$O("OAD", "ASN");
C$.modifications.put$O$O("OAS", "SER");
C$.modifications.put$O$O("OBF", "XAA");
C$.modifications.put$O$O("OBS", "XAA");
C$.modifications.put$O$O("OCS", "CYS");
C$.modifications.put$O$O("OCY", "CYS");
C$.modifications.put$O$O("ODP", "ASN");
C$.modifications.put$O$O("OHI", "HIS");
C$.modifications.put$O$O("OHS", "ASP");
C$.modifications.put$O$O("OIC", "XAA");
C$.modifications.put$O$O("OIP", "ILE");
C$.modifications.put$O$O("OLE", "XAA");
C$.modifications.put$O$O("OLT", "THR");
C$.modifications.put$O$O("OLZ", "SER");
C$.modifications.put$O$O("OMC", "CYS");
C$.modifications.put$O$O("OMG", "GLY");
C$.modifications.put$O$O("OMT", "MET");
C$.modifications.put$O$O("OMU", "UR3");
C$.modifications.put$O$O("ONE", "UR3");
C$.modifications.put$O$O("ONH", "ALA");
C$.modifications.put$O$O("ONL", "XAA");
C$.modifications.put$O$O("OPR", "ARG");
C$.modifications.put$O$O("ORN", "ALA");
C$.modifications.put$O$O("ORQ", "ARG");
C$.modifications.put$O$O("OSE", "SER");
C$.modifications.put$O$O("OTB", "XAA");
C$.modifications.put$O$O("OTH", "THR");
C$.modifications.put$O$O("OTY", "TYR");
C$.modifications.put$O$O("OXX", "ASP");
C$.modifications.put$O$O("P  ", "GLY");
C$.modifications.put$O$O("P1L", "CYS");
C$.modifications.put$O$O("P1P", "ASN");
C$.modifications.put$O$O("P2T", "THR");
C$.modifications.put$O$O("P2U", "UR3");
C$.modifications.put$O$O("P2Y", "PRO");
C$.modifications.put$O$O("P5P", "ALA");
C$.modifications.put$O$O("PAQ", "TYR");
C$.modifications.put$O$O("PAS", "ASP");
C$.modifications.put$O$O("PAT", "TRP");
C$.modifications.put$O$O("PAU", "ALA");
C$.modifications.put$O$O("PBB", "CYS");
C$.modifications.put$O$O("PBF", "PHE");
C$.modifications.put$O$O("PBT", "ASN");
C$.modifications.put$O$O("PCA", "GLU");
C$.modifications.put$O$O("PCC", "PRO");
C$.modifications.put$O$O("PCE", "XAA");
C$.modifications.put$O$O("PCS", "PHE");
C$.modifications.put$O$O("PDL", "XAA");
C$.modifications.put$O$O("PDU", "UR3");
C$.modifications.put$O$O("PEC", "CYS");
C$.modifications.put$O$O("PF5", "PHE");
C$.modifications.put$O$O("PFF", "PHE");
C$.modifications.put$O$O("PFX", "XAA");
C$.modifications.put$O$O("PG1", "SER");
C$.modifications.put$O$O("PG7", "GLY");
C$.modifications.put$O$O("PG9", "GLY");
C$.modifications.put$O$O("PGL", "XAA");
C$.modifications.put$O$O("PGN", "GLY");
C$.modifications.put$O$O("PGP", "GLY");
C$.modifications.put$O$O("PGY", "GLY");
C$.modifications.put$O$O("PHA", "PHE");
C$.modifications.put$O$O("PHD", "ASP");
C$.modifications.put$O$O("PHE", "PHE");
C$.modifications.put$O$O("PHI", "PHE");
C$.modifications.put$O$O("PHL", "PHE");
C$.modifications.put$O$O("PHM", "PHE");
C$.modifications.put$O$O("PIA", "AYG");
C$.modifications.put$O$O("PIV", "XAA");
C$.modifications.put$O$O("PLE", "LEU");
C$.modifications.put$O$O("PM3", "PHE");
C$.modifications.put$O$O("PMT", "CYS");
C$.modifications.put$O$O("POM", "PRO");
C$.modifications.put$O$O("PPN", "PHE");
C$.modifications.put$O$O("PPU", "ALA");
C$.modifications.put$O$O("PPW", "GLY");
C$.modifications.put$O$O("PQ1", "ASN");
C$.modifications.put$O$O("PR3", "CYS");
C$.modifications.put$O$O("PR5", "ALA");
C$.modifications.put$O$O("PR9", "PRO");
C$.modifications.put$O$O("PRN", "ALA");
C$.modifications.put$O$O("PRO", "PRO");
C$.modifications.put$O$O("PRS", "PRO");
C$.modifications.put$O$O("PSA", "PHE");
C$.modifications.put$O$O("PSH", "HIS");
C$.modifications.put$O$O("PST", "THR");
C$.modifications.put$O$O("PSU", "UR3");
C$.modifications.put$O$O("PSW", "CYS");
C$.modifications.put$O$O("PTA", "XAA");
C$.modifications.put$O$O("PTH", "TYR");
C$.modifications.put$O$O("PTM", "TYR");
C$.modifications.put$O$O("PTR", "TYR");
C$.modifications.put$O$O("PU ", "ALA");
C$.modifications.put$O$O("PUY", "ASN");
C$.modifications.put$O$O("PVH", "HIS");
C$.modifications.put$O$O("PVL", "XAA");
C$.modifications.put$O$O("PYA", "ALA");
C$.modifications.put$O$O("PYO", "UR3");
C$.modifications.put$O$O("PYX", "CYS");
C$.modifications.put$O$O("PYY", "ASN");
C$.modifications.put$O$O("QLG", "QLG");
C$.modifications.put$O$O("QMM", "GLN");
C$.modifications.put$O$O("QPA", "CYS");
C$.modifications.put$O$O("QPH", "PHE");
C$.modifications.put$O$O("QUO", "GLY");
C$.modifications.put$O$O("R  ", "ALA");
C$.modifications.put$O$O("R1A", "CYS");
C$.modifications.put$O$O("R4K", "TRP");
C$.modifications.put$O$O("RC7", "HYG");
C$.modifications.put$O$O("RE0", "TRP");
C$.modifications.put$O$O("RE3", "TRP");
C$.modifications.put$O$O("RIA", "ALA");
C$.modifications.put$O$O("RMP", "ALA");
C$.modifications.put$O$O("RON", "XAA");
C$.modifications.put$O$O("RT ", "THR");
C$.modifications.put$O$O("RTP", "ASN");
C$.modifications.put$O$O("S1H", "SER");
C$.modifications.put$O$O("S2C", "CYS");
C$.modifications.put$O$O("S2D", "ALA");
C$.modifications.put$O$O("S2M", "THR");
C$.modifications.put$O$O("S2P", "ALA");
C$.modifications.put$O$O("S4A", "ALA");
C$.modifications.put$O$O("S4C", "CYS");
C$.modifications.put$O$O("S4G", "GLY");
C$.modifications.put$O$O("S4U", "UR3");
C$.modifications.put$O$O("S6G", "GLY");
C$.modifications.put$O$O("SAC", "SER");
C$.modifications.put$O$O("SAH", "CYS");
C$.modifications.put$O$O("SAR", "GLY");
C$.modifications.put$O$O("SBL", "SER");
C$.modifications.put$O$O("SC ", "CYS");
C$.modifications.put$O$O("SCH", "CYS");
C$.modifications.put$O$O("SCS", "CYS");
C$.modifications.put$O$O("SCY", "CYS");
C$.modifications.put$O$O("SD2", "XAA");
C$.modifications.put$O$O("SDG", "GLY");
C$.modifications.put$O$O("SDP", "SER");
C$.modifications.put$O$O("SEB", "SER");
C$.modifications.put$O$O("SEC", "ALA");
C$.modifications.put$O$O("SEG", "ALA");
C$.modifications.put$O$O("SEL", "SER");
C$.modifications.put$O$O("SEM", "SER");
C$.modifications.put$O$O("SEN", "SER");
C$.modifications.put$O$O("SEP", "SER");
C$.modifications.put$O$O("SER", "SER");
C$.modifications.put$O$O("SET", "SER");
C$.modifications.put$O$O("SGB", "SER");
C$.modifications.put$O$O("SHC", "CYS");
C$.modifications.put$O$O("SHP", "GLY");
C$.modifications.put$O$O("SHR", "LYS");
C$.modifications.put$O$O("SIB", "CYS");
C$.modifications.put$O$O("SIC", "DC");
C$.modifications.put$O$O("SLA", "PRO");
C$.modifications.put$O$O("SLR", "PRO");
C$.modifications.put$O$O("SLZ", "LYS");
C$.modifications.put$O$O("SMC", "CYS");
C$.modifications.put$O$O("SME", "MET");
C$.modifications.put$O$O("SMF", "PHE");
C$.modifications.put$O$O("SMP", "ALA");
C$.modifications.put$O$O("SMT", "THR");
C$.modifications.put$O$O("SNC", "CYS");
C$.modifications.put$O$O("SNN", "ASN");
C$.modifications.put$O$O("SOC", "CYS");
C$.modifications.put$O$O("SOS", "ASN");
C$.modifications.put$O$O("SOY", "SER");
C$.modifications.put$O$O("SPT", "THR");
C$.modifications.put$O$O("SRA", "ALA");
C$.modifications.put$O$O("SSU", "UR3");
C$.modifications.put$O$O("STY", "TYR");
C$.modifications.put$O$O("SUB", "XAA");
C$.modifications.put$O$O("SUI", "DG");
C$.modifications.put$O$O("SUN", "SER");
C$.modifications.put$O$O("SUR", "UR3");
C$.modifications.put$O$O("SVA", "SER");
C$.modifications.put$O$O("SVV", "SER");
C$.modifications.put$O$O("SVW", "SER");
C$.modifications.put$O$O("SVX", "SER");
C$.modifications.put$O$O("SVY", "SER");
C$.modifications.put$O$O("SVZ", "XAA");
C$.modifications.put$O$O("SWG", "SWG");
C$.modifications.put$O$O("SYS", "CYS");
C$.modifications.put$O$O("T  ", "THR");
C$.modifications.put$O$O("T11", "PHE");
C$.modifications.put$O$O("T23", "THR");
C$.modifications.put$O$O("T2S", "THR");
C$.modifications.put$O$O("T2T", "ASN");
C$.modifications.put$O$O("T31", "UR3");
C$.modifications.put$O$O("T32", "THR");
C$.modifications.put$O$O("T36", "THR");
C$.modifications.put$O$O("T37", "THR");
C$.modifications.put$O$O("T38", "THR");
C$.modifications.put$O$O("T39", "THR");
C$.modifications.put$O$O("T3P", "THR");
C$.modifications.put$O$O("T41", "THR");
C$.modifications.put$O$O("T48", "THR");
C$.modifications.put$O$O("T49", "THR");
C$.modifications.put$O$O("T4S", "THR");
C$.modifications.put$O$O("T5O", "UR3");
C$.modifications.put$O$O("T5S", "THR");
C$.modifications.put$O$O("T66", "XAA");
C$.modifications.put$O$O("T6A", "ALA");
C$.modifications.put$O$O("TA3", "THR");
C$.modifications.put$O$O("TA4", "XAA");
C$.modifications.put$O$O("TAF", "THR");
C$.modifications.put$O$O("TAL", "ASN");
C$.modifications.put$O$O("TAV", "ASP");
C$.modifications.put$O$O("TBG", "VAL");
C$.modifications.put$O$O("TBM", "THR");
C$.modifications.put$O$O("TC1", "CYS");
C$.modifications.put$O$O("TCP", "THR");
C$.modifications.put$O$O("TCQ", "TYR");
C$.modifications.put$O$O("TCR", "TRP");
C$.modifications.put$O$O("TCY", "ALA");
C$.modifications.put$O$O("TDD", "LEU");
C$.modifications.put$O$O("TDY", "THR");
C$.modifications.put$O$O("TFE", "THR");
C$.modifications.put$O$O("TFO", "ALA");
C$.modifications.put$O$O("TFQ", "PHE");
C$.modifications.put$O$O("TFT", "THR");
C$.modifications.put$O$O("TGP", "GLY");
C$.modifications.put$O$O("TH6", "THR");
C$.modifications.put$O$O("THC", "THR");
C$.modifications.put$O$O("THO", "XAA");
C$.modifications.put$O$O("THR", "THR");
C$.modifications.put$O$O("THX", "ASN");
C$.modifications.put$O$O("THZ", "ARG");
C$.modifications.put$O$O("TIH", "ALA");
C$.modifications.put$O$O("TLB", "ASN");
C$.modifications.put$O$O("TLC", "THR");
C$.modifications.put$O$O("TLN", "UR3");
C$.modifications.put$O$O("TMB", "THR");
C$.modifications.put$O$O("TMD", "THR");
C$.modifications.put$O$O("TNB", "CYS");
C$.modifications.put$O$O("TNR", "SER");
C$.modifications.put$O$O("TOX", "TRP");
C$.modifications.put$O$O("TP1", "THR");
C$.modifications.put$O$O("TPC", "CYS");
C$.modifications.put$O$O("TPG", "GLY");
C$.modifications.put$O$O("TPH", "XAA");
C$.modifications.put$O$O("TPL", "TRP");
C$.modifications.put$O$O("TPO", "THR");
C$.modifications.put$O$O("TPQ", "TYR");
C$.modifications.put$O$O("TQI", "TRP");
C$.modifications.put$O$O("TQQ", "TRP");
C$.modifications.put$O$O("TRF", "TRP");
C$.modifications.put$O$O("TRG", "LYS");
C$.modifications.put$O$O("TRN", "TRP");
C$.modifications.put$O$O("TRO", "TRP");
C$.modifications.put$O$O("TRP", "TRP");
C$.modifications.put$O$O("TRQ", "TRP");
C$.modifications.put$O$O("TRW", "TRP");
C$.modifications.put$O$O("TRX", "TRP");
C$.modifications.put$O$O("TS ", "ASN");
C$.modifications.put$O$O("TST", "XAA");
C$.modifications.put$O$O("TT ", "ASN");
C$.modifications.put$O$O("TTD", "THR");
C$.modifications.put$O$O("TTI", "UR3");
C$.modifications.put$O$O("TTM", "THR");
C$.modifications.put$O$O("TTQ", "TRP");
C$.modifications.put$O$O("TTS", "TYR");
C$.modifications.put$O$O("TY1", "TYR");
C$.modifications.put$O$O("TY2", "TYR");
C$.modifications.put$O$O("TY3", "TYR");
C$.modifications.put$O$O("TY5", "TYR");
C$.modifications.put$O$O("TYB", "TYR");
C$.modifications.put$O$O("TYI", "TYR");
C$.modifications.put$O$O("TYJ", "TYR");
C$.modifications.put$O$O("TYN", "TYR");
C$.modifications.put$O$O("TYO", "TYR");
C$.modifications.put$O$O("TYQ", "TYR");
C$.modifications.put$O$O("TYR", "TYR");
C$.modifications.put$O$O("TYS", "TYR");
C$.modifications.put$O$O("TYT", "TYR");
C$.modifications.put$O$O("TYU", "ASN");
C$.modifications.put$O$O("TYW", "TYR");
C$.modifications.put$O$O("TYX", "XAA");
C$.modifications.put$O$O("TYY", "TYR");
C$.modifications.put$O$O("TZB", "XAA");
C$.modifications.put$O$O("TZO", "XAA");
C$.modifications.put$O$O("U  ", "UR3");
C$.modifications.put$O$O("U25", "UR3");
C$.modifications.put$O$O("U2L", "UR3");
C$.modifications.put$O$O("U2N", "UR3");
C$.modifications.put$O$O("U2P", "UR3");
C$.modifications.put$O$O("U31", "UR3");
C$.modifications.put$O$O("U33", "UR3");
C$.modifications.put$O$O("U34", "UR3");
C$.modifications.put$O$O("U36", "UR3");
C$.modifications.put$O$O("U37", "UR3");
C$.modifications.put$O$O("U8U", "UR3");
C$.modifications.put$O$O("UAR", "UR3");
C$.modifications.put$O$O("UCL", "UR3");
C$.modifications.put$O$O("UD5", "UR3");
C$.modifications.put$O$O("UDP", "ASN");
C$.modifications.put$O$O("UFP", "ASN");
C$.modifications.put$O$O("UFR", "UR3");
C$.modifications.put$O$O("UFT", "UR3");
C$.modifications.put$O$O("UMA", "ALA");
C$.modifications.put$O$O("UMP", "UR3");
C$.modifications.put$O$O("UMS", "UR3");
C$.modifications.put$O$O("UN1", "XAA");
C$.modifications.put$O$O("UN2", "XAA");
C$.modifications.put$O$O("UNK", "XAA");
C$.modifications.put$O$O("UR3", "UR3");
C$.modifications.put$O$O("URD", "UR3");
C$.modifications.put$O$O("US1", "UR3");
C$.modifications.put$O$O("US2", "UR3");
C$.modifications.put$O$O("US3", "THR");
C$.modifications.put$O$O("US5", "UR3");
C$.modifications.put$O$O("USM", "UR3");
C$.modifications.put$O$O("VAD", "VAL");
C$.modifications.put$O$O("VAF", "VAL");
C$.modifications.put$O$O("VAL", "VAL");
C$.modifications.put$O$O("VB1", "LYS");
C$.modifications.put$O$O("VDL", "XAA");
C$.modifications.put$O$O("VLL", "XAA");
C$.modifications.put$O$O("VLM", "XAA");
C$.modifications.put$O$O("VMS", "XAA");
C$.modifications.put$O$O("VOL", "XAA");
C$.modifications.put$O$O("WCR", "GYG");
C$.modifications.put$O$O("X  ", "GLY");
C$.modifications.put$O$O("X2W", "GLU");
C$.modifications.put$O$O("X4A", "ASN");
C$.modifications.put$O$O("X9Q", "AFG");
C$.modifications.put$O$O("XAD", "ALA");
C$.modifications.put$O$O("XAE", "ASN");
C$.modifications.put$O$O("XAL", "ALA");
C$.modifications.put$O$O("XAR", "ASN");
C$.modifications.put$O$O("XCL", "CYS");
C$.modifications.put$O$O("XCN", "CYS");
C$.modifications.put$O$O("XCP", "XAA");
C$.modifications.put$O$O("XCR", "CYS");
C$.modifications.put$O$O("XCS", "ASN");
C$.modifications.put$O$O("XCT", "CYS");
C$.modifications.put$O$O("XCY", "CYS");
C$.modifications.put$O$O("XGA", "ASN");
C$.modifications.put$O$O("XGL", "GLY");
C$.modifications.put$O$O("XGR", "GLY");
C$.modifications.put$O$O("XGU", "GLY");
C$.modifications.put$O$O("XPR", "PRO");
C$.modifications.put$O$O("XSN", "ASN");
C$.modifications.put$O$O("XTH", "THR");
C$.modifications.put$O$O("XTL", "THR");
C$.modifications.put$O$O("XTR", "THR");
C$.modifications.put$O$O("XTS", "GLY");
C$.modifications.put$O$O("XTY", "ASN");
C$.modifications.put$O$O("XUA", "ALA");
C$.modifications.put$O$O("XUG", "GLY");
C$.modifications.put$O$O("XX1", "LYS");
C$.modifications.put$O$O("XXY", "THG");
C$.modifications.put$O$O("XYG", "DYG");
C$.modifications.put$O$O("Y  ", "ALA");
C$.modifications.put$O$O("YCM", "CYS");
C$.modifications.put$O$O("YG ", "GLY");
C$.modifications.put$O$O("YOF", "TYR");
C$.modifications.put$O$O("YRR", "ASN");
C$.modifications.put$O$O("YYG", "GLY");
C$.modifications.put$O$O("Z  ", "CYS");
C$.modifications.put$O$O("Z01", "ALA");
C$.modifications.put$O$O("ZAD", "ALA");
C$.modifications.put$O$O("ZAL", "ALA");
C$.modifications.put$O$O("ZBC", "CYS");
C$.modifications.put$O$O("ZBU", "UR3");
C$.modifications.put$O$O("ZCL", "PHE");
C$.modifications.put$O$O("ZCY", "CYS");
C$.modifications.put$O$O("ZDU", "UR3");
C$.modifications.put$O$O("ZFB", "XAA");
C$.modifications.put$O$O("ZGU", "GLY");
C$.modifications.put$O$O("ZHP", "ASN");
C$.modifications.put$O$O("ZTH", "THR");
C$.modifications.put$O$O("ZU0", "THR");
C$.modifications.put$O$O("ZZJ", "ALA");
};
};
})();
;Clazz.setTVer('3.3.1-v1');//Created 2022-07-13 14:45:40 Java2ScriptVisitor version 3.3.1-v1 net.sf.j2s.core.jar version 3.3.1-v1
